// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.layers;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class BaseDecodingOutputs extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BaseDecodingOutputs(Pointer p) { super(p); }

    public BaseDecodingOutputs(@ByVal @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIds) { super((Pointer)null); allocate(outputIds); }
    private native void allocate(@ByVal @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIds);

    /** Mandatory parameters */
    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIds(); public native BaseDecodingOutputs outputIds(ITensor setter); // [maxBatchSize, maxSeqLen]

    /** Optional parameters */
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor finished(); public native BaseDecodingOutputs finished(ITensor setter);       // [maxBatchSize * maxBeamWidth], on pinned
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor sequenceLength(); public native BaseDecodingOutputs sequenceLength(ITensor setter); // [maxBatchSize * maxBeamWidth], on gpu
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor cumLogProbs(); public native BaseDecodingOutputs cumLogProbs(ITensor setter);    // [maxBatchSize * maxBeamWidth], on gpu, for Beam Search
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor outputLogProbs(); public native BaseDecodingOutputs outputLogProbs(ITensor setter); // [maxBatchSize, maxBeamWidth, maxSeqLen], on gpu
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor parentIds(); public native BaseDecodingOutputs parentIds(ITensor setter);      // [maxBatchSize, maxBeamWidth, maxSeqLen], on gpu, for Beam Search

    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIdsPtr(); public native BaseDecodingOutputs outputIdsPtr(ITensor setter);     // [maxBatchSize][maxBeamWidth, maxSeqLen], on gpu and outputIdsPtr[i], on gpu
    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIdsPtrHost(); public native BaseDecodingOutputs outputIdsPtrHost(ITensor setter); // [maxBatchSize][maxBeamWidth, maxSeqLen], on cpu but outputIdsPtrHost[i], on gpu
    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor parentIdsPtr(); public native BaseDecodingOutputs parentIdsPtr(ITensor setter);     // [maxBatchSize][maxBeamWidth, maxSeqLen], on cpu but parentIdsPtr[i], on gpu
    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor newTokens(); public native BaseDecodingOutputs newTokens(ITensor setter);        // [maxBatchSize, maxBeamWidth], on gpu, tokens predicted at current iteration.

    // optional parameters
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor numNewTokens(); public native BaseDecodingOutputs numNewTokens(ITensor setter); // [maxBatchSize], on pinned, number of tokens predicted at current iteration
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor finishedSum(); public native BaseDecodingOutputs finishedSum(ITensor setter);  // [1], on pinned
    public native @Cast("tensorrt_llm::layers::TensorPtr*") @Optional ITensor outputLogProbsTiled(); public native BaseDecodingOutputs outputLogProbsTiled(ITensor setter); // [maxSeqLen, maxBatchSize, maxBeamWidth], on gpu

    // Beam width might change in Variable-Beam-Width-Search mode.
    // So the beam width is updated in beam search layer for the later layers.
    public native @Cast("tensorrt_llm::runtime::SizeType32") int beamWidth(); public native BaseDecodingOutputs beamWidth(int setter);
}
