// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.layers;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class BeamSearchOutputs extends BaseDecodingOutputs {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BeamSearchOutputs(Pointer p) { super(p); }

    public BeamSearchOutputs(@ByVal @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIds) { super((Pointer)null); allocate(outputIds); }
    private native void allocate(@ByVal @Cast("tensorrt_llm::layers::TensorPtr*") ITensor outputIds);

    public native @ByRef @Cast("tensorrt_llm::layers::TensorPtr*") ITensor tgtCacheIndirection(); public native BeamSearchOutputs tgtCacheIndirection(ITensor setter); //[forwardBatchSize, maxBeamWidth, maxSeqLen], on gpu, the k/v cache index

    public native @UniquePtr BeamHypotheses beamHypotheses(); public native BeamSearchOutputs beamHypotheses(BeamHypotheses setter); // Structure maintains variables of Beam Search
}
