// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.global;

import tensorrt_llm.thop.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class Thop extends tensorrt_llm.presets.ThopConfig {
    static { Loader.load(); }

// Parsed from tensorrt_llm/thop/thUtils.h

/*
 * Copyright (c) 2020-2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// #pragma once

// #include "tensorrt_llm/common/config.h"
// #include "tensorrt_llm/runtime/iTensor.h"

// #include <ATen/cuda/CUDAContext.h>
// #include <cuda_fp16.h>
// #include <cuda_runtime.h>
// #include <nvtx3/nvToolsExt.h>
// #include <torch/custom_class.h>
// #include <torch/extension.h>
// #include <torch/script.h>

// #include <cstdio>

// #define CHECK_TYPE(x, st)
//     TORCH_CHECK(x.scalar_type() == st, #x " dtype is ", x.scalar_type(), ", while ", st, " is expected")
// #define CHECK_TH_CUDA(x) TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor")
// #define CHECK_CPU(x) TORCH_CHECK(!x.is_cuda(), #x " must be a CPU tensor")
// #define CHECK_CONTIGUOUS(x) TORCH_CHECK(x.is_contiguous(), #x " must be contiguous")
// #define CHECK_INPUT(x, st)
//     CHECK_TH_CUDA(x);
//     CHECK_CONTIGUOUS(x);
//     CHECK_TYPE(x, st)
// #define CHECK_CPU_INPUT(x, st)
//     CHECK_CPU(x);
//     CHECK_CONTIGUOUS(x);
//     CHECK_TYPE(x, st)
// #define CHECK_OPTIONAL_INPUT(x, st)
//     if (x.has_value())
//     {
//         CHECK_INPUT(x.value(), st);
//     }
// #define CHECK_OPTIONAL_CPU_INPUT(x, st)
//     if (x.has_value())
//     {
//         CHECK_CPU_INPUT(x.value(), st);
//     }
// #define PRINT_TENSOR(x) std::cout << #x << ":\n" << x << std::endl
// #define PRINT_TENSOR_SIZE(x) std::cout << "size of " << #x << ": " << x.sizes() << std::endl

// TODO: switch to use torch native fp4 dtype when ready
@Namespace("tensorrt_llm::torch_ext") @MemberGetter public static native int FLOAT4_E2M1X2(); // uint8_t
@Namespace("tensorrt_llm::torch_ext") @MemberGetter public static native int SF_DTYPE();      // uint8_t

@Namespace("tensorrt_llm::torch_ext") @MemberGetter public static native int FP8_BLOCK_SCALING_SF_DTYPE();
@Namespace("tensorrt_llm::torch_ext") @MemberGetter public static native int FP8_ROWWISE_SF_DTYPE();

@Namespace("tensorrt_llm::torch_ext") public static native @ByVal Shape convert_shape(@ByVal Pointer tensor);

@Namespace("tensorrt_llm::torch_ext") public static native long sizeBytes(@ByVal Pointer tensor);

// from: cpp/tensorrt_llm/plugins/common/gemmPluginProfiler.h
@Namespace("tensorrt_llm::torch_ext") public static native int nextPowerOfTwo(int v);

// from: cpp/tensorrt_llm/plugins/lowLatencyGemmPlugin/lowLatencyGemmPlugin.cpp
@Namespace("tensorrt_llm::torch_ext") public static native @Optional FloatPointer getFloatEnv(@Cast("const char*") BytePointer name);
@Namespace("tensorrt_llm::torch_ext") public static native @Optional FloatBuffer getFloatEnv(String name);

@Namespace("tensorrt_llm::torch_ext") public static native @ByVal cudaDataType_t convert_torch_dtype(@ByVal ScalarType dtype);

 // namespace torch_ext




}
