// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DML.*;


@Namespace("Pointer") @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class DimXMinus extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public DimXMinus() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public DimXMinus(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DimXMinus(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public DimXMinus position(long position) {
        return (DimXMinus)super.position(position);
    }
    @Override public DimXMinus getPointer(long i) {
        return new DimXMinus((Pointer)this).offsetAddress(i);
    }

    public static native @Cast("bool") boolean constant();
    public static native @Cast("int64_t") long apply(@Cast("int64_t") long a, @Cast("int64_t") long b);

    public static native @StdString BytePointer ToString();
}
