// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DML.*;


@Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class ThreeInterpolateOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ThreeInterpolateOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    public native void Kernel(OpKernelContext context,
                            int b,
                            int c,
                            int m,
                            int n,
                            @Const FloatPointer points,
                            @Const IntPointer idx,
                            @Const FloatPointer weight,
                            FloatPointer out);
    public native void Kernel(OpKernelContext context,
                            int b,
                            int c,
                            int m,
                            int n,
                            @Const FloatBuffer points,
                            @Const IntBuffer idx,
                            @Const FloatBuffer weight,
                            FloatBuffer out);
    public native void Kernel(OpKernelContext context,
                            int b,
                            int c,
                            int m,
                            int n,
                            @Const float[] points,
                            @Const int[] idx,
                            @Const float[] weight,
                            float[] out);
}
