// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.io;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DIO.*;


/** class MKVMetadata
 * 
 *  AzureKinect mkv metadata. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DIOConfig.class)
public class MKVMetadata extends IJsonConvertible {
    static { Loader.load(); }
    /** Default native constructor. */
    public MKVMetadata() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MKVMetadata(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MKVMetadata(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MKVMetadata position(long position) {
        return (MKVMetadata)super.position(position);
    }
    @Override public MKVMetadata getPointer(long i) {
        return new MKVMetadata((Pointer)this).offsetAddress(i);
    }

    public native @Cast("bool") boolean ConvertToJsonValue(@ByRef Value value);
    public native @Cast("bool") boolean ConvertFromJsonValue(@Const @ByRef Value value);
    /** \brief Shared intrinsics between RGB & depth.
     * 
     *  We assume depth image is always warped to the color image system. */
    public native @ByRef PinholeCameraIntrinsic intrinsics_(); public native MKVMetadata intrinsics_(PinholeCameraIntrinsic setter);

    public native @StdString BytePointer serial_number_(); public native MKVMetadata serial_number_(BytePointer setter);
    /** Length of the video (usec). */
    public native @Cast("uint64_t") long stream_length_usec_(); public native MKVMetadata stream_length_usec_(long setter);
    /** Width of the video. */
    public native int width_(); public native MKVMetadata width_(int setter);
    /** Height of the video. */
    public native int height_(); public native MKVMetadata height_(int setter);
    public native @StdString BytePointer color_mode_(); public native MKVMetadata color_mode_(BytePointer setter);
    public native @StdString BytePointer depth_mode_(); public native MKVMetadata depth_mode_(BytePointer setter);
}
