// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::batch_manager::eviction_policy") @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class BaseEvictionPolicy extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BaseEvictionPolicy(Pointer p) { super(p); }


    // TODO(TRTLLM-1564): Don't use a separate `initialize` function. Ensure eviction policies can't be in-between a
    // state of construction and initialization.
    public native void initialize(@StdVector BlockPtr mAllBlocksById, @Cast("SizeType32*") @StdVector IntPointer sizes,
            @Cast("tensorrt_llm::executor::RetentionPriority*") @Optional IntPointer secondaryOffloadMinPriority);

    /** \brief Get a free block from the specified cache level
     *  @return The pointer to the free block, along with whether it can be offloaded */
    /** \brief Release a block. Prioritize the block for eviction if toFront=true */
    public native void releaseBlock(@ByVal BlockPtr block);
    public native void releaseBlock(@ByVal BlockPtr block, @Cast("bool") boolean toFront);
    /** \brief Get the amount of free blocks in the primary memory pool */
    public native @Cast("SizeType32") int getNumFreeBlocks(@Cast("SizeType32") int cacheLevel);
    /** \brief Claim a free block. Called when the cache manager allocates or reuses a new block */
    public native void claimBlock(@ByVal BlockPtr block);
    public native void claimBlock(@ByVal BlockPtr block, @Cast("tensorrt_llm::executor::RetentionPriority*") @Optional IntPointer priority,
            @Cast("std::chrono::milliseconds*") @Optional LongPointer durationMs);
    /** \brief Perform any per-iteration bookkeeping */
    public native void refresh();

    public native @Cast("bool") boolean verifyQueueIntegrity();
}
