// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Opaque @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class BufferManagerTest extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public BufferManagerTest() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BufferManagerTest(Pointer p) { super(p); }
}
