// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief A wrapper around {@code nvinfer1::DataType} that provides a support for pointer types. */
@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class BufferDataType extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public BufferDataType() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public BufferDataType(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BufferDataType(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public BufferDataType position(long position) {
        return (BufferDataType)super.position(position);
    }
    @Override public BufferDataType getPointer(long i) {
        return new BufferDataType((Pointer)this).offsetAddress(i);
    }


    public native @Cast("const bool") @NoException(true) boolean isPointer();

    public native @Cast("const bool") boolean isUnsigned();

    public native @Cast("const std::size_t") @NoException(true) long getSize();

    public native @Cast("const std::size_t") @NoException(true) long getSizeInBits();
}
