// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class CacheTransceiverComm extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CacheTransceiverComm(Pointer p) { super(p); }

    // Construct from a non-owning raw pointer, won't take ownership of the pointer
    public CacheTransceiverComm(@Const MpiComm mpiComm) { super((Pointer)null); allocate(mpiComm); }
    private native void allocate(@Const MpiComm mpiComm);

    // Construct from a shared_ptr with shared ownership

    // Construct from a ProcessGroup communicator
    public CacheTransceiverComm(@ByVal c10::intrusive_ptr<c10d::ProcessGroup> pgComm) { super((Pointer)null); allocate(pgComm); }
    private native void allocate(@ByVal c10::intrusive_ptr<c10d::ProcessGroup> pgComm);

    public native @Cast("bool") @NoException(true) boolean isMpi();

    public native int getRank();

    public native int getSize();

    public native void allgather(@Const Pointer sendbuf, Pointer recvbuf, int count, @ByVal MpiType dtype);

    public native @Cast("bool") boolean allgatherv(@Const Pointer sendbuf, int sendcount, @ByVal MpiType sendtype, Pointer recvbuf,
            @Const @StdVector @ByRef IntPointer recvcounts, @Const @StdVector @ByRef IntPointer displs, @ByVal MpiType recvtype);

    public native @ByVal CacheTransceiverComm split(int color, int key);
}
