// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class DecoderOutputBuffers extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DecoderOutputBuffers(Pointer p) { super(p); }


    public DecoderOutputBuffers(@Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxNumSequences, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxBeamWidth, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxSeqLen,
            @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxTokensPerStep, @Const @ByRef BufferManager manager) { super((Pointer)null); allocate(maxNumSequences, maxBeamWidth, maxSeqLen, maxTokensPerStep, manager); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxNumSequences, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxBeamWidth, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxSeqLen,
            @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxTokensPerStep, @Const @ByRef BufferManager manager);

    public native void enableLookaheadDecoding(@Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxNumSequences, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxTokensPerStep);
    public native void disableLookaheadDecoding(@Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxNumSequences);

    public native void setupSpeculativeDecoding(
            @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxNumSequences, @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::SizeType32") int maxTokensPerStep, @Const @ByRef ModelConfig modelConfig);

    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor sequenceLengthsHost(); public native DecoderOutputBuffers sequenceLengthsHost(ITensor setter); // [mMaxNumRequests, beamWidth], pinned host tensor
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor newOutputTokensHost(); public native DecoderOutputBuffers newOutputTokensHost(ITensor setter); // [maxTokensPerStep, mMaxNumRequests, beamWidth]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor cumLogProbsHost(); public native DecoderOutputBuffers cumLogProbsHost(ITensor setter);     // [mMaxNumRequests, beamWidth]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor logProbsHost(); public native DecoderOutputBuffers logProbsHost(ITensor setter);        // [mMaxNumRequests, beamWidth, maxSeqLen]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor finishedSumHost(); public native DecoderOutputBuffers finishedSumHost(ITensor setter);     // [mMaxNumRequests], pinned host tensor
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor finishReasonsHost(); public native DecoderOutputBuffers finishReasonsHost(ITensor setter);   // [mMaxNumRequests, beamWidth], pinned host tensor

    // speculative decoding buffers
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor nextDraftTokensHost(); public native DecoderOutputBuffers nextDraftTokensHost(ITensor setter);        // [mMaxNumRequests, maxTokensPerStep-1]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor prevDraftTokensLengthsHost(); public native DecoderOutputBuffers prevDraftTokensLengthsHost(ITensor setter); // [mMaxNumRequests]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderOutputBuffers::TensorPtr*") ITensor nextDraftTokensLengthsHost(); public native DecoderOutputBuffers nextDraftTokensLengthsHost(ITensor setter); // [mMaxNumRequests]
}
