// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
// namespace kv_cache_manager

@Namespace("tensorrt_llm::batch_manager") @Opaque @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class EncoderBuffers extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public EncoderBuffers() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public EncoderBuffers(Pointer p) { super(p); }
}
