// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
// namespace tensorrt_llm::runtime

@Namespace("tensorrt_llm::batch_manager") @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class HandleContextLogits extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public HandleContextLogits(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public HandleContextLogits(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public HandleContextLogits position(long position) {
        return (HandleContextLogits)super.position(position);
    }
    @Override public HandleContextLogits getPointer(long i) {
        return new HandleContextLogits((Pointer)this).offsetAddress(i);
    }


    public HandleContextLogits() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Cast("tensorrt_llm::runtime::SizeType32") @Name("operator ()") int apply(@ByRef DecoderInputBuffers inputBuffers, @SharedPtr LlmRequest contextRequests,
            @Const @ByRef ITensor logits, @Const @StdVector @ByRef IntPointer numContextLogitsVec,
            @Const @ByRef ModelConfig modelConfig, @Const @ByRef BufferManager manager,
            @ByVal tensorrt_llm::batch_manager::HandleContextLogits::OptionalRef<tensorrt_llm::batch_manager::MedusaBuffers> medusaBuffers);
}
