// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
// namespace tensorrt_llm::runtime

@Namespace("tensorrt_llm::batch_manager") @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class HandleGenerationLogits extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public HandleGenerationLogits(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public HandleGenerationLogits(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public HandleGenerationLogits position(long position) {
        return (HandleGenerationLogits)super.position(position);
    }
    @Override public HandleGenerationLogits getPointer(long i) {
        return new HandleGenerationLogits((Pointer)this).offsetAddress(i);
    }


    public HandleGenerationLogits() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Name("operator ()") void apply(@ByRef DecoderInputBuffers inputBuffers, @SharedPtr LlmRequest generationRequests,
            @Const @ByRef ITensor logits, @Cast("tensorrt_llm::runtime::SizeType32") int logitsIndex,
            @Const @ByRef ModelConfig modelConfig, @Const @ByRef BufferManager manager,
            @ByVal tensorrt_llm::batch_manager::HandleGenerationLogits::OptionalRef<tensorrt_llm::batch_manager::RuntimeBuffers> genRuntimeBuffers, @ByVal tensorrt_llm::batch_manager::HandleGenerationLogits::OptionalRef<tensorrt_llm::batch_manager::MedusaBuffers> medusaBuffers);
}
