// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief Multimodal input data class */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class MultimodalInput extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MultimodalInput(Pointer p) { super(p); }

    public MultimodalInput(@StdVector @StdVector IntPointer multimodalHashes,
            @StdVector @ByVal IntPointer multimodalPositions, @StdVector @ByVal IntPointer multimodalLengths) { super((Pointer)null); allocate(multimodalHashes, multimodalPositions, multimodalLengths); }
    private native void allocate(@StdVector @StdVector IntPointer multimodalHashes,
            @StdVector @ByVal IntPointer multimodalPositions, @StdVector @ByVal IntPointer multimodalLengths);

    public native @StdVector @StdVector IntPointer getMultimodalHashes();
    public native @StdVector @ByVal IntPointer getMultimodalPositions();
    public native @StdVector @ByVal IntPointer getMultimodalLengths();
}
