// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief Split vector into list of blocks of given size.
 *  @param vec vector to split
 *  @param usableSize part of the vector that is processed
 *  @param elementsPerBlock desired size of blocks
 *  @param allowPartial whether to append a block smaller than {@code elementsPerBlock} at the end
 *  @return list of blocks */

@Namespace("tensorrt_llm::batch_manager::kv_cache_manager") @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class TempAttentionWindowInputs extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public TempAttentionWindowInputs() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public TempAttentionWindowInputs(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TempAttentionWindowInputs(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public TempAttentionWindowInputs position(long position) {
        return (TempAttentionWindowInputs)super.position(position);
    }
    @Override public TempAttentionWindowInputs getPointer(long i) {
        return new TempAttentionWindowInputs((Pointer)this).offsetAddress(i);
    }

    public native @Cast("bool") boolean pagedContextFMHA(); public native TempAttentionWindowInputs pagedContextFMHA(boolean setter);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::SizeType32") int maxInputLen(); public native TempAttentionWindowInputs maxInputLen(int setter);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::SizeType32") int maxNumTokens(); public native TempAttentionWindowInputs maxNumTokens(int setter);
}
