// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.common;


import tensorrt_llm.global.Common;
import tensorrt_llm.presets.CommonConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Common.*;

@Namespace("tensorrt_llm::runtime") @Opaque @Properties(inherit = tensorrt_llm.presets.CommonConfig.class)
public class McastDeviceMemory extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public McastDeviceMemory() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public McastDeviceMemory(Pointer p) { super(p); }
}
