// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.common;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Common.*;


@Namespace("tensorrt_llm::common") @NoOffset @Properties(inherit = tensorrt_llm.presets.CommonConfig.class)
public class TllmException extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TllmException(Pointer p) { super(p); }

    @MemberGetter public static native int MAX_FRAMES();
    public static final int MAX_FRAMES = MAX_FRAMES();

    public TllmException(@Cast("const char*") BytePointer file, long line, @Cast("const char*") BytePointer msg) { super((Pointer)null); allocate(file, line, msg); }
    private native void allocate(@Cast("const char*") BytePointer file, long line, @Cast("const char*") BytePointer msg);
    public TllmException(String file, long line, String msg) { super((Pointer)null); allocate(file, line, msg); }
    private native void allocate(String file, long line, String msg);

    public native @StdString BytePointer getTrace();

    public static native @StdString BytePointer demangle(@Cast("const char*") BytePointer name);
    public static native @StdString String demangle(String name);
}
