// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


// Base class with common code for the OpKernel implementations
@Namespace("nms_opkernel") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class NmsOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public NmsOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    // Function with the device specific code
    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor boxes,
                            @Const @ByRef Tensor scores);
}
