// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


// Base class with common code for the OpKernel implementations
@Namespace("voxel_pooling_opkernel") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class VoxelPoolingGradOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public VoxelPoolingGradOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    // Function with the device specific code
    public native void Kernel(OpKernelContext context,
                            @ByRef Tensor features_backprop,
                            @Const @ByRef Tensor positions,
                            @Const @ByRef Tensor features,
                            @Const @ByRef Tensor pooled_positions,
                            @Const @ByRef Tensor pooled_features_gradient,
                            @Const @ByRef Tensor voxel_size);
}
