#!/bin/bash
# 为缺失的10个Layer创建Opaque stub，让JavaCPP生成

cd /Users/mullerzhang/IdeaProjects/TRTLLM-Java-Bridge

MISSING_LAYERS=(
    "DecodingLayer"
    "DynamicDecodeLayer"
    "BanWordsLayer"
    "StopCriteriaLayer"
    "BeamSearchLayer"
    "MedusaDecodingLayer"
    "EagleDecodingLayer"
    "LookaheadDecodingLayer"
    "ExplicitDraftTokensLayer"
    "ExternalDraftTokensLayer"
)

echo "创建缺失Layer的Opaque stub..."
for layer in "${MISSING_LAYERS[@]}"; do
    cat > "src/main/java/org/bytedeco/tensorrt_llm/${layer}.java" << EOF
// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


@Namespace("tensorrt_llm::layers") @Opaque @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class ${layer} extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ${layer}(Pointer p) { super(p); }
}
EOF
    echo "✓ 创建了 ${layer}.java"
done

echo ""
echo "现在编译..."
mvn clean compile -DskipTests -q && echo "✓ 编译成功"

echo ""
echo "验证所有15个Layer文件..."
find src/main/java/org/bytedeco/tensorrt_llm -name "*Layer.java" -type f | wc -l

echo ""
echo "列出所有Layer文件:"
find src/main/java/org/bytedeco/tensorrt_llm -name "*Layer.java" -type f | xargs basename -a | sort

