// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class LoraCacheFullException extends LoraExpectedException {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LoraCacheFullException(Pointer p) { super(p); }

    public LoraCacheFullException(@StdString BytePointer msg) { super((Pointer)null); allocate(msg); }
    private native void allocate(@StdString BytePointer msg);
    public LoraCacheFullException(@StdString String msg) { super((Pointer)null); allocate(msg); }
    private native void allocate(@StdString String msg);
}
