// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class MedusaModule extends SpeculativeDecodingModule {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MedusaModule(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MedusaModule(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public MedusaModule position(long position) {
        return (MedusaModule)super.position(position);
    }
    @Override public MedusaModule getPointer(long i) {
        return new MedusaModule((Pointer)this).offsetAddress(i);
    }


    public MedusaModule(int maxAcceptedTokens, int maxDraftTokens) { super((Pointer)null); allocate(maxAcceptedTokens, maxDraftTokens); }
    @NoException(true) private native void allocate(int maxAcceptedTokens, int maxDraftTokens);

    public MedusaModule() { super((Pointer)null); allocate(); }
    @NoException(true) private native void allocate();

    public native @StdVector @NoException(true) IntPointer getMedusaChoices();
}
