// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


@NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class BuildSpatialHashTableOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BuildSpatialHashTableOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor points,
                            @Const @ByRef Tensor radius,
                            @Const @ByRef Tensor points_row_splits,
                            @Cast("uint32_t*") @StdVector IntPointer hash_table_splits,
                            @ByRef Tensor hash_table_index,
                            @ByRef Tensor hash_table_cell_splits);
    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor points,
                            @Const @ByRef Tensor radius,
                            @Const @ByRef Tensor points_row_splits,
                            @Cast("uint32_t*") @StdVector IntBuffer hash_table_splits,
                            @ByRef Tensor hash_table_index,
                            @ByRef Tensor hash_table_cell_splits);
    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor points,
                            @Const @ByRef Tensor radius,
                            @Const @ByRef Tensor points_row_splits,
                            @Cast("uint32_t*") @StdVector int[] hash_table_splits,
                            @ByRef Tensor hash_table_index,
                            @ByRef Tensor hash_table_cell_splits);
}
