// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


//
// Dim expression operator classes
//

@Namespace("open3d::ml::op_util") @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class DimXPlus extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public DimXPlus() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public DimXPlus(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DimXPlus(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public DimXPlus position(long position) {
        return (DimXPlus)super.position(position);
    }
    @Override public DimXPlus getPointer(long i) {
        return new DimXPlus((Pointer)this).offsetAddress(i);
    }

    public static native @Cast("bool") boolean constant();
    public static native @Cast("int64_t") long apply(@Cast("int64_t") long a, @Cast("int64_t") long b);

    public static native @StdString BytePointer ToString();
}
