// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


// Base class with common code for the OpKernel implementations
@Namespace("invert_neighbors_list_opkernel") @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class InvertNeighborsListOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public InvertNeighborsListOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    // Function with the device specific code
    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor inp_neighbors_index,
                            @Const @ByRef Tensor inp_neighbors_row_splits,
                            @Const @ByRef Tensor inp_neighbors_attributes,
                            int num_attributes,
                            @ByRef Tensor neighbors_index,
                            @ByRef Tensor neighbors_row_splits,
                            @ByRef Tensor neighbors_attributes);
}
