// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


/** A class for managing memory segments within a memory allocation. */
@Namespace("open3d::ml::impl") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class MemoryAllocation extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MemoryAllocation(Pointer p) { super(p); }

    /** Creates a MemoryAllocation object that manages memory segments within
     *  a memory allocation.
     * 
     *  @param ptr          Pointer to the beginning of the memory.
     *  @param size         Size of the memory.
     *  @param alignment    The alignment for returned segments.
     *  */
    public MemoryAllocation(Pointer ptr, long size, long alignment/*=1*/) { super((Pointer)null); allocate(ptr, size, alignment); }
    private native void allocate(Pointer ptr, long size, long alignment/*=1*/);
    public MemoryAllocation(Pointer ptr, long size) { super((Pointer)null); allocate(ptr, size); }
    private native void allocate(Pointer ptr, long size);

    /** Returns a memory segment with size for type T.
     *  Returns the pointer and the size in number of elements T.
     *  May return the pair (nullptr,0) if the allocation is not possible. */

    /** Returns a memory segment with size in bytes.
     *  May return the pair (nullptr,0) if the allocation is not possible. */
    public native @ByVal std::pair<void*,size_t> Alloc(long size);

    /** Returns the largest free segment. */
    public native @ByVal std::pair<void*,size_t> AllocLargestSegment();

    /** Frees a previously returned segment. */

    /** Frees a previously returned segment. */
    public native void Free(@Const @ByRef std::pair<void*,size_t> segment);

    /** Returns the peak memory usage in bytes. */
    public native long MaxUsed();

    /** Returns the alignment in bytes. */
    public native long Alignment();

    /** Returns the list of free segments. */
    public native @StdVector std::pair<void*,size_t> FreeSegments();

    /** Prints the segment. Meant for debugging. */

    /** Prints all free segments. Meant for debugging. */
    public native void PrintFreeSegments();
}
