// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


/** \cond */
// namespace for code that is common for all kernels

@Namespace("radius_search_opkernel") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class RadiusSearchOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RadiusSearchOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor points,
                            @Const @ByRef Tensor queries,
                            @Const @ByRef Tensor radius,
                            @Const @ByRef Tensor points_row_splits,
                            @Const @ByRef Tensor queries_row_splits,
                            @ByRef Tensor query_neighbors_row_splits);
}
