// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.ml;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DML.*;


// Base class with common code for the OpKernel implementations
@Namespace("voxelize_opkernel") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DMLConfig.class)
public class VoxelizeOpKernel extends OpKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public VoxelizeOpKernel(Pointer p) { super(p); }


    public native void Compute(OpKernelContext context);

    // Function with the device specific code
    public native void Kernel(OpKernelContext context,
                            @Const @ByRef Tensor points,
                            @Const @ByRef Tensor row_splits,
                            @Const @ByRef Tensor voxel_size,
                            @Const @ByRef Tensor points_range_min,
                            @Const @ByRef Tensor points_range_max);
}
