// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.TrtllmRuntime.*;


@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class GptJsonConfig extends Pointer {
    // [CPP-FIX] broken decl removed:
    // static { Loader.load(); }
    // /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    // public GptJsonConfig(Pointer p) { super(p); }
    // 
    // public GptJsonConfig(@StdString BytePointer name, @StdString BytePointer version, @StdString BytePointer precision, int tensorParallelism,
    // int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig,
    // // [CPP-FIX] @Optional RuntimeDefaults runtimeDefaults/*=std::nullopt*/) { super((Pointer)null); allocate(name, version, precision, tensorParallelism, pipelineParallelism, contextParallelism, gpusPerNode, modelConfig, runtimeDefaults); }
    // // [CPP-FIX] broken signature removed:
    // // private native void allocate(@StdString BytePointer name, @StdString BytePointer version, @StdString BytePointer precision, int tensorParallelism,
    // // int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig,
    // // // [CPP-FIX] @Optional RuntimeDefaults runtimeDefaults/*=std::nullopt*/);
    public GptJsonConfig(@StdString BytePointer name, @StdString BytePointer version, @StdString BytePointer precision, int tensorParallelism);
            int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig) { super((Pointer)null); allocate(name, version, precision, tensorParallelism, pipelineParallelism, contextParallelism, gpusPerNode, modelConfig); }
    private native void allocate(@StdString BytePointer name, @StdString BytePointer version, @StdString BytePointer precision, int tensorParallelism,
            int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig);
    // [CPP-FIX] broken decl removed:
    // public GptJsonConfig(@StdString String name, @StdString String version, @StdString String precision, int tensorParallelism,
    // int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig,
    // // [CPP-FIX] @Optional RuntimeDefaults runtimeDefaults/*=std::nullopt*/) { super((Pointer)null); allocate(name, version, precision, tensorParallelism, pipelineParallelism, contextParallelism, gpusPerNode, modelConfig, runtimeDefaults); }
    // // [CPP-FIX] broken signature removed:
    // // private native void allocate(@StdString String name, @StdString String version, @StdString String precision, int tensorParallelism,
    // // int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig,
    // // // [CPP-FIX] @Optional RuntimeDefaults runtimeDefaults/*=std::nullopt*/);
    public GptJsonConfig(@StdString String name, @StdString String version, @StdString String precision, int tensorParallelism);
            int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig) { super((Pointer)null); allocate(name, version, precision, tensorParallelism, pipelineParallelism, contextParallelism, gpusPerNode, modelConfig); }
    private native void allocate(@StdString String name, @StdString String version, @StdString String precision, int tensorParallelism,
            int pipelineParallelism, int contextParallelism, int gpusPerNode, @ByVal ModelConfig modelConfig);

    public static native @ByVal GptJsonConfig parse(@StdString BytePointer json);
    public static native @ByVal GptJsonConfig parse(@StdString String json);

    public static native @ByVal GptJsonConfig parse(@Cast("std::istream*") @ByRef Pointer json);

    public native @Const @ByRef ModelConfig getModelConfig();

    public native @ByRef ModelConfig getModelConfigMutable();

    public native @StdString BytePointer getName();

    public native @StdString BytePointer getVersion();

    public native @StdString BytePointer getPrecision();

    public native int getTensorParallelism();

    public native int getPipelineParallelism();

    public native int getContextParallelism();

    public native int getGpusPerNode();

    public native int getWorldSize();

    public native @Optional RuntimeDefaults getRuntimeDefaults();

    public native @StdString BytePointer engineFilename(@Const @ByRef WorldConfig worldConfig, @StdString BytePointer model);
    public native @StdString String engineFilename(@Const @ByRef WorldConfig worldConfig, @StdString String model);

    public native @StdString BytePointer engineFilename(@Const @ByRef WorldConfig worldConfig);
}
