// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.TrtllmRuntime.*;

@Namespace("tensorrt_llm::batch_manager") @Opaque @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class LlmRequest extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public LlmRequest() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LlmRequest(Pointer p) { super(p); }
}
