// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;


import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class MoePlacementCpuInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MoePlacementCpuInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MoePlacementCpuInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MoePlacementCpuInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MoePlacementCpuInfo position(long position) {
        return (MoePlacementCpuInfo)super.position(position);
    }
    @Override public MoePlacementCpuInfo getPointer(long i) {
        return new MoePlacementCpuInfo((Pointer)this).offsetAddress(i);
    }

    public native @StdVector IntPointer expertReplicaCount(); public native MoePlacementCpuInfo expertReplicaCount(IntPointer setter);

    // rankExpertIds[i][j] is the list of expert ids for rank i's j-th slot
    // all ranks have the same number of slots, so rankExpertIds is a vector of vectors.
    // it can also be a tensor of shape [epSize, slotCountPerRank]
    // SKIPPED (leaked C++ type): public native @StdVector std::vector<int> rankExpertIds(); public native MoePlacementCpuInfo rankExpertIds(std::vector<int> setter);

    // oldRankExpertIds[i][j] is the list of old rank ids for expert i's j-th replica
    // same as rankExpertIds but holding the last iteration's rank ids
    // SKIPPED (leaked C++ type): public native @StdVector std::vector<int> oldRankExpertIds(); public native MoePlacementCpuInfo oldRankExpertIds(std::vector<int> setter);

    public native @ByRef MoePlacementInfo placementInfoForGPU(); public native MoePlacementCpuInfo placementInfoForGPU(MoePlacementInfo setter);
}
