// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;


import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class MoeWeight extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MoeWeight() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MoeWeight(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MoeWeight(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MoeWeight position(long position) {
        return (MoeWeight)super.position(position);
    }
    @Override public MoeWeight getPointer(long i) {
        return new MoeWeight((Pointer)this).offsetAddress(i);
    }

    // use 2D layout to support stride tensor using cudaMemcpy2D
    public native Pointer mWeightPtr(); public native MoeWeight mWeightPtr(Pointer setter);
    public native long mHeight(); public native MoeWeight mHeight(long setter);
    public native long mWidth(); public native MoeWeight mWidth(long setter);
    public native long mPitch(); public native MoeWeight mPitch(long setter);

    public native long getWeightPtr();

    public native void setWeightPtr(long weightPtr);
}
