// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;


import tensorrt_llm.global.Executor.DataType;
import tensorrt_llm.executor.Shape;
import tensorrt_llm.executor.Tensor;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class TorchView extends ITensor {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TorchView(Pointer p) { super(p); }
    /** Downcast constructor. */
    public TorchView(ITensor pointer) { super((Pointer)null); allocate(pointer); }
    @Namespace private native @Name("dynamic_cast<Pointer*>") void allocate(ITensor pointer);
    public ITensor asITensor() { return asITensor(this); }
    @Namespace public static native @Name("static_cast<Pointer*>") ITensor asITensor(TorchView pointer);

    public static native @UniquePtr ITensor of(@ByRef(true) Tensor tensor);

    public native Pointer data();

    public native long getSize();

    public native long getCapacity();

    public native @Cast("nvinfer1::DataType") int getDataType();

    public native @Cast("tensorrt_llm::runtime::MemoryType") int getMemoryType();

    public native void release();

    public native @Const @ByRef Pointer getShape();

    public native void reshape(@Const @ByRef Pointer dims);
}
