// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor") @Opaque @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class Model extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public Model() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Model(Pointer p) { super(p); }
}
