// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class OrchestratorConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public OrchestratorConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public OrchestratorConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public OrchestratorConfig position(long position) {
        return (OrchestratorConfig)super.position(position);
    }
    @Override public OrchestratorConfig getPointer(long i) {
        return new OrchestratorConfig((Pointer)this).offsetAddress(i);
    }

    public OrchestratorConfig(boolean isOrchestrator/*=true*/, @StdString BytePointer workerExecutablePath/*=""*/,
            @SharedPtr MpiComm orchLeaderComm/*=nullptr*/, boolean spawnProcesses/*=true*/) { super((Pointer)null); allocate(isOrchestrator, workerExecutablePath, orchLeaderComm, spawnProcesses); }
    private native void allocate(boolean isOrchestrator/*=true*/, @StdString BytePointer workerExecutablePath/*=""*/,
            @SharedPtr MpiComm orchLeaderComm/*=nullptr*/, boolean spawnProcesses/*=true*/);
    public OrchestratorConfig() { super((Pointer)null); allocate(); }
    private native void allocate();
    public OrchestratorConfig(boolean isOrchestrator/*=true*/, @StdString String workerExecutablePath/*=""*/,
            @SharedPtr MpiComm orchLeaderComm/*=nullptr*/, boolean spawnProcesses/*=true*/) { super((Pointer)null); allocate(isOrchestrator, workerExecutablePath, orchLeaderComm, spawnProcesses); }
    private native void allocate(boolean isOrchestrator/*=true*/, @StdString String workerExecutablePath/*=""*/,
            @SharedPtr MpiComm orchLeaderComm/*=nullptr*/, boolean spawnProcesses/*=true*/);

    public native boolean getIsOrchestrator();
    public native @StdString BytePointer getWorkerExecutablePath();
    public native @SharedPtr MpiComm getOrchLeaderComm();
    public native boolean getSpawnProcesses();

    public native void setIsOrchestrator(boolean isOrchestrator);
    public native void setWorkerExecutablePath(@StdString BytePointer workerExecutablePath);
    public native void setWorkerExecutablePath(@StdString String workerExecutablePath);
    public native void setOrchLeaderComm(@SharedPtr MpiComm orchLeaderComm);
    public native void setSpawnProcesses(boolean spawnProcesses);
}
