// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.kernels;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Kernels.*;


////////////////////////////////////////////////////////////////////////////////////////////////////

// The structure of parameters for the masked multihead attention kernel.
//
// We use the following terminology to describe the different dimensions.
//
// B:  Batch size (number of sequences),
// L:  Sequence length,
// D:  Hidden dimension,
// H:  Number of heads,
// Dh: Hidden dimension per head - Dh = D / H.

@Name("tensorrt_llm::kernels::Multihead_attention_params_base<float>") @Properties(inherit = tensorrt_llm.presets.KernelsConfig.class)
public class Multihead_attention_params_base extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public Multihead_attention_params_base() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Multihead_attention_params_base(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Multihead_attention_params_base(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public Multihead_attention_params_base position(long position) {
        return (Multihead_attention_params_base)super.position(position);
    }
    @Override public Multihead_attention_params_base getPointer(long i) {
        return new Multihead_attention_params_base((Pointer)this).offsetAddress(i);
    }


    // The output buffer. Dimensions B x D.
    public native Pointer out(); public native Multihead_attention_params_base out(Pointer setter);

    // The input Qs and the associated bias. Dimensions B x D and D, resp.
    public native @Const FloatPointer q(); public native Multihead_attention_params_base q(FloatPointer setter);
    public native @Const FloatPointer q_bias(); public native Multihead_attention_params_base q_bias(FloatPointer setter);
    // The input Ks and the associated bias. Dimensions B x D and D, resp.
    public native @Const FloatPointer k(); public native Multihead_attention_params_base k(FloatPointer setter);
    public native @Const FloatPointer k_bias(); public native Multihead_attention_params_base k_bias(FloatPointer setter);
    // The input Vs and the associated bias. Dimensions B x D and D, resp.
    public native @Const FloatPointer v(); public native Multihead_attention_params_base v(FloatPointer setter);
    public native @Const FloatPointer v_bias(); public native Multihead_attention_params_base v_bias(FloatPointer setter);

    // The indirections to use for cache when beam sampling.
    public native @Const IntPointer cache_indir(); public native Multihead_attention_params_base cache_indir(IntPointer setter);

    // scales
    public native @Const FloatPointer query_weight_output_scale(); public native Multihead_attention_params_base query_weight_output_scale(FloatPointer setter);
    public native @Const FloatPointer attention_qk_scale(); public native Multihead_attention_params_base attention_qk_scale(FloatPointer setter);
    public native @Const FloatPointer attention_output_weight_input_scale_inv(); public native Multihead_attention_params_base attention_output_weight_input_scale_inv(FloatPointer setter);

    // Stride to handle the case when KQV is a single buffer
    public native int stride(); public native Multihead_attention_params_base stride(int setter);

    // The batch size.
    public native int batch_size(); public native Multihead_attention_params_base batch_size(int setter);
    // The beam width
    public native int beam_width(); public native Multihead_attention_params_base beam_width(int setter);
    // The chunked attention size.
    public native int chunked_attention_size(); public native Multihead_attention_params_base chunked_attention_size(int setter);
    // The chunked attention size in log2.
    public native int chunked_attention_size_log2(); public native Multihead_attention_params_base chunked_attention_size_log2(int setter);
    // By default, max_attention_window_size == cyclic_attention_window_size
    // unless each layer has different cyclic kv cache length.
    // Max cache capacity (used to allocate KV cache)
    public native int max_attention_window_size(); public native Multihead_attention_params_base max_attention_window_size(int setter);
    // Cyclic kv cache capacity (used to get the cyclic kv cache position for new tokens)
    public native int cyclic_attention_window_size(); public native Multihead_attention_params_base cyclic_attention_window_size(int setter);
    // Length of the sink token in KV cache
    public native int sink_token_length(); public native Multihead_attention_params_base sink_token_length(int setter);
    // The number of heads (H).
    public native int num_heads(); public native Multihead_attention_params_base num_heads(int setter);
    // Controls MHA/MQA/GQA
    public native int num_kv_heads(); public native Multihead_attention_params_base num_kv_heads(int setter);
    // The hidden dimension per head (Dh).
    public native int hidden_size_per_head(); public native Multihead_attention_params_base hidden_size_per_head(int setter);
    // Rotary position embedding type
    public native PositionEmbeddingType position_embedding_type(); public native Multihead_attention_params_base position_embedding_type(PositionEmbeddingType setter);
    // The per-head latent space reserved for rotary embeddings.
    public native int rotary_embedding_dim(); public native Multihead_attention_params_base rotary_embedding_dim(int setter);
    public native float rotary_embedding_base(); public native Multihead_attention_params_base rotary_embedding_base(float setter);
    public native RotaryScalingType rotary_embedding_scale_type(); public native Multihead_attention_params_base rotary_embedding_scale_type(RotaryScalingType setter);
    public native float rotary_embedding_scale(); public native Multihead_attention_params_base rotary_embedding_scale(float setter);
    // The pre-computed rotary inv freq when building the engines (as constant weights).
    public native @Const FloatPointer rotary_embedding_inv_freq_cache(); public native Multihead_attention_params_base rotary_embedding_inv_freq_cache(FloatPointer setter);
    // The pre-computed cos/sin cache.
    public native @Cast("const float2*") FloatPointer rotary_embedding_cos_sin_cache(); public native Multihead_attention_params_base rotary_embedding_cos_sin_cache(@Cast("const float2*") FloatPointer setter);
    public native float rotary_embedding_short_m_scale(); public native Multihead_attention_params_base rotary_embedding_short_m_scale(float setter);
    public native float rotary_embedding_long_m_scale(); public native Multihead_attention_params_base rotary_embedding_long_m_scale(float setter);
    public native int rotary_embedding_max_positions(); public native Multihead_attention_params_base rotary_embedding_max_positions(int setter);
    public native int rotary_embedding_original_max_positions(); public native Multihead_attention_params_base rotary_embedding_original_max_positions(int setter);
    public native int rotary_cogvlm_vision_start(); public native Multihead_attention_params_base rotary_cogvlm_vision_start(int setter);
    public native int rotary_cogvlm_vision_length(); public native Multihead_attention_params_base rotary_cogvlm_vision_length(int setter);
    // Position shift for streamingllm
    public native boolean position_shift_enabled(); public native Multihead_attention_params_base position_shift_enabled(boolean setter);
    // The current timestep. TODO Check that do we only this param in cross attention?
    public native int timestep(); public native Multihead_attention_params_base timestep(int setter);
    // The current timestep of each sentences (support different timestep for different sentences)

    // The 1.f / sqrt(Dh). Computed on the host.
    public native float inv_sqrt_dh(); public native Multihead_attention_params_base inv_sqrt_dh(float setter);

    // The attention logit softcapping scale.
    public native float attn_logit_softcapping_scale(); public native Multihead_attention_params_base attn_logit_softcapping_scale(float setter);
    public native float attn_logit_softcapping_inverse_scale(); public native Multihead_attention_params_base attn_logit_softcapping_inverse_scale(float setter);

    // The attention mask [batch_size, attention_mask_stride (i.e. max_kv_seqlen)]
    public native @Const BoolPointer attention_mask(); public native Multihead_attention_params_base attention_mask(BoolPointer setter);
    public native int attention_mask_stride(); public native Multihead_attention_params_base attention_mask_stride(int setter);

    // The attention sinks [num_heads_q].
    public native @Const FloatPointer attention_sinks(); public native Multihead_attention_params_base attention_sinks(FloatPointer setter);

    // If relative position embedding is used
    public native @Const FloatPointer relative_attention_bias(); public native Multihead_attention_params_base relative_attention_bias(FloatPointer setter);
    public native int relative_attention_bias_stride(); public native Multihead_attention_params_base relative_attention_bias_stride(int setter);
    public native int max_distance(); public native Multihead_attention_params_base max_distance(int setter);

    // If logn scaling is used
    public native @Const FloatPointer logn_scaling_ptr(); public native Multihead_attention_params_base logn_scaling_ptr(FloatPointer setter);

    // block sparse config
    public native boolean block_sparse_attention(); public native Multihead_attention_params_base block_sparse_attention(boolean setter);
    public native @ByRef Pointer block_sparse_params(); public native Multihead_attention_params_base block_sparse_params(Pointer setter);

    // The slope per head of linear position bias to attention score (H).
    public native @Const FloatPointer linear_bias_slopes(); public native Multihead_attention_params_base linear_bias_slopes(FloatPointer setter);

    public native @Const FloatPointer ia3_key_weights(); public native Multihead_attention_params_base ia3_key_weights(FloatPointer setter);
    public native @Const FloatPointer ia3_value_weights(); public native Multihead_attention_params_base ia3_value_weights(FloatPointer setter);
    public native @Const IntPointer ia3_tasks(); public native Multihead_attention_params_base ia3_tasks(IntPointer setter);

    public native @Const FloatPointer qkv_scale_quant_orig(); public native Multihead_attention_params_base qkv_scale_quant_orig(FloatPointer setter);
    public native @Const FloatPointer attention_out_scale_orig_quant(); public native Multihead_attention_params_base attention_out_scale_orig_quant(FloatPointer setter);

    // 8 bits kv cache scales.
    public native @Const FloatPointer kv_scale_orig_quant(); public native Multihead_attention_params_base kv_scale_orig_quant(FloatPointer setter);
    public native @Const FloatPointer kv_scale_quant_orig(); public native Multihead_attention_params_base kv_scale_quant_orig(FloatPointer setter);

    public native boolean int8_kv_cache(); public native Multihead_attention_params_base int8_kv_cache(boolean setter);
    public native boolean fp8_kv_cache(); public native Multihead_attention_params_base fp8_kv_cache(boolean setter);

    // Multi-block setups
    public native boolean multi_block_mode(); public native Multihead_attention_params_base multi_block_mode(boolean setter);

    // Number of streaming processors on the device.
    // Tune block size to maximum occupancy.
    public native int multi_processor_count(); public native Multihead_attention_params_base multi_processor_count(int setter);

    public native int timesteps_per_block(); public native Multihead_attention_params_base timesteps_per_block(int setter);
    public native int seq_len_tile(); public native Multihead_attention_params_base seq_len_tile(int setter);

    public native int min_seq_len_tile(); public native Multihead_attention_params_base min_seq_len_tile(int setter);
    public native int max_seq_len_tile(); public native Multihead_attention_params_base max_seq_len_tile(int setter);
    // The partial output buffer. Dimensions max_seq_len_tile x B x D. (for each timestep only seq_len_tile x B x D is
    // needed)
    public native FloatPointer partial_out(); public native Multihead_attention_params_base partial_out(FloatPointer setter);
    // ThreadBlock sum. Dimensions max_seq_len_tile x 1. (for each timestep only seq_len_tile x 1 is needed)
    public native FloatPointer partial_sum(); public native Multihead_attention_params_base partial_sum(FloatPointer setter);
    // ThreadBlock max. Dimensions max_seq_len_tile x 1. (for each timestep only seq_len_tile x 1 is needed)
    public native FloatPointer partial_max(); public native Multihead_attention_params_base partial_max(FloatPointer setter);
    // threadblock counter to identify the complete of partial attention computations
    public native IntPointer block_counter(); public native Multihead_attention_params_base block_counter(IntPointer setter);

    public native @Const IntPointer memory_length_per_sample(); public native Multihead_attention_params_base memory_length_per_sample(IntPointer setter);
    public native @Const IntPointer mrope_position_deltas(); public native Multihead_attention_params_base mrope_position_deltas(IntPointer setter);
}
