// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.tensorrt_llm.*;
import org.bytedeco.tensorrt_llm.executor.*;
import org.bytedeco.tensorrt_llm.executor.kvcache.*;
import org.bytedeco.tensorrt_llm.runtime.*;
import org.bytedeco.tensorrt_llm.batch_manager.*;
import org.bytedeco.tensorrt_llm.batch_manager.kvcache.*;
import org.bytedeco.tensorrt_llm.common.*;
import org.bytedeco.tensorrt_llm.mpi.*;
import org.bytedeco.tensorrt_llm.nvinfer.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class ContextPhaseParams extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ContextPhaseParams(Pointer p) { super(p); }


    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @StdVector @Optional IntPointer draftTokens,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/) { super((Pointer)null); allocate(firstGenTokens, reqId, draftTokens, ctxDpRank, disaggInfoEndpoint); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @StdVector @Optional IntPointer draftTokens,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @StdVector @Optional IntPointer draftTokens) { super((Pointer)null); allocate(firstGenTokens, reqId, draftTokens); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @StdVector @Optional IntPointer draftTokens);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, Pointer state, @StdVector @Optional IntPointer draftTokens,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/) { super((Pointer)null); allocate(firstGenTokens, reqId, state, draftTokens, ctxDpRank, disaggInfoEndpoint); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, Pointer state, @StdVector @Optional IntPointer draftTokens,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, Pointer state, @StdVector @Optional IntPointer draftTokens) { super((Pointer)null); allocate(firstGenTokens, reqId, state, draftTokens); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, Pointer state, @StdVector @Optional IntPointer draftTokens);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector BytePointer serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens, ctxDpRank, disaggInfoEndpoint); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector BytePointer serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector BytePointer serializedState,
            @StdVector @Optional IntPointer draftTokens) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector BytePointer serializedState,
            @StdVector @Optional IntPointer draftTokens);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector ByteBuffer serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens, ctxDpRank, disaggInfoEndpoint); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector ByteBuffer serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector ByteBuffer serializedState,
            @StdVector @Optional IntPointer draftTokens) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector ByteBuffer serializedState,
            @StdVector @Optional IntPointer draftTokens);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector byte[] serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens, ctxDpRank, disaggInfoEndpoint); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector byte[] serializedState,
            @StdVector @Optional IntPointer draftTokens, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank/*=std::nullopt*/,
            @StdString @Optional BytePointer disaggInfoEndpoint/*=std::nullopt*/);
    public ContextPhaseParams(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector byte[] serializedState,
            @StdVector @Optional IntPointer draftTokens) { super((Pointer)null); allocate(firstGenTokens, reqId, serializedState, draftTokens); }
    private native void allocate(@StdVector @ByVal IntPointer firstGenTokens, @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId, @Cast("char*") @StdVector byte[] serializedState,
            @StdVector @Optional IntPointer draftTokens);

    public ContextPhaseParams(@Const @ByRef ContextPhaseParams arg0) { super((Pointer)null); allocate(arg0); }
    private native void allocate(@Const @ByRef ContextPhaseParams arg0);
    public native @ByRef @Name("operator =") ContextPhaseParams put(@Const @ByRef ContextPhaseParams arg0);

    public native @Cast("bool") @Name("operator ==") @NoException(true) boolean equals(@Const @ByRef ContextPhaseParams arg0);

    public native @Const @StdVector @ByRef @NoException(true) IntPointer getFirstGenTokens();
    public native @NoException(true) void setFirstGenTokens(@Const @StdVector @ByRef IntPointer firstGenTokens);
    public native @StdVector @Optional @NoException(true) IntPointer getDraftTokens();
    public native @NoException(true) void setDraftTokens(@StdVector @Optional IntPointer draftTokens);
    
    public native @Cast("tensorrt_llm::executor::ContextPhaseParams::RequestIdType") @NoException(true) long getReqId();
    public native @NoException(true) void setReqId(@Cast("const tensorrt_llm::executor::ContextPhaseParams::RequestIdType") long reqId);
    public native @NoException(true) Pointer getState();
    public native @NoException(true) Pointer releaseState();
    public native @Cast("char*") @StdVector @NoException(true) BytePointer getSerializedState();

    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional @NoException(true) IntPointer getCtxDpRank();
    public native @NoException(true) void setCtxDpRank(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer ctxDpRank);
    public native @StdString @Optional @NoException(true) BytePointer getDisaggInfoEndpoint();
    public native @NoException(true) void setDisaggInfoEndpoint(@StdString @Optional BytePointer disaggInfoEndpoint);
}
