// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.tensorrt_llm.*;
import org.bytedeco.tensorrt_llm.executor.*;
import org.bytedeco.tensorrt_llm.executor.kvcache.*;
import org.bytedeco.tensorrt_llm.runtime.*;
import org.bytedeco.tensorrt_llm.batch_manager.*;
import org.bytedeco.tensorrt_llm.batch_manager.kvcache.*;
import org.bytedeco.tensorrt_llm.common.*;
import org.bytedeco.tensorrt_llm.mpi.*;
import org.bytedeco.tensorrt_llm.nvinfer.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief An entry for a single block stored into the tree */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class KVCacheStoredBlockData extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KVCacheStoredBlockData(Pointer p) { super(p); }


    public KVCacheStoredBlockData(@Cast("tensorrt_llm::executor::IdType") long blockHash, @ByVal Pointer tokens,
            @Cast("tensorrt_llm::runtime::LoraTaskIdType*") @Optional LongPointer loraId, @Cast("tensorrt_llm::executor::SizeType32") int cacheLevel, @Cast("tensorrt_llm::executor::SizeType32") int priority,
            @StdVector MmKey mmKeys/*={}*/) { super((Pointer)null); allocate(blockHash, tokens, loraId, cacheLevel, priority, mmKeys); }
    private native void allocate(@Cast("tensorrt_llm::executor::IdType") long blockHash, @ByVal Pointer tokens,
            @Cast("tensorrt_llm::runtime::LoraTaskIdType*") @Optional LongPointer loraId, @Cast("tensorrt_llm::executor::SizeType32") int cacheLevel, @Cast("tensorrt_llm::executor::SizeType32") int priority,
            @StdVector MmKey mmKeys/*={}*/);
    public KVCacheStoredBlockData(@Cast("tensorrt_llm::executor::IdType") long blockHash, @ByVal Pointer tokens,
            @Cast("tensorrt_llm::runtime::LoraTaskIdType*") @Optional LongPointer loraId, @Cast("tensorrt_llm::executor::SizeType32") int cacheLevel, @Cast("tensorrt_llm::executor::SizeType32") int priority) { super((Pointer)null); allocate(blockHash, tokens, loraId, cacheLevel, priority); }
    private native void allocate(@Cast("tensorrt_llm::executor::IdType") long blockHash, @ByVal Pointer tokens,
            @Cast("tensorrt_llm::runtime::LoraTaskIdType*") @Optional LongPointer loraId, @Cast("tensorrt_llm::executor::SizeType32") int cacheLevel, @Cast("tensorrt_llm::executor::SizeType32") int priority);

    /** \brief The hash of the block */
    public native @Cast("tensorrt_llm::executor::IdType") long blockHash(); public native KVCacheStoredBlockData blockHash(long setter);
    /** \brief The unique tokens of the block */
    public native @ByRef Pointer tokens(); public native KVCacheStoredBlockData tokens(Pointer setter);
    /** \brief The Lora task id of the block */
    public native @Cast("tensorrt_llm::runtime::LoraTaskIdType*") @Optional LongPointer loraId(); public native KVCacheStoredBlockData loraId(LongPointer setter);
    /** \brief The cache level of the block */
    public native @Cast("tensorrt_llm::executor::SizeType32") int cacheLevel(); public native KVCacheStoredBlockData cacheLevel(int setter);
    /** \brief The priority of the block */
    public native @Cast("tensorrt_llm::executor::SizeType32") int priority(); public native KVCacheStoredBlockData priority(int setter);
    /** \brief The multimodal keys of the block */
    public native @StdVector MmKey mmKeys(); public native KVCacheStoredBlockData mmKeys(MmKey setter);
}
