// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.tensorrt_llm.*;
import org.bytedeco.tensorrt_llm.executor.*;
import org.bytedeco.tensorrt_llm.executor.kvcache.*;
import org.bytedeco.tensorrt_llm.runtime.*;
import org.bytedeco.tensorrt_llm.batch_manager.*;
import org.bytedeco.tensorrt_llm.batch_manager.kvcache.*;
import org.bytedeco.tensorrt_llm.common.*;
import org.bytedeco.tensorrt_llm.mpi.*;
import org.bytedeco.tensorrt_llm.nvinfer.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Configuration that controls the outputs of a Result */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class OutputConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public OutputConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public OutputConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public OutputConfig position(long position) {
        return (OutputConfig)super.position(position);
    }
    @Override public OutputConfig getPointer(long i) {
        return new OutputConfig((Pointer)this).offsetAddress(i);
    }

    public OutputConfig() { super((Pointer)null); allocate(); }
    private native void allocate();

    /** \brief Controls if Result should contain log probabilities. Default is false. */
    public native @Cast("bool") boolean returnLogProbs(); public native OutputConfig returnLogProbs(boolean setter);
    /** \brief Controls if Result should contain the context logits. Default is false. */
    public native @Cast("bool") boolean returnContextLogits(); public native OutputConfig returnContextLogits(boolean setter);
    /** \brief Controls if Result should contain the generation logits. Default is false. */
    public native @Cast("bool") boolean returnGenerationLogits(); public native OutputConfig returnGenerationLogits(boolean setter);
    /** \brief Controls if output tokens in Result should include the input tokens. Default is false. */
    public native @Cast("bool") boolean excludeInputFromOutput(); public native OutputConfig excludeInputFromOutput(boolean setter);
    /** \brief Controls if Result should contain encoder output hidden states (for encoder-only and encoder-decoder
     *  models). Default is false. */
    public native @Cast("bool") boolean returnEncoderOutput(); public native OutputConfig returnEncoderOutput(boolean setter);
    /** \brief Controls if Result should contain performance metrics */
    public native @Cast("bool") boolean returnPerfMetrics(); public native OutputConfig returnPerfMetrics(boolean setter);

    /** \brief The additional outputs to gather from the model. */
}
