// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.tensorrt_llm.*;
import org.bytedeco.tensorrt_llm.executor.*;
import org.bytedeco.tensorrt_llm.executor.kvcache.*;
import org.bytedeco.tensorrt_llm.runtime.*;
import org.bytedeco.tensorrt_llm.batch_manager.*;
import org.bytedeco.tensorrt_llm.batch_manager.kvcache.*;
import org.bytedeco.tensorrt_llm.common.*;
import org.bytedeco.tensorrt_llm.mpi.*;
import org.bytedeco.tensorrt_llm.nvinfer.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Sampling configuration */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class SamplingConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SamplingConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SamplingConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public SamplingConfig position(long position) {
        return (SamplingConfig)super.position(position);
    }
    @Override public SamplingConfig getPointer(long i) {
        return new SamplingConfig((Pointer)this).offsetAddress(i);
    }

    /** \brief Constructor for SamplingConfig
     *  See description of parameters below */
    public SamplingConfig(@Cast("tensorrt_llm::executor::SizeType32") int beamWidth/*=1*/, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer topK/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topP/*=std::nullopt*/, @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPMin/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::TokenIdType*") @Optional IntPointer topPResetIds/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPDecay/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::RandomSeedType*") @Optional LongPointer seed/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer temperature/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer minTokens/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer beamSearchDiversityRate/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer repetitionPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer presencePenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer frequencyPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer promptIgnoreLength/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer lengthPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer earlyStopping/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer noRepeatNgramSize/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer numReturnSequences/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer minP/*=std::nullopt*/,
            @StdVector @Optional IntPointer beamWidthArray/*=std::nullopt*/) { super((Pointer)null); allocate(beamWidth, topK, topP, topPMin, topPResetIds, topPDecay, seed, temperature, minTokens, beamSearchDiversityRate, repetitionPenalty, presencePenalty, frequencyPenalty, promptIgnoreLength, lengthPenalty, earlyStopping, noRepeatNgramSize, numReturnSequences, minP, beamWidthArray); }
    private native void allocate(@Cast("tensorrt_llm::executor::SizeType32") int beamWidth/*=1*/, @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer topK/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topP/*=std::nullopt*/, @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPMin/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::TokenIdType*") @Optional IntPointer topPResetIds/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPDecay/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::RandomSeedType*") @Optional LongPointer seed/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer temperature/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer minTokens/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer beamSearchDiversityRate/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer repetitionPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer presencePenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer frequencyPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer promptIgnoreLength/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer lengthPenalty/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer earlyStopping/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer noRepeatNgramSize/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer numReturnSequences/*=std::nullopt*/,
            @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer minP/*=std::nullopt*/,
            @StdVector @Optional IntPointer beamWidthArray/*=std::nullopt*/);
    public SamplingConfig() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef SamplingConfig other);

    public native @Cast("tensorrt_llm::executor::SizeType32") int getBeamWidth();
    public native @Cast("tensorrt_llm::executor::SizeType32") int getNumReturnBeams();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getTopK();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getTopP();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getTopPMin();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getTopPResetIds();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getTopPDecay();
    public native @Cast("tensorrt_llm::executor::RandomSeedType*") @Optional LongPointer getSeed();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getTemperature();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getMinTokens();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getBeamSearchDiversityRate();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getRepetitionPenalty();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getPresencePenalty();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getFrequencyPenalty();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getPromptIgnoreLength();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getLengthPenalty();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getEarlyStopping();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getNoRepeatNgramSize();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getNumReturnSequences();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getMinP();
    public native @StdVector @Optional IntPointer getBeamWidthArray();

    public native void setBeamWidth(@Cast("tensorrt_llm::executor::SizeType32") int beamWidth);
    public native void setTopK(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer topK);
    public native void setTopP(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topP);
    public native void setTopPMin(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPMin);
    public native void setTopPResetIds(@Cast("tensorrt_llm::executor::TokenIdType*") @Optional IntPointer topPResetIds);
    public native void setTopPDecay(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer topPDecay);
    public native void setSeed(@Cast("tensorrt_llm::executor::RandomSeedType*") @Optional LongPointer seed);
    public native void setTemperature(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer temperature);
    public native void setMinTokens(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer minTokens);
    public native void setBeamSearchDiversityRate(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer beamSearchDiversityRate);
    public native void setRepetitionPenalty(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer repetitionPenalty);
    public native void setPresencePenalty(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer presencePenalty);
    public native void setFrequencyPenalty(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer frequencyPenalty);
    public native void setPromptIgnoreLength(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer promptIgnoreLength);
    public native void setLengthPenalty(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer lengthPenalty);
    public native void setEarlyStopping(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer earlyStopping);
    public native void setNoRepeatNgramSize(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer noRepeatNgramSize);
    public native void setNumReturnSequences(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer numReturnSequences);
    public native void setMinP(@Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer minP);
    public native void setBeamWidthArray(@StdVector @Optional IntPointer beamWidthArray);
}
