// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class AllReduceBuffers extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AllReduceBuffers(Pointer p) { super(p); }


    public AllReduceBuffers(int maxBatchSize, int maxBeamWidth, int maxSequenceLength,
            int hiddenSize, @Const @ByRef BufferManager manager, @Const @ByRef WorldConfig worldConfig,
            boolean fakeBuffers/*=false*/) { super((Pointer)null); allocate(maxBatchSize, maxBeamWidth, maxSequenceLength, hiddenSize, manager, worldConfig, fakeBuffers); }
    private native void allocate(int maxBatchSize, int maxBeamWidth, int maxSequenceLength,
            int hiddenSize, @Const @ByRef BufferManager manager, @Const @ByRef WorldConfig worldConfig,
            boolean fakeBuffers/*=false*/);
    public AllReduceBuffers(int maxBatchSize, int maxBeamWidth, int maxSequenceLength,
            int hiddenSize, @Const @ByRef BufferManager manager, @Const @ByRef WorldConfig worldConfig) { super((Pointer)null); allocate(maxBatchSize, maxBeamWidth, maxSequenceLength, hiddenSize, manager, worldConfig); }
    private native void allocate(int maxBatchSize, int maxBeamWidth, int maxSequenceLength,
            int hiddenSize, @Const @ByRef BufferManager manager, @Const @ByRef WorldConfig worldConfig);

    public native @SharedPtr ITensor mAllReduceCommPtrs(); public native AllReduceBuffers mAllReduceCommPtrs(ITensor setter);
    public native @SharedPtr ITensor mFlagPtrs(); public native AllReduceBuffers mFlagPtrs(ITensor setter);
    public native @StdVector IpcMemory mIpcMemoryHandles(); public native AllReduceBuffers mIpcMemoryHandles(IpcMemory setter);
}
