// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class CudaVirtualMemoryManager extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CudaVirtualMemoryManager() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CudaVirtualMemoryManager(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CudaVirtualMemoryManager(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CudaVirtualMemoryManager position(long position) {
        return (CudaVirtualMemoryManager)super.position(position);
    }
    @Override public CudaVirtualMemoryManager getPointer(long i) {
        return new CudaVirtualMemoryManager((Pointer)this).offsetAddress(i);
    }

    /**
     * Add memory to be managed by this manager.
     * @param handle  Unique handle provided to reference this memory in {@code remove}.
     * @param tag     Tag the memory, so this memory can be targeted in {@code releaseWithTag} and {@code materializeWithTag}.
     * @param memory  The CUDAVirtualMemory object.
     *
     * The memory and internal state will remain valid if any exception is thrown.
     */
    public native void add(@Cast("uintptr_t") long handle, @StdString BytePointer tag, @ByRef(true) CUDAVirtualMemoryChunk memory);
    public native void add(@Cast("uintptr_t") long handle, @StdString String tag, @ByRef(true) CUDAVirtualMemoryChunk memory);

    /**
     * Creates and adds memory to be managed by this manager. The created memory is automatically materialized.
     * @param handle         Unique handle provided to reference this memory in {@code remove}.
     * @param tag            Tag the memory, so this memory can be targeted in {@code releaseWithTag} and
     * {@code materializeWithTag}.
     * @param creator        The creator for the memory.
     * @param configurators  The configurators for the memory.
     *
     * The internal state will remain valid if any exception is thrown.
     */
    public native void add(@Cast("uintptr_t") long handle, @StdString BytePointer tag, @UniquePtr CUDAVirtualMemoryChunk.Creator creator,
            @UniquePtr CUDAVirtualMemoryChunk.Configurator configurators);
    public native void add(@Cast("uintptr_t") long handle, @StdString String tag, @UniquePtr CUDAVirtualMemoryChunk.Creator creator,
            @UniquePtr CUDAVirtualMemoryChunk.Configurator configurators);

    /**
     * Remove the memory from the manager.
     * @param handle The handle provided to {@code add}.
     * @return The CUDAVirtualMemory object. If the handle is unknown, an empty CUDAVirtualMemory will be returned.
     */
    public native @ByVal @NoException(true) CUDAVirtualMemoryChunk remove(@Cast("uintptr_t") long handle);

    /**
     * Call release for CUDAVirtualMemoryChunk objects with a given tag.
     * @param tag the tag to select target memories.
     * @return Number of objects selected.
     *
     * This function will always call {@code CUDAVirtualMemoryChunk::release} on all selected objects.
     * The last exception thrown by {@code CUDAVirtualMemoryChunk::release} will be rethrown, and others will be logged.
     *
     * If any CUDAVirtualMemoryChunk threw an exception during {@code release}, it will be removed from the manager.
     * Call {@code retrieveBadHandles} to retrieve handles of all CUDAVirtualMemoryChunk that got removed due to exception.
     */
    public native long releaseWithTag(@StdString BytePointer tag);
    public native long releaseWithTag(@StdString String tag);

    /**
     * Call materialize for CUDAVirtualMemoryChunk objects with a given tag.
     * @param tag the tag to select target memories.
     * @return Number of objects selected.
     *
     * This function will stop at the first {@code CUDAVirtualMemoryChunk::materialize} that throws exception,
     * and attempt to roll back previous successful {@code materialize} by calling {@code release}.
     * The exception thrown by {@code CUDAVirtualMemoryChunk::materialize} will be rethrown,
     * and any exception thrown by {@code release} will be logged.
     *
     * If any CUDAVirtualMemoryChunk threw an exception during {@code materialize} or {@code release}, it will be removed from the
     * manager. Successfully roll backed CUDAVirtualMemoryChunk will not be removed.
     * Call {@code retrieveBadHandles} to retrieve handles of all CUDAVirtualMemoryChunk that got removed due to exception.
     */
    public native long materializeWithTag(@StdString BytePointer tag);
    public native long materializeWithTag(@StdString String tag);

    /**
     * Retrieve handles of all CUDAVirtualMemoryChunk that got removed due to exception and reset the list.
     * The returned list may not include all removed CUDAVirtualMemoryChunk handles if OOM happened.
     * This method is only for diagnostic purpose, and should not be called concurrently with other methods.
     * @return The handle list.
     */
    public native @Cast("uintptr_t*") @StdVector @NoException(true) SizeTPointer retrieveBadHandles();
}
