// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.executor.LookaheadDecodingConfig;


@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class LookaheadModule extends SpeculativeDecodingModule {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LookaheadModule(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public LookaheadModule(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public LookaheadModule position(long position) {
        return (LookaheadModule)super.position(position);
    }
    @Override public LookaheadModule getPointer(long i) {
        return new LookaheadModule((Pointer)this).offsetAddress(i);
    }

    public LookaheadModule(int maxDraftPathLen, int maxDecodingDraftTokens) { super((Pointer)null); allocate(maxDraftPathLen, maxDecodingDraftTokens); }
    @NoException(true) private native void allocate(int maxDraftPathLen, int maxDecodingDraftTokens);

    public LookaheadModule() { super((Pointer)null); allocate(); }
    @NoException(true) private native void allocate();

    public native void setExecutionConfig(@Const @ByRef LookaheadDecodingConfig config);

    public native @Const @ByRef LookaheadDecodingConfig getExecutionConfig();
}
