// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Namespace @Name("void") @Opaque @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class MPI_Comm extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public MPI_Comm() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MPI_Comm(Pointer p) { super(p); }
}
