// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

////////////////////////////////////////////////////////////////
// Functions for sharing file descriptors between processes
////////////////////////////////////////////////////////////////
@Namespace("tensorrt_llm::runtime") @Opaque @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class NcclIpcSocket extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public NcclIpcSocket() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public NcclIpcSocket(Pointer p) { super(p); }
}
