// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class TensorView extends ITensor {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TensorView(Pointer p) { super(p); }
    /** Downcast constructor. */
    public TensorView(ITensor pointer) { super((Pointer)null); allocate(pointer); }
    @Namespace private native @Name("dynamic_cast<tensorrt_llm::runtime::TensorView*>") void allocate(ITensor pointer);
    public BufferView asBufferView() { return asBufferView(this); }
    @Namespace public static native @Name("static_cast<tensorrt_llm::runtime::BufferView*>") BufferView asBufferView(TensorView pointer);
    public ITensor asITensor() { return asITensor(this); }
    @Namespace public static native @Name("static_cast<tensorrt_llm::runtime::ITensor*>") ITensor asITensor(TensorView pointer);


    public TensorView(@SharedPtr ITensor buffer, long offset, long size) { super((Pointer)null); allocate(buffer, offset, size); }
    private native void allocate(@SharedPtr ITensor buffer, long offset, long size);

    public TensorView(@SharedPtr IBuffer buffer, long offset, long size, @Const @ByRef Dims dims) { super((Pointer)null); allocate(buffer, offset, size, dims); }
    private native void allocate(@SharedPtr IBuffer buffer, long offset, long size, @Const @ByRef Dims dims);

    public native @Const @ByRef Dims getShape();

    public native void reshape(@Const @ByRef Dims dims);

    public native void resize(long newSize);

    public native void release();
}
