// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Layers.*;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class MedusaSetupParams extends DecodingSetupParams {
    static { Loader.load(); }
    /** Default native constructor. */
    public MedusaSetupParams() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MedusaSetupParams(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MedusaSetupParams(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MedusaSetupParams position(long position) {
        return (MedusaSetupParams)super.position(position);
    }
    @Override public MedusaSetupParams getPointer(long i) {
        return new MedusaSetupParams((Pointer)this).offsetAddress(i);
    }

    // Medusa params
    public native @StdVector IntPointer runtimeTopK(); public native MedusaSetupParams runtimeTopK(IntPointer setter);                   // [setupBatchSize]
    // [CPP-FIX] public native @StdVector std::vector<tensorrt_llm::runtime::SizeType32> runtimeHeadsTopK(); public native MedusaSetupParams runtimeHeadsTopK(std::vector<tensorrt_llm::runtime::SizeType32> setter); // [setupBatchSize, maxMedusaHeads]
}
