// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.plugins.SharedConstPtr;
import tensorrt_llm.runtime.BufferManager;
import tensorrt_llm.runtime.DecodingLayerWorkspace;

import static tensorrt_llm.global.Layers.*;


/** \brief Layer applies penalties to the logits. Supports:
 *  1. Temperature
 *  2. Repetition penalty
 *  3. Presence penalty
 *  4. Frequency penalty
 *  5. Min length penalty */
@Name("tensorrt_llm::layers::PenaltyLayer<float>") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class PenaltyLayer extends BaseLayer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public PenaltyLayer(Pointer p) { super(p); }

    public PenaltyLayer(@Const @ByRef Pointer mode, @Const @ByRef DecoderDomain decoderDomain,
            @SharedPtr BufferManager bufferManager) { super((Pointer)null); allocate(mode, decoderDomain, bufferManager); }
    private native void allocate(@Const @ByRef Pointer mode, @Const @ByRef DecoderDomain decoderDomain,
            @SharedPtr BufferManager bufferManager);

    public native void setup(int batchSize, int beamWidth, @ByVal @Cast("tensorrt_llm::layers::TensorConstPtr*") SharedConstPtr batchSlots,
            @SharedPtr BaseSetupParams setupParams,
            @SharedPtr DecodingLayerWorkspace workspace);

    /** \brief Modifies 'outputs->logits' in-place with -INF for banned words */
    public native void forwardAsync(@SharedPtr BaseDecodingOutputs outputs,
            @SharedPtr BaseDecodingInputs inputs,
            @SharedPtr DecodingLayerWorkspace workspace);

    /** @return workspace needed for this layer in bytes */
    public native @NoException(true) long getWorkspaceSize();
}
