// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Layers.*;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class SamplingInputs extends DecodingInputs {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SamplingInputs(Pointer p) { super(p); }

    public SamplingInputs(@ByVal @Cast("tensorrt_llm::layers::TensorConstPtr*") SharedConstPtr endIds, @ByVal @Cast("tensorrt_llm::layers::TensorConstPtr*") SharedConstPtr batchSlots, int step,
            int ite, int localBatchSize) { super((Pointer)null); allocate(endIds, batchSlots, step, ite, localBatchSize); }
    private native void allocate(@ByVal @Cast("tensorrt_llm::layers::TensorConstPtr*") SharedConstPtr endIds, @ByVal @Cast("tensorrt_llm::layers::TensorConstPtr*") SharedConstPtr batchSlots, int step,
            int ite, int localBatchSize);

    /** optional parameters */
    public native Pointer curandStates(); public native SamplingInputs curandStates(Pointer setter); // [localBatchSize]

    /** Flag to mark that logits tensor contains probabilities */
    public native boolean probsComputed(); public native SamplingInputs probsComputed(boolean setter);
}
