// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.pipelines;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DPipelines.*;


/** \class GlobalOptimizationOption
 * 
 *  \brief Option for GlobalOptimization. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DPipelinesConfig.class)
public class GlobalOptimizationOption extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GlobalOptimizationOption(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GlobalOptimizationOption(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public GlobalOptimizationOption position(long position) {
        return (GlobalOptimizationOption)super.position(position);
    }
    @Override public GlobalOptimizationOption getPointer(long i) {
        return new GlobalOptimizationOption((Pointer)this).offsetAddress(i);
    }

    /** \brief Parameterized Constructor.
     * 
     *  @param max_correspondence_distance Identifies which distance value is
     *  used for finding neighboring points when making information matrix.
     *  According to [Choi et al 2015], this distance is used for determining
     *  $\mu$, a line process weight.
     *  @param edge_prune_threshold According to
     *  [Choi et al 2015], line_process weight < edge_prune_threshold (0.25) is
     *  pruned.
     *  @param preference_loop_closure odometry vs loop-closure. [0,1]
     *  -> try to unchange odometry edges, [1) -> try to utilize loop-closure.
     *  Recommendation: 0.1 for RGBD Odometry, 2.0 for fragment registration.
     *  @param reference_node The pose of this node is unchanged after
     *  optimization. */
    public GlobalOptimizationOption(double max_correspondence_distance/*=0.075*/,
                                 double edge_prune_threshold/*=0.25*/,
                                 double preference_loop_closure/*=1.0*/,
                                 int reference_node/*=-1*/) { super((Pointer)null); allocate(max_correspondence_distance, edge_prune_threshold, preference_loop_closure, reference_node); }
    private native void allocate(double max_correspondence_distance/*=0.075*/,
                                 double edge_prune_threshold/*=0.25*/,
                                 double preference_loop_closure/*=1.0*/,
                                 int reference_node/*=-1*/);
    public GlobalOptimizationOption() { super((Pointer)null); allocate(); }
    private native void allocate();
    /** See reference list in GlobalOptimization.h
     *  Identifies which distance value is used for finding neighboring points
     *  when making information matrix. According to [Choi et al 2015],
     *  this distance is used for determining $\mu$, a line process weight. */
    public native double max_correspondence_distance_(); public native GlobalOptimizationOption max_correspondence_distance_(double setter);
    /** According to [Choi et al 2015],
     *  line_process weight < edge_prune_threshold_ (0.25) is pruned. */
    public native double edge_prune_threshold_(); public native GlobalOptimizationOption edge_prune_threshold_(double setter);
    /** Balancing parameter to decide which one is more reliable: odometry vs
     *  loop-closure. [0,1] -> try to unchange odometry edges, [1) -> try to
     *  utilize loop-closure. Recommendation: 0.1 for RGBD Odometry, 2.0 for
     *  fragment registration. */
    public native double preference_loop_closure_(); public native GlobalOptimizationOption preference_loop_closure_(double setter);
    /** The pose of this node is unchanged after optimization. */
    public native int reference_node_(); public native GlobalOptimizationOption reference_node_(int setter);
}
