// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.batch_manager.BufferManager;
import tensorrt_llm.batch_manager.CudaStream;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class DebugTensor extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DebugTensor(Pointer p) { super(p); }

    public DebugTensor(@Const @ByRef ITensor tensor, @Cast("const char*") BytePointer name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/) { super((Pointer)null); allocate(tensor, name, bufferManager, stream); }
    private native void allocate(@Const @ByRef ITensor tensor, @Cast("const char*") BytePointer name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/);
    public DebugTensor(@Const @ByRef ITensor tensor, @Cast("const char*") BytePointer name) { super((Pointer)null); allocate(tensor, name); }
    private native void allocate(@Const @ByRef ITensor tensor, @Cast("const char*") BytePointer name);
    public DebugTensor(@Const @ByRef ITensor tensor, String name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/) { super((Pointer)null); allocate(tensor, name, bufferManager, stream); }
    private native void allocate(@Const @ByRef ITensor tensor, String name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/);
    public DebugTensor(@Const @ByRef ITensor tensor, String name) { super((Pointer)null); allocate(tensor, name); }
    private native void allocate(@Const @ByRef ITensor tensor, String name);

    public DebugTensor(@ByVal SharedConstPtr tensor, @Cast("const char*") BytePointer name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/) { super((Pointer)null); allocate(tensor, name, bufferManager, stream); }
    private native void allocate(@ByVal SharedConstPtr tensor, @Cast("const char*") BytePointer name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/);
    public DebugTensor(@ByVal SharedConstPtr tensor, @Cast("const char*") BytePointer name) { super((Pointer)null); allocate(tensor, name); }
    private native void allocate(@ByVal SharedConstPtr tensor, @Cast("const char*") BytePointer name);
    public DebugTensor(@ByVal SharedConstPtr tensor, String name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/) { super((Pointer)null); allocate(tensor, name, bufferManager, stream); }
    private native void allocate(@ByVal SharedConstPtr tensor, String name,
            @SharedPtr BufferManager bufferManager/*=nullptr*/,
            @SharedPtr CudaStream stream/*=nullptr*/);
    public DebugTensor(@ByVal SharedConstPtr tensor, String name) { super((Pointer)null); allocate(tensor, name); }
    private native void allocate(@ByVal SharedConstPtr tensor, String name);

    // FIXED: public native @Cast("const uint8_t") byte u8(@Const @ByRef std::initializer_list<runtime::ITensor::DimType64> dims);

    public native @Cast("const uint8_t") byte u8(int idx);

    // FIXED: public native byte i8(@Const @ByRef std::initializer_list<runtime::ITensor::DimType64> dims);

    public native byte i8(int idx);

    // FIXED: public native int i32(@Const @ByRef std::initializer_list<runtime::ITensor::DimType64> dims);

    public native int i32(int idx);

    // FIXED: public native long i64(@Const @ByRef std::initializer_list<runtime::ITensor::DimType64> dims);

    public native long i64(int idx);

    // FIXED: public native float f(@Const @ByRef std::initializer_list<runtime::ITensor::DimType64> dims);

    public native float f(int idx);

    public native @ByVal ITensorPtr copyToHostOptional();

    public native @StdString BytePointer string();

    public native @StdString BytePointer tokens();

    public native @StdString BytePointer values();

    public native @StdString BytePointer shape();

    public native void print_tokens();

    public native void print_values();

    public native void print_shape();

    public native void randomize();

    public native void setZeros();

    public native void setOnes();
}
