// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief An CPU implementation of Lookahead with ITensor. */
@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class LookaheadAlgorithm extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LookaheadAlgorithm(Pointer p) { super(p); }


    /** \brief Currently the resource management is to be aligned with batch manager.
     *  @param w, n, g is the Jacobi window, n-gram level and guess set size respectively. */
    public LookaheadAlgorithm(
            int maxW, int maxN, int maxG, int id/*=0*/) { super((Pointer)null); allocate(maxW, maxN, maxG, id); }
    private native void allocate(
            int maxW, int maxN, int maxG, int id/*=0*/);
    public LookaheadAlgorithm(
            int maxW, int maxN, int maxG) { super((Pointer)null); allocate(maxW, maxN, maxG); }
    private native void allocate(
            int maxW, int maxN, int maxG);

    /** \brief setup per request, fill internal states from @param prompt. */
    public native void setup(@Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr prompt, int w, int n, int g,
            long seed);

    /** \brief accept the new generated tokens.
     *  LookaheadDecodingLayer need call once for the first token in generation phase. */
    public native void accept(@Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr generatedTokens);

    /** \brief combine lookahead and guess to prepare the tensors.
     *  input @param lastPositionIdPtr is position id of the last golden token, in a TensorPtr.
     *  input @param lastTokenPtr the last golden token for searching in the pool, in a TensorPtr.
     *  output @param draftTokens, positionIds includes the lookahead and the verification branch information.
     *  output @param draftLengthPtr holds the draft tokens length.
     *  output @param attentionMask holds the draft tokens dependency mask, and attentionMaskOffset is the index offset
     *  in attentionMask. */
    public native void prepare(@Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr draftTokens, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr positionIds, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr draftLengthPtr,
            @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr attentionMask, int attentionMaskOffset,
            @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr lastPositionIdPtr, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr lastTokenPtr);

    /** \brief update the internal states and generate accepted tokens from @param outputTokens.
     *  input @param sampledTokens is the all the tokens from the language model.
     *  input @param endToken is the end token for {@code verify} early quit.
     *  output @param acceptedTokens, acceptedOffsets in @param acceptedLength. */
    public native void update(@Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr acceptedTokens, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr acceptedOffsets, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr acceptedLength,
            @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr sampledTokens, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr endToken);

    /** generate attention @param mask from @param posIds. */
    public static native void posIdsToMask(@Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr mask, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorConstPtr*") @ByRef SharedConstPtr posIds);

    /** inplace encode the @param tokens and @param posIds according to attention @param masks, and record the offsets
     *  in @param encodeMap. */
    public static native int treeEncode(
            @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr tokens, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr posIds, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr masks, @Cast("const tensorrt_llm::layers::LookaheadAlgorithm::TensorPtr*") @ByRef SharedPtr encodeMap);
}
