// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.layers;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::layers") @NoOffset @Properties(inherit = tensorrt_llm.presets.LayersConfig.class)
public class SamplingSetupParams extends DecodingSetupParams {
    static { Loader.load(); }
    /** Default native constructor. */
    public SamplingSetupParams() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SamplingSetupParams(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SamplingSetupParams(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SamplingSetupParams position(long position) {
        return (SamplingSetupParams)super.position(position);
    }
    @Override public SamplingSetupParams getPointer(long i) {
        return new SamplingSetupParams((Pointer)this).offsetAddress(i);
    }

    // baseSamplingLayer
    public native @StdVector IntPointer runtimeTopK(); public native SamplingSetupParams runtimeTopK(IntPointer setter); // [1] or [setupBatchSize]
    public native @StdVector FloatPointer runtimeTopP(); public native SamplingSetupParams runtimeTopP(FloatPointer setter);               // [1] or [setupBatchSize]
    public native @StdVector FloatPointer runtimeMinP(); public native SamplingSetupParams runtimeMinP(FloatPointer setter);               // [1] or [setupBatchSize]

    // topPSamplingLayer
    public native @StdVector FloatPointer topPDecay(); public native SamplingSetupParams topPDecay(FloatPointer setter);                   // [setupBatchSize], between [0, 1]
    public native @StdVector FloatPointer topPMin(); public native SamplingSetupParams topPMin(FloatPointer setter);                     // [setupBatchSize], between [0, 1]
    public native @StdVector IntPointer topPResetIds(); public native SamplingSetupParams topPResetIds(IntPointer setter); // [setupBatchSize]
    public native @Optional BoolPointer normalizeLogProbs(); public native SamplingSetupParams normalizeLogProbs(BoolPointer setter);
}
