// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.runtime.KVCacheIndex;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager::kv_cache_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class BlockManager extends Pointer {
    // [CPP-FIX] broken decl removed:
    // static { Loader.load(); }
    // /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    // public BlockManager(Pointer p) { super(p); }
    // 
    // 
    // public BlockManager(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer numKvHeadsPerLayer, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sizePerHead,
    // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int tokensPerBlock, @Const @ByRef Pointer blocksPerWindow, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxNumSequences,
    // @SharedPtr Pointer stream, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxSequenceLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxBeamWidth,
    // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer maxAttentionWindowVec,
    // @Optional Pointer tempAttentionWindowInputs, int dtype,
    // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sinkBubbleLength, boolean onboardBlocks, @ByVal(nullValue = "CacheType::kSELF") int cacheType,
    // // [CPP-FIX] @Optional int secondaryOffloadMinPriority/*=std::nullopt*/,
    // // [CPP-FIX] @SharedPtr KVCacheEventManager eventManager/*=nullptr*/, boolean enablePartialReuse/*=true*/,
    // // [CPP-FIX] boolean copyOnPartialReuse/*=true*/,
    // // [CPP-FIX] @SharedPtr KvCacheConnectorManager kvCacheConnectorManager/*=nullptr*/,
    // // [CPP-FIX] @Optional BaseAgentConfig agentConfig/*=std::nullopt*/, boolean enableIndexerKCache/*=false*/,
    // // [CPP-FIX] @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int indexerKCacheQuantBlockSize/*=128*/, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int indexerKCacheIndexHeadDim/*=0*/) { super((Pointer)null); allocate(numKvHeadsPerLayer, sizePerHead, tokensPerBlock, blocksPerWindow, maxNumSequences, stream, maxSequenceLength, maxBeamWidth, maxAttentionWindowVec, tempAttentionWindowInputs, dtype, sinkBubbleLength, onboardBlocks, cacheType, secondaryOffloadMinPriority, eventManager, enablePartialReuse, copyOnPartialReuse, kvCacheConnectorManager, agentConfig, enableIndexerKCache, indexerKCacheQuantBlockSize, indexerKCacheIndexHeadDim); }
    // // [CPP-FIX] broken signature removed:
    // // private native void allocate(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer numKvHeadsPerLayer, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sizePerHead,
    // // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int tokensPerBlock, @Const @ByRef Pointer blocksPerWindow, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxNumSequences,
    // // @SharedPtr Pointer stream, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxSequenceLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxBeamWidth,
    // // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer maxAttentionWindowVec,
    // // @Optional Pointer tempAttentionWindowInputs, int dtype,
    // // @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sinkBubbleLength, boolean onboardBlocks, @ByVal(nullValue = "CacheType::kSELF") int cacheType,
    // // // [CPP-FIX] @Optional int secondaryOffloadMinPriority/*=std::nullopt*/,
    // // // [CPP-FIX] @SharedPtr KVCacheEventManager eventManager/*=nullptr*/, boolean enablePartialReuse/*=true*/,
    // // // [CPP-FIX] boolean copyOnPartialReuse/*=true*/,
    // // // [CPP-FIX] @SharedPtr KvCacheConnectorManager kvCacheConnectorManager/*=nullptr*/,
    // // // [CPP-FIX] @Optional BaseAgentConfig agentConfig/*=std::nullopt*/, boolean enableIndexerKCache/*=false*/,
    // // // [CPP-FIX] @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int indexerKCacheQuantBlockSize/*=128*/, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int indexerKCacheIndexHeadDim/*=0*/);
    public BlockManager(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer numKvHeadsPerLayer, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sizePerHead,
    @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int tokensPerBlock, @Const @ByRef Pointer blocksPerWindow, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxNumSequences,
    @SharedPtr Pointer stream, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxSequenceLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxBeamWidth,
    @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer maxAttentionWindowVec,
    @Optional Pointer tempAttentionWindowInputs, int dtype,
    @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sinkBubbleLength, boolean onboardBlocks) { super((Pointer)null); allocate(numKvHeadsPerLayer, sizePerHead, tokensPerBlock, blocksPerWindow, maxNumSequences, stream, maxSequenceLength, maxBeamWidth, maxAttentionWindowVec, tempAttentionWindowInputs, dtype, sinkBubbleLength, onboardBlocks); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer numKvHeadsPerLayer, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sizePerHead,
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int tokensPerBlock, @Const @ByRef Pointer blocksPerWindow, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxNumSequences,
    @SharedPtr Pointer stream, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxSequenceLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int maxBeamWidth,
    @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32*") @StdVector IntPointer maxAttentionWindowVec,
    @Optional Pointer tempAttentionWindowInputs, int dtype,
    @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int sinkBubbleLength, boolean onboardBlocks);

    public native boolean isEnableIndexerKCache();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getIndexerKCacheQuantBlockSize();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getIndexerKCacheIndexHeadDim();

    public native boolean isEnablePartialReuse();

    
    

    /** \brief Calculate the proportional share each window size receives of the total memory pool
     *  \details Example:       (uniqueWindowSizeToLayers={1024: [1], 4096: [0, 4, 5], 8192: [2, 3]})
     *           Would Return:  {1024: 0.0345, 4096: 0.4138, 8192: 0.5517} [sums to 1.0].
     *           See: TEST_F(KVCacheManagerTest, BlockManagerTestWindowSizeToShare).
     *  @return Map<windowSize, share> where share is a float between 0 and 1. Shares sum to 1.0. */
    // [CPP-FIX] public static native @ByVal std::map<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,float> calculateWindowSizeToShare();
    // [CPP-FIX] @Const @ByRef std::map<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,std::vector<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32> > uniqueWindowSizeToLayers,
    // [CPP-FIX] @Const @ByRef std::map<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32> cacheSizePerTokenPerWindowSize);

    public native void allocatePools(boolean useUvm);

    /** @return The number of tokens that were matched/prepopulated from cache (prepopulatedPromptLen) */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int addSequence(@ByRef GenerationRequest sequence, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int inputLength,
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int numContextBlocks, @ByRef LlmRequest llmRequest, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    /** \brief Assign blocks for a new sequence.
     *  @param sequence  The GenerationRequest to process.
     *  @param numContextBlocks  Number of context blocks to allocate.
     *  @param windowSize  Attention window size
     *  @param isShareLastContextBlock  If true, the last context block is shared among beams. */
    public native void addSequence(
            @ByRef GenerationRequest sequence, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int numContextBlocks, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize, boolean isShareLastContextBlock);

    public native void allocateBlock(@ByRef GenerationRequest sequence, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native void replaceSharedBlock(@ByRef GenerationRequest sequence, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int blockIdx);

    // [CPP-FIX] broken signature removed:
    // public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @Optional IntPointer releaseBlocks(
    // // [CPP-FIX] @ByRef GenerationRequest sequence, @ByVal(nullValue = "OptionalRef<const tensorrt_llm::batch_manager::LlmRequest>(std::nullopt)") OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest, boolean pinBlocks/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @Optional IntPointer releaseBlocks(
    @ByRef GenerationRequest sequence);

    // [CPP-FIX] broken signature removed:
    // public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer storeBlocksForReuse(
    // // [CPP-FIX] @ByRef GenerationRequest sequence, @ByVal(nullValue = "OptionalRef<const tensorrt_llm::batch_manager::LlmRequest>(std::nullopt)") OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest, boolean pinBlocks/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer storeBlocksForReuse(
    @ByRef GenerationRequest sequence);

    public native void schedulingReleaseBlocks(@ByVal long requestId);

    /** \brief Pin all blocks associated with a sequence across all window managers.
     *  @param sequence The generation request whose blocks should be pinned. */
    public native void pinBlocks(@ByRef GenerationRequest sequence);

    public native void unpinBlocksById(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer blockIds);

    public native void releaseLastBlock(@ByRef GenerationRequest sequence, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native void setOffsets(KVCacheIndex offsetsPtr, @Const @ByRef Pointer offsetsShape, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int beamIdx,
                                  @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int blockIdx, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    // WILL NOT WORK FOR VARIABLE WINDOW ATTENTION
    public native @Optional Pointer findNewContextBlock(
            @Const @ByRef Pointer uniqueTokens, @Const @ByRef LlmRequest llmRequest);

    /** \brief Count the number of full blocks that can be reused from the KV cache for a given request.
     *  \details WILL NOT WORK FOR VARIABLE WINDOW ATTENTION. */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int countReusableBlocks(
            @Const @ByRef Pointer uniqueTokens, @Const @ByRef LlmRequest llmRequest, boolean onlyAllocated/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int countReusableBlocks(
            @Const @ByRef Pointer uniqueTokens, @Const @ByRef LlmRequest llmRequest);

    /** \brief Bring block from primary to secondary memory for window size.
     *  \details Does nothing if block is already in primary memory. */
    // [CPP-FIX] broken signature removed:
    // public native void onboardBlock(@ByRef GenerationRequest sequence, @Const @ByRef Pointer offloadBlock, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize,
    // // [CPP-FIX] KvCacheTransferMode mode/*=executor::KvCacheTransferMode::DRAM*/, @StdString BytePointer directory/*=""*/);
    public native void onboardBlock(@ByRef GenerationRequest sequence, @Const @ByRef Pointer offloadBlock, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);
    // [CPP-FIX] broken signature removed:
    // public native void onboardBlock(@ByRef GenerationRequest sequence, @Const @ByRef Pointer offloadBlock, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);
    // // [CPP-FIX] KvCacheTransferMode mode/*=executor::KvCacheTransferMode::DRAM*/, @StdString String directory/*=""*/);

    /** \brief Bring block from primary to secondary memory for window size.
     *  \details Does nothing if block is already in secondary memory. */
    // [CPP-FIX] broken signature removed:
    // public native void offloadBlock(@Const @ByRef Pointer block, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize,
    // // [CPP-FIX] KvCacheTransferMode mode/*=executor::KvCacheTransferMode::DRAM*/, @StdString BytePointer directory/*=""*/);
    public native void offloadBlock(@Const @ByRef Pointer block, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);
    // [CPP-FIX] broken signature removed:
    // public native void offloadBlock(@Const @ByRef Pointer block, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);
    // // [CPP-FIX] KvCacheTransferMode mode/*=executor::KvCacheTransferMode::DRAM*/, @StdString String directory/*=""*/);

    // [CPP-FIX] public native @ByVal std::pair<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,std::vector<tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType> > storeBlocks();
    // [CPP-FIX] @StdVector Pointer blockKeys, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer blockIds,
    // [CPP-FIX] @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize, boolean pinBlocks/*=false*/);
    // [CPP-FIX] public native @ByVal std::pair<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,std::vector<tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType> > storeBlocks();
    // [CPP-FIX] @StdVector Pointer blockKeys, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer blockIds,
    // [CPP-FIX] @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native boolean verifyQueueIntegrity(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native void releasePools();

    public native void startScheduling();

    // [CPP-FIX] public native @ByVal std::map<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32> getNumFreeBlocksPerWindowSize();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumFreeBlocks();

    public native boolean schedulingHasFreeBlocks(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int numRequired, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumAllocTotalBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getFirstWindowSize();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getLastWindowSize();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumAllocNewBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumReusedBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumMissedBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumLayers();

    public native @ByVal int getCacheType();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getLayerPoolIdx(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int layerIdx);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getPoolLayerIdx(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int layerIdx);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") @NoException(true) int getTokensPerBlock();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getStreamDevice();

    // [CPP-FIX] public native @ByVal std::deque<executor::KVCacheEvent> getLatestEvents();
    // [CPP-FIX] @Optional Pointer timeout);

    public native void flushIterationEvents();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getPoolWindowSize(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getBlockSize(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumPools(
            boolean includeBlockScalePools/*=true*/, boolean includeIndexerKCachePools/*=true*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumPools();

    // [CPP-FIX] public native @Const @ByRef @NoException(true) std::map<tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32,tensorrt_llm::batch_manager::kv_cache_manager::WindowSizeMetadata> getWindowSizesMetadata();

    public native @ByVal @NoException(true) WindowSizeMetadata getWindowSizeMetadata(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native @NoException(true) boolean isVariableWindow();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getMaxBlockPerSeqWhenSingleWindowSize();

    public native @NoException(true) boolean isVariableGQA();

    public native @ByVal SharedPtr getPrimaryPool(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    public native @ByVal SharedPtr getSecondaryPool(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumAllocatedBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getMaxNumBlocks();

    public native @Const @ByRef Pointer getBlockById(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native @SharedPtr Pointer findBlocksInReuseTreeByBlockKey(
            @Const @ByRef Pointer blockKey, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int getNumPrimaryBlocks();

    public native boolean containsBlockScales(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    /** \brief Store context blocks */
    public native void storeContextBlocks(@ByRef GenerationRequest sequence, @Const @ByRef LlmRequest llmRequest);

    /** \brief Store newest block for reuse */
    // [CPP-FIX] public native void storeNewBlock(@ByRef GenerationRequest sequence, @ByVal OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest);

    /** \brief Sync internal streams used by transfer manager with buffer manager stream */
    public native void syncTransferManagerWithBufferManager();

    /** \brief Perform per-request bookkeeping */
    public native void refreshBlocks();

    public native @Const @ByRef BufferManager getBufferManager(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native @Const @ByRef KVCacheBlockPool getPool(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int poolIdx);

    /** \brief Update cache offsets for blocks initiated from sequence */
    public native void updateSequenceCacheBlockOffsets(@ByRef GenerationRequest seq, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    /** \brief Update cache offsets for block at index */
    public native void updateCacheBlockOffsetsAtIdx(@ByRef GenerationRequest seq, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int blockIdx);

    /** \brief Add/detach block(s) to/from the sequence if needed
     *  \details When we need a new block, we add it. For sliding window
     *  attention (SWA), when a block goes out-of-window (OOW), we detach it
     *  If this called in the first step of the generation phase, we may
     *  detach more than a single block since there may be more than one
     *  context block that goes OOW. */
    public native void adjustBlocksIfNeeded(@ByRef GenerationRequest sequence);

    /** \brief Return whether the sequence is already managed by the block manager */
    public native boolean isSequenceHeld(@ByVal long requestId);

    /** \brief Add a sequence to the managed sequences
     *  \details Take the sequence into account for the manager. Initialize
     *  sequence storage validity under all window sizes. */
    public native void holdSequence(@ByVal long requestId);

    /** \brief Remove a sequence from the managed sequences.
     *  \details Remove sequence from the managed sequences and remove sequence
     *  storage */
    public native void releaseSequence(@ByVal long requestId);

    /** \brief Return whether the sequence is still valid for store-for-reuse
     *  regarding the specific window size.
     *  \details Currently this utility function is only used under
     *  kvCacheManagerTest.cpp. Checking for store-for-reuse for each window
     *  size is done in an iterating fashion under BlockManager::releaseBlocks. */
    public native boolean isSequenceValidForStoreForReuse(@ByVal long requestId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::SizeType32") int windowSize);

    public native void resetReuseState();
}
