// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.executor.CommState;
import tensorrt_llm.executor.ConnectionManager;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class CacheSender extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CacheSender(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CacheSender(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public CacheSender position(long position) {
        return (CacheSender)super.position(position);
    }
    @Override public CacheSender getPointer(long i) {
        return new CacheSender((Pointer)this).offsetAddress(i);
    }

    /** \brief Constructor.
     *  @param manager The connection manager.
     *  @param selfIndex The sequential index of the current executor process.
     *  @param cacheLayer The cache layer bundling all cache states and formatters. */
    public CacheSender(ConnectionManager manager, @Cast("tensorrt_llm::batch_manager::SizeType32") int selfIndex, @ByVal CacheTransferLayer cacheLayer) { super((Pointer)null); allocate(manager, selfIndex, cacheLayer); }
    private native void allocate(ConnectionManager manager, @Cast("tensorrt_llm::batch_manager::SizeType32") int selfIndex, @ByVal CacheTransferLayer cacheLayer);

    public CacheSender() { super((Pointer)null); allocate(); }
    private native void allocate();

    /** \brief Asynchronously respond to the request and send data.
     *  @param llmRequest Request object. Its data should be ready when called, and the data for this request
     *  should remain valid until future synchronization.
     *  @return Once the data is fully sent, the future object will become valid. */
    // [CPP-FIX] public native @ByVal std::future<void> sendAsync(@ByRef LlmRequest llmRequest);

    /** \brief Return the internal communicator status.
     *  @return The communicator status. */
    public native @Const @ByRef CommState getCommState();

    /** \brief Reset the internal communicator status.
     *  @param commState The communicator status. */
    public native void setCommState(@ByVal CommState commState);

    /** \brief Synchronously send data.
     *  @param llmRequest The request object to which the data belongs. */
    public native void sendSync(@Const @ByRef LlmRequest llmRequest);

    /** \brief Receive request information.
     *  @param llmRequest The request object to which the data belongs. */
    public native @ByVal RequestInfo recvRequestInfo();

    /** \brief Cancel the request.
     *  @param requestId The ID used in the context phase of the current request.
     *  @return Whether the request is cancelled. */
    public native boolean cancelRequest(@Const @ByRef LlmRequest llmRequest);

    /** \brief Send ready signal.
     *  @param requestId The ID used in the context phase of the current request.
     *  @param isReady Whether the request is ready to be received. */
    public native void sendReadySignal(@ByVal long requestId, boolean isReady);

    /** \brief Destructor. */
}
