// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.executor.MpiComm;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class DecoderSlotAsyncSend extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DecoderSlotAsyncSend(Pointer p) { super(p); }


    public DecoderSlotAsyncSend(@Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr outputIds, @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr sequenceLengths, @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr cumLogProbs,
            @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr logProbs, boolean returnLogProbs, @Const @ByRef MpiComm commSession, int peer) { super((Pointer)null); allocate(outputIds, sequenceLengths, cumLogProbs, logProbs, returnLogProbs, commSession, peer); }
    private native void allocate(@Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr outputIds, @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr sequenceLengths, @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr cumLogProbs,
            @Cast("const tensorrt_llm::batch_manager::DecoderSlotAsyncSend::TensorPtr*") @ByRef SharedPtr logProbs, boolean returnLogProbs, @Const @ByRef MpiComm commSession, int peer);

    public DecoderSlotAsyncSend(
            @Const @ByRef SlotDecoderBuffers slotDecoderBuffers, boolean returnLogProbs, @Const @ByRef MpiComm commSession, int peer) { super((Pointer)null); allocate(slotDecoderBuffers, returnLogProbs, commSession, peer); }
    private native void allocate(
            @Const @ByRef SlotDecoderBuffers slotDecoderBuffers, boolean returnLogProbs, @Const @ByRef MpiComm commSession, int peer);

    public static native void recv(
            @Const @ByRef SlotDecoderBuffers slotDecoderBuffers, boolean returnLogProbs, @Const @ByRef MpiComm commSession, int peer);
}
