// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;


import tensorrt_llm.executor.Tensor;
import tensorrt_llm.global.Batchmanager;
import tensorrt_llm.presets.BatchmanagerConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager::kv_cache_manager_v2") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class IndexMapper extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public IndexMapper(Pointer p) { super(p); }

    public IndexMapper(@Cast("tensorrt_llm::batch_manager::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::SizeType32") int maxBeamWidth) { super((Pointer)null); allocate(maxBatchSize, maxBeamWidth); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::SizeType32") int maxBeamWidth);

    
    

    public native @Cast("tensorrt_llm::batch_manager::SizeType32") int addNewSequence(@ByVal long requestId);

    public native @Cast("tensorrt_llm::batch_manager::SizeType32") int getIndex(@ByVal long requestId);

    public native void removeSequence(@ByVal long requestId);

    public native @ByVal Tensor getCopyIndex(
            @StdVector long requestIds, @Cast("tensorrt_llm::batch_manager::SizeType32") int numContext, @Cast("tensorrt_llm::batch_manager::SizeType32") int beamWidth);
}
