// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


/** \brief The KV connector manager. This is passed into the C++ KV Cache Manager when adding sequences. */
@Namespace("tensorrt_llm::batch_manager::kv_connector") @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class KvCacheConnectorManager extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KvCacheConnectorManager(Pointer p) { super(p); }


    /** \brief Handle the getNumNewMatchedTokens call inside the C++ KV Cache Manager.
     *  @return The number of tokens that can be loaded from remote KV cache. */
    public native int getNumNewMatchedTokens(@Const @ByRef LlmRequest request, int numComputedTokens);
}
