// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class LogitsPostProcessor extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LogitsPostProcessor(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public LogitsPostProcessor(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public LogitsPostProcessor position(long position) {
        return (LogitsPostProcessor)super.position(position);
    }
    @Override public LogitsPostProcessor getPointer(long i) {
        return new LogitsPostProcessor((Pointer)this).offsetAddress(i);
    }


    @MemberGetter public static native int name();
    public static final int name = name();

    public LogitsPostProcessor() { super((Pointer)null); allocate(); }
    private native void allocate();

    // [CPP-FIX] broken signature removed:
    // public native @Name("operator ()") boolean apply(@ByRef DecoderInputBuffers inputBuffers, boolean replicateLogitsPostProcessor,
    // @Const @ByRef Pointer worldConfig, @SharedPtr Pointer stream,
    // // [CPP-FIX] @Optional Pointer logitsPostProcessorBatched/*=std::nullopt*/);
    public native @Name("operator ()") boolean apply(@ByRef DecoderInputBuffers inputBuffers, boolean replicateLogitsPostProcessor,
    @Const @ByRef Pointer worldConfig, @SharedPtr Pointer stream);
}
