// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;



import tensorrt_llm.executor.ExecutorConfig;
import tensorrt_llm.executor.DebugTensorsPerIteration;
import tensorrt_llm.executor.IterationStats;
import tensorrt_llm.executor.RequestStatsPerIteration;
import tensorrt_llm.global.Batchmanager;
import tensorrt_llm.presets.BatchmanagerConfig;
import tensorrt_llm.runtime.Dims;
import tensorrt_llm.runtime.ModelConfig;
import tensorrt_llm.runtime.WorldConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.runtime.RawEngine;

import static tensorrt_llm.global.Batchmanager.*;
 // namespace tensorrt_llm::runtime

@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class TrtEncoderModel extends TrtGptModel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TrtEncoderModel(Pointer p) { super(p); }


    public TrtEncoderModel(@Const @ByRef ModelConfig modelConfig, @Const @ByRef WorldConfig worldConfig,
                           @Const @ByRef RawEngine rawEngine, @SharedPtr Pointer logger,
    @Const @ByRef ExecutorConfig executorConfig) { super((Pointer)null); allocate(modelConfig, worldConfig, rawEngine, logger, executorConfig); }
    private native void allocate(@Const @ByRef ModelConfig modelConfig, @Const @ByRef WorldConfig worldConfig,
            @Const @ByRef RawEngine rawEngine, @SharedPtr Pointer logger,
    @Const @ByRef ExecutorConfig executorConfig);

    public native void terminateRequest(@SharedPtr LlmRequest llmRequest, boolean pause/*=false*/);
    public native void terminateRequest(@SharedPtr LlmRequest llmRequest);
    public native void terminateRequestSync(
            @SharedPtr LlmRequest llmRequest, @ByVal int finishReason);

    public native void forward(@SharedPtr LlmRequest activeRequests);

    public native void forwardSync();

    public native void forwardAsync(@Const @ByRef RequestList activeRequests);

    public native @Const @ByRef BufferManager getBufferManager();
    public native @ByVal CudaStreamPtr getRuntimeStreamPtr();

    public native @Const @ByRef ModelConfig getModelConfig();

    public native boolean getGatherGenerationLogits();

    public native @Const @ByRef WorldConfig getWorldConfig();

    public native @Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int getHiddenSize();

    public native @Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int getMaxInputLen();

    public native @Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int getNumMicroBatches();

    public native int getLogitDataType();

    public native int getTensorDataType(@StdString BytePointer name);
    
    public native @ByVal Dims getTensorShape(@StdString BytePointer name);
    

    public native @Cast("tensorrt_llm::batch_manager::TrtGptModelType") int getModelType();

    public native @ByVal @NoException(true) long getIterCounter();

    public native void updatePeftCache(@SharedPtr LlmRequest arg0);

    public native void getCurrentIterationStats(@ByRef IterationStats stats);
    public native void getCurrentRequestStats(@ByRef RequestStatsPerIteration stats);
    public native @ByVal DebugTensorsPerIteration getCurrentDebugTensors();

    public native void setLayerProfiler();
    public native @StdString BytePointer getLayerProfileInfo();

    public native void setLogitsPostProcessorBatched(@Optional Pointer logitsPostProcessorBatched);
    public native void setReplicateLogitsPostProcessor(boolean replicateLogitsPostProcessor);
    public native boolean getReplicateLogitsPostProcessor();

    public native void resetIterationStats();

    public native @Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int getMaxCapacityBatchSize(@Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::TrtEncoderModel::SizeType32") int outputLength);
}
