// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;



import tensorrt_llm.executor.ExecutorConfig;
import tensorrt_llm.global.Batchmanager;
import tensorrt_llm.presets.BatchmanagerConfig;
import tensorrt_llm.runtime.GptJsonConfig;
import tensorrt_llm.runtime.ModelConfig;
import tensorrt_llm.runtime.RawEngine;
import tensorrt_llm.runtime.WorldConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class TrtGptModelFactory extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public TrtGptModelFactory() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public TrtGptModelFactory(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TrtGptModelFactory(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public TrtGptModelFactory position(long position) {
        return (TrtGptModelFactory)super.position(position);
    }
    @Override public TrtGptModelFactory getPointer(long i) {
        return new TrtGptModelFactory((Pointer)this).offsetAddress(i);
    }


    public static native @SharedPtr TrtGptModel create(@Const @ByRef path trtEnginePath, @Cast("tensorrt_llm::batch_manager::TrtGptModelType") int modelType,
            @Const @ByRef ExecutorConfig executorConfig, boolean isLeaderInOrchMode);

    public static native @SharedPtr TrtGptModel create(@Const @ByRef path trtEnginePath, @Cast("tensorrt_llm::batch_manager::TrtGptModelType") int modelType,
            @Const @ByRef GptJsonConfig jsonConfig, @Const @ByRef WorldConfig worldConfig);
            @Const @ByRef ExecutorConfig executorConfig, boolean isLeaderInOrchMode);

    public static native @SharedPtr TrtGptModel create(@Const @ByRef RawEngine rawEngine,
            @Const @ByRef ModelConfig modelConfig, @Const @ByRef WorldConfig worldConfig, @Cast("tensorrt_llm::batch_manager::TrtGptModelType") int modelType);
            @Const @ByRef ExecutorConfig executorConfig, boolean isLeaderInOrchMode);
}
