// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


/** \class VoxelGrid
 * 
 *  \brief VoxelGrid is a collection of voxels which are aligned in grid. */
@Namespace("open3d::geometry") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class VoxelGrid extends Geometry3D {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public VoxelGrid(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public VoxelGrid(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public VoxelGrid position(long position) {
        return (VoxelGrid)super.position(position);
    }
    @Override public VoxelGrid getPointer(long i) {
        return new VoxelGrid((Pointer)this).offsetAddress(i);
    }

    /** \brief Default Constructor. */
    public VoxelGrid() { super((Pointer)null); allocate(); }
    private native void allocate();
    /** \brief Copy Constructor. */
    public VoxelGrid(@Const @ByRef VoxelGrid src_voxel_grid) { super((Pointer)null); allocate(src_voxel_grid); }
    private native void allocate(@Const @ByRef VoxelGrid src_voxel_grid);

    public native @ByRef VoxelGrid Clear();
    public native @Cast("bool") boolean IsEmpty();
    public native @ByVal Vector3d GetMinBound();
    public native @ByVal Vector3d GetMaxBound();
    public native @ByVal Vector3d GetCenter();

    /** \brief Returns the 3D coordinates of all corners of every voxel in
     *  the grid.
     *  @return A std::vector of Eigen::Vector3d representing the corners of all
     *  voxels. */
    public native @StdVector Vector3d GetAllVoxelCorners();
    /** Creates the axis-aligned bounding box around the object.
     *  Further details in AxisAlignedBoundingBox::AxisAlignedBoundingBox() */
    public native @ByVal AxisAlignedBoundingBox GetAxisAlignedBoundingBox();

    /** Creates an oriented bounding box that is identical to the
     *  axis-aligned bounding from GetAxisAlignedBoundingBox(). */
    public native @ByVal OrientedBoundingBox GetOrientedBoundingBox(
                @Cast("bool") boolean robust/*=false*/);
    public native @ByVal OrientedBoundingBox GetOrientedBoundingBox();

    /** Creates an oriented bounding box that is identical to the
     *  axis-aligned bounding from GetAxisAlignedBoundingBox(). */
    public native @ByVal OrientedBoundingBox GetMinimalOrientedBoundingBox(
                @Cast("bool") boolean robust/*=false*/);
    public native @ByVal OrientedBoundingBox GetMinimalOrientedBoundingBox();

    public native @ByRef VoxelGrid Transform(@Const @ByRef Matrix4d transformation);
    public native @ByRef VoxelGrid Translate(@Const @ByRef Vector3d translation,
                             @Cast("bool") boolean relative/*=true*/);
    public native @ByRef VoxelGrid Translate(@Const @ByRef Vector3d translation);
    public native @ByRef VoxelGrid Scale(double scale,
                         @Const @ByRef Vector3d center);
    public native @ByRef VoxelGrid Rotate(@Const @ByRef Matrix3d R,
                          @Const @ByRef Vector3d center);

    public native @ByRef @Name("operator +=") VoxelGrid addPut(@Const @ByRef VoxelGrid voxelgrid);
    public native @ByVal @Name("operator +") VoxelGrid add(@Const @ByRef VoxelGrid voxelgrid);

    /** Returns {@code true} if the voxel grid contains voxels. */
    public native @Cast("bool") boolean HasVoxels();
    /** Returns {@code true} if the voxel grid contains voxel colors. */
    public native @Cast("bool") boolean HasColors();
    /** Returns voxel index given query point. */
    public native @ByVal Vector3i GetVoxel(@Const @ByRef Vector3d point);

    /** Function that returns the 3d coordinates of the queried voxel center. */
    public native @ByVal Vector3d GetVoxelCenterCoordinate(@Const @ByRef Vector3i idx);

    /** Add a voxel with specified grid index and color. */
    public native void AddVoxel(@Const @ByRef Voxel voxel);

    /** Remove a voxel with specified grid index. */
    public native void RemoveVoxel(@Const @ByRef Vector3i idx);

    /** Return a vector of 3D coordinates that define the indexed voxel cube. */
    public native @StdVector Vector3d GetVoxelBoundingPoints(
                @Const @ByRef Vector3i index);

    /** Element-wise check if a query in the list is included in the VoxelGrid
     *  Queries are double precision and are mapped to the closest voxel. */
    
    ///
    public native @Cast("bool*") @StdVector BoolPointer CheckIfIncluded(
                @StdVector Vector3d queries);

    /** Remove all voxels from the VoxelGrid where none of the boundary points
     *  of the voxel projects to depth value that is smaller, or equal than the
     *  projected depth of the boundary point. If keep_voxels_outside_image is
     *  true then voxels are only carved if all boundary points project to a
     *  valid image location.
     * 
     *  @param depth_map Depth map (Image) used for VoxelGrid carving.
     *  @param camera_parameter Input Camera Parameters.
     *  @param keep_voxels_outside_image Project all voxels to a valid location. */
    
    ///
    public native @ByRef VoxelGrid CarveDepthMap(
                @Const @ByRef Image depth_map,
                @Const @ByRef PinholeCameraParameters camera_parameter,
                @Cast("bool") boolean keep_voxels_outside_image);

    /** Remove all voxels from the VoxelGrid where none of the boundary points
     *  of the voxel projects to a valid mask pixel (pixel value > 0). If
     *  keep_voxels_outside_image is true then voxels are only carved if
     *  all boundary points project to a valid image location.
     * 
     *  @param silhouette_mask Silhouette mask (Image) used for VoxelGrid
     *  carving.
     *  @param camera_parameter Input Camera Parameters.
     *  @param keep_voxels_outside_image Project all voxels to a valid location. */
    
    ///
    public native @ByRef VoxelGrid CarveSilhouette(
                @Const @ByRef Image silhouette_mask,
                @Const @ByRef PinholeCameraParameters camera_parameter,
                @Cast("bool") boolean keep_voxels_outside_image);

    /** Create VoxelGrid from Octree
     * 
     *  @param octree The input Octree. */
    
    ///
    public native void CreateFromOctree(@Const @ByRef Octree octree);

    /** Convert to Octree.
     * 
     *  @param max_depth Maximum depth of the octree. */
    
    ///
    public native @SharedPtr Octree ToOctree(long max_depth);

    /** Creates a voxel grid where every voxel is set (hence dense). This is a
     *  useful starting point for voxel carving.
     * 
     *  @param origin Coordinate center of the VoxelGrid
     *  @param color Voxel color for all voxels of the VoxelGrid.
     *  @param voxel_size Voxel size of of the VoxelGrid construction.
     *  @param width Spatial width extend of the VoxelGrid.
     *  @param height Spatial height extend of the VoxelGrid.
     *  @param depth Spatial depth extend of the VoxelGrid. */
    
    ///
    public static native @SharedPtr VoxelGrid CreateDense(@Const @ByRef Vector3d origin,
                                                      @Const @ByRef Vector3d color,
                                                      double voxel_size,
                                                      double width,
                                                      double height,
                                                      double depth);

    /** \enum VoxelPoolingMode
     * 
     *  \brief Possible ways of determining voxel color from PointCloud. */
    /** enum class open3d::geometry::VoxelGrid::VoxelPoolingMode */
    public static final int AVG = 0, MIN = 1, MAX = 2, SUM = 3;

    /** Creates a VoxelGrid from a given PointCloud. The color value of a given
     *  voxel is determined by the VoxelPoolingMode, e.g. by default the average
     *  color value of the points that fall into it (if the
     *  PointCloud has colors).
     *  The bounds of the created VoxelGrid are computed from the PointCloud.
     * 
     *  @param input The input PointCloud.
     *  @param voxel_size Voxel size of of the VoxelGrid construction.
     *  @param color_mode Mode of determining color for each voxel. */
    
    ///
    public static native @SharedPtr VoxelGrid CreateFromPointCloud(
                @Const @ByRef PointCloud input,
                double voxel_size,
                @Cast("open3d::geometry::VoxelGrid::VoxelPoolingMode") int color_mode/*=open3d::geometry::VoxelGrid::VoxelPoolingMode::AVG*/);
    public static native @SharedPtr VoxelGrid CreateFromPointCloud(
                @Const @ByRef PointCloud input,
                double voxel_size);

    /** Creates a VoxelGrid from a given PointCloud. The color value of a given
     *  voxel is determined by the VoxelPoolingMode, e.g. by default the average
     *  color value of the points that fall into it (if the
     *  PointCloud has colors).
     *  The bounds of the created VoxelGrid are defined by the given parameters.
     * 
     *  @param input The input PointCloud.
     *  @param voxel_size Voxel size of of the VoxelGrid construction.
     *  @param min_bound Minimum boundary point for the VoxelGrid to create.
     *  @param max_bound Maximum boundary point for the VoxelGrid to create.
     *  @param color_mode Mode of determining color for each voxel. */
    
    ///
    public static native @SharedPtr VoxelGrid CreateFromPointCloudWithinBounds(
                @Const @ByRef PointCloud input,
                double voxel_size,
                @Const @ByRef Vector3d min_bound,
                @Const @ByRef Vector3d max_bound,
                @Cast("open3d::geometry::VoxelGrid::VoxelPoolingMode") int color_mode/*=open3d::geometry::VoxelGrid::VoxelPoolingMode::AVG*/);
    public static native @SharedPtr VoxelGrid CreateFromPointCloudWithinBounds(
                @Const @ByRef PointCloud input,
                double voxel_size,
                @Const @ByRef Vector3d min_bound,
                @Const @ByRef Vector3d max_bound);

    /** Creates a VoxelGrid from a given TriangleMesh. No color information is
     *  converted. The bounds of the created VoxelGrid are computed from the
     *  TriangleMesh.
     * 
     *  @param input The input TriangleMesh.
     *  @param voxel_size Voxel size of of the VoxelGrid construction. */
    
    ///
    public static native @SharedPtr VoxelGrid CreateFromTriangleMesh(
                @Const @ByRef TriangleMesh input, double voxel_size);

    /** Creates a VoxelGrid from a given TriangleMesh. No color information is
     *  converted. The bounds of the created VoxelGrid are defined by the given
     *  parameters..
     * 
     *  @param input The input TriangleMesh.
     *  @param voxel_size Voxel size of of the VoxelGrid construction.
     *  @param min_bound Minimum boundary point for the VoxelGrid to create.
     *  @param max_bound Maximum boundary point for the VoxelGrid to create. */
    public static native @SharedPtr VoxelGrid CreateFromTriangleMeshWithinBounds(
                @Const @ByRef TriangleMesh input,
                double voxel_size,
                @Const @ByRef Vector3d min_bound,
                @Const @ByRef Vector3d max_bound);

    /** Returns List of {@code }Voxel{@code }: Voxels contained in voxel grid.
     *  Changes to the voxels returned from this method are not reflected in
     *  the voxel grid. */
    public native @StdVector Voxel GetVoxels();
    /** Size of the voxel. */
    public native double voxel_size_(); public native VoxelGrid voxel_size_(double setter);
    /** Coordinate of the origin point. */
    public native @ByRef Vector3d origin_(); public native VoxelGrid origin_(Vector3d setter);
    /** Orientation (rotation) of the voxel grid (world = origin_ +
     *  rotation_ * local) */
    public native @ByRef Matrix3d rotation_(); public native VoxelGrid rotation_(Matrix3d setter);
    /** Voxels contained in voxel grid */
}
