// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


/** \class KDTreeFlann
 * 
 *  \brief KDTree with FLANN for nearest neighbor search. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class KDTreeFlann extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KDTreeFlann(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public KDTreeFlann(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public KDTreeFlann position(long position) {
        return (KDTreeFlann)super.position(position);
    }
    @Override public KDTreeFlann getPointer(long i) {
        return new KDTreeFlann((Pointer)this).offsetAddress(i);
    }

    /** \brief Default Constructor. */
    
    ///
    public KDTreeFlann() { super((Pointer)null); allocate(); }
    private native void allocate();
    /** \brief Parameterized Constructor.
     * 
     *  @param data Provides set of data points for KDTree construction. */
    
    ///
    public KDTreeFlann(@Const @ByRef MatrixXd data) { super((Pointer)null); allocate(data); }
    private native void allocate(@Const @ByRef MatrixXd data);
    /** \brief Parameterized Constructor.
     * 
     *  @param geometry Provides geometry from which KDTree is constructed. */
    
    ///
    public KDTreeFlann(@Const @ByRef Geometry geometry) { super((Pointer)null); allocate(geometry); }
    private native void allocate(@Const @ByRef Geometry geometry);
    /** \brief Parameterized Constructor.
     * 
     *  @param feature Provides a set of features from which the KDTree is
     *  constructed. */
    public KDTreeFlann(@Const @ByRef Feature feature) { super((Pointer)null); allocate(feature); }
    private native void allocate(@Const @ByRef Feature feature);
    
    
    /** Sets the data for the KDTree from a matrix.
     * 
     *  @param data Data points for KDTree Construction. */
    
    ///
    public native @Cast("bool") boolean SetMatrixData(@Const @ByRef MatrixXd data);
    /** Sets the data for the KDTree from geometry.
     * 
     *  @param geometry Geometry for KDTree Construction. */
    
    ///
    public native @Cast("bool") boolean SetGeometry(@Const @ByRef Geometry geometry);
    /** Sets the data for the KDTree from the feature data.
     * 
     *  @param feature Set of features for KDTree construction. */
    public native @Cast("bool") boolean SetFeature(@Const @ByRef Feature feature);
    /** \brief Sets the KDTree data from the data provided by the other methods.
     * 
     *  Internal method that sets all the members of KDTree by data provided by
     *  features, geometry, etc. */
}
