// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


/** \class OctreeColorLeafNode
 * 
 *  \brief OctreeColorLeafNode class is an OctreeLeafNode containing color. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class OctreeColorLeafNode extends OctreeLeafNode {
    static { Loader.load(); }
    /** Default native constructor. */
    public OctreeColorLeafNode() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public OctreeColorLeafNode(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public OctreeColorLeafNode(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public OctreeColorLeafNode position(long position) {
        return (OctreeColorLeafNode)super.position(position);
    }
    @Override public OctreeColorLeafNode getPointer(long i) {
        return new OctreeColorLeafNode((Pointer)this).offsetAddress(i);
    }

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef OctreeLeafNode other);

    /** Clone this OctreeLeafNode. */
    
    ///
    public native @SharedPtr OctreeLeafNode Clone();

    /** \brief Get lambda function for initializing OctreeLeafNode.
     * 
     *  When the init function is called, an empty OctreeColorLeafNode is
     *  created. */

    /** \brief Get lambda function for updating OctreeLeafNode.
     * 
     *  When called, the update function updates the corresponding node with the
     *  input color.
     * 
     *  @param color Color of the node. */

    public native @Cast("bool") boolean ConvertToJsonValue(@ByRef Value value);
    public native @Cast("bool") boolean ConvertFromJsonValue(@Const @ByRef Value value);
    /** TODO: flexible data, with lambda function for handling node
     *  Color of the node. */
    public native @ByRef Vector3d color_(); public native OctreeColorLeafNode color_(Vector3d setter);
}
