// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


/** \class OctreeLeafNode
 * 
 *  \brief OctreeLeafNode base class. */
@Namespace("Pointer") @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class OctreeLeafNode extends OctreeNode {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public OctreeLeafNode(Pointer p) { super(p); }

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef OctreeLeafNode other);
    /** Clone this OctreeLeafNode. */
    public native @SharedPtr OctreeLeafNode Clone();
}
