// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


/** \class RGBDImage
 * 
 *  \brief RGBDImage is for a pair of registered color and depth images,
 * 
 *  viewed from the same view, of the same resolution.
 *  If you have other format, convert it first. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class RGBDImage extends Geometry2D {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RGBDImage(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public RGBDImage(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public RGBDImage position(long position) {
        return (RGBDImage)super.position(position);
    }
    @Override public RGBDImage getPointer(long i) {
        return new RGBDImage((Pointer)this).offsetAddress(i);
    }

    /** \brief Default Comnstructor. */
    
    ///
    public RGBDImage() { super((Pointer)null); allocate(); }
    private native void allocate();
    /** \brief Parameterized Constructor.
     * 
     *  @param color The color image.
     *  @param depth The depth image. */
    public RGBDImage(@Const @ByRef Image color, @Const @ByRef Image depth) { super((Pointer)null); allocate(color, depth); }
    private native void allocate(@Const @ByRef Image color, @Const @ByRef Image depth);

    public native @ByRef RGBDImage Clear();
    public native @Cast("bool") boolean IsEmpty();
    public native @ByVal Vector2d GetMinBound();
    
    ///
    public native @ByVal Vector2d GetMaxBound();

    /** \brief Factory function to create an RGBD Image from color and depth
     *  Images.
     * 
     *  @param color The color image.
     *  @param depth The depth image.
     *  @param depth_scale The ratio to scale depth values. The depth values
     *  will first be scaled and then truncated.
     *  @param depth_trunc Depth values larger than \p depth_trunc gets
     *  truncated to 0. The depth values will first be scaled and then
     *  truncated.
     *  @param convert_rgb_to_intensity - Whether to convert RGB
     *  image to intensity image. */
    
    ///
    public static native @SharedPtr RGBDImage CreateFromColorAndDepth(
                @Const @ByRef Image color,
                @Const @ByRef Image depth,
                double depth_scale/*=1000.0*/,
                double depth_trunc/*=3.0*/,
                @Cast("bool") boolean convert_rgb_to_intensity/*=true*/);
    public static native @SharedPtr RGBDImage CreateFromColorAndDepth(
                @Const @ByRef Image color,
                @Const @ByRef Image depth);

    /** \brief Factory function to create an RGBD Image from Redwood dataset.
     * 
     *  @param color The color image.
     *  @param depth The depth image.
     *  @param convert_rgb_to_intensity Whether to convert RGB image to
     *  intensity image. */
    
    ///
    public static native @SharedPtr RGBDImage CreateFromRedwoodFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth,
                @Cast("bool") boolean convert_rgb_to_intensity/*=true*/);
    public static native @SharedPtr RGBDImage CreateFromRedwoodFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth);

    /** \brief Factory function to create an RGBD Image from TUM dataset.
     * 
     *  @param color The color image.
     *  @param depth The depth image.
     *  @param convert_rgb_to_intensity Whether to convert RGB image to
     *  intensity image. */
    
    ///
    public static native @SharedPtr RGBDImage CreateFromTUMFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth,
                @Cast("bool") boolean convert_rgb_to_intensity/*=true*/);
    public static native @SharedPtr RGBDImage CreateFromTUMFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth);

    /** \brief Factory function to create an RGBD Image from SUN3D dataset.
     * 
     *  @param color The color image.
     *  @param depth The depth image.
     *  @param convert_rgb_to_intensity Whether to convert RGB image to
     *  intensity image. */
    
    ///
    public static native @SharedPtr RGBDImage CreateFromSUNFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth,
                @Cast("bool") boolean convert_rgb_to_intensity/*=true*/);
    public static native @SharedPtr RGBDImage CreateFromSUNFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth);

    /** \brief Factory function to create an RGBD Image from NYU dataset.
     * 
     *  @param color The color image.
     *  @param depth The depth image.
     *  @param convert_rgb_to_intensity Whether to convert RGB image to
     *  intensity image. */
    public static native @SharedPtr RGBDImage CreateFromNYUFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth,
                @Cast("bool") boolean convert_rgb_to_intensity/*=true*/);
    public static native @SharedPtr RGBDImage CreateFromNYUFormat(
                @Const @ByRef Image color,
                @Const @ByRef Image depth);

    public static native Pointer FilterPyramid(
                Pointer rgbd_image_pyramid, @Cast("Pointer") int type);

    public native Pointer CreatePyramid(
                long num_of_levels,
                @Cast("bool") boolean with_gaussian_filter_for_color/*=true*/,
                @Cast("bool") boolean with_gaussian_filter_for_depth/*=false*/);
    public native Pointer CreatePyramid(
                long num_of_levels);
    /** The color image. */
    public native @ByRef Image color_(); public native RGBDImage color_(Image setter);
    /** The depth image. */
    public native @ByRef Image depth_(); public native RGBDImage depth_(Image setter);
}
