// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.batch_manager;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::batch_manager::kv_cache_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchManagerConfig.class)
public class BlockIterator extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BlockIterator(Pointer p) { super(p); }


    public BlockIterator(@Const BlockRangeForWindow range, @Cast("size_t") long idx) { super((Pointer)null); allocate(range, idx); }
    private native void allocate(@Const BlockRangeForWindow range, @Cast("size_t") long idx);

    public native @ByVal @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockIterator::pointer*") @Name("operator ->") ITensor access();

    public native @ByVal @Cast("tensorrt_llm::batch_manager::kv_cache_manager::BlockIterator::reference*") @Name("operator *") ITensor multiply();

    public native @ByRef @Name("operator ++") BlockIterator increment();

    public native @ByVal @Name("operator ++") BlockIterator increment(int arg0);

    public native @ByVal @Name("operator tensorrt_llm::runtime::ITensor::SharedPtr") ITensor asITensor();

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef BlockIterator other);

    public native @Cast("bool") @Name("operator ==") boolean equals(@ByVal BlockRangeForWindow.Sentinel other);
}
