// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.batch_manager;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


// Use to track progress of context phase in dist-serving
@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchManagerConfig.class)
public class ContextProgress extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ContextProgress(Pointer p) { super(p); }

    public ContextProgress(int numLayers) { super((Pointer)null); allocate(numLayers); }
    private native void allocate(int numLayers);

    public native void recordEvent(int layerIdx, @Cast("cudaStream_t") Pointer stream);

    public native @Name("wait") void _wait(int layerIdx);

    public native int getNumLayers();

    public native @Cast("cudaEvent_t") Pointer getEvent(int layerIdx);
}
