// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.batch_manager;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


// Basic building block of a paged KV cache - a single
// cache block. This class just holds metadata, no pointers
// since it is reused across all layers.
@Namespace("tensorrt_llm::batch_manager::kv_cache_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchManagerConfig.class)
public class KVCacheBlock extends std::enable_shared_from_this<tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock> {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KVCacheBlock(Pointer p) { super(p); }


    @MemberGetter public static native @Cast("const tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int kCachedBlocksRootId();
    public static final int kCachedBlocksRootId = kCachedBlocksRootId();

    public KVCacheBlock(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId, @ByVal KVCacheIndex blockIdx) { super((Pointer)null); allocate(blockId, blockIdx); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId, @ByVal KVCacheIndex blockIdx);

    public native void startScheduling();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int getBlockId();

    public native @ByVal NextBlockMap getNextBlocks();

    /** \brief Wire this block into the shared lookup tree at the given node and window size.
     *  \details If the block is already attached to a different node, the old attachment is
     *  cleared first (its value slot is erased and cascade pruning fires upward). Then the
     *  block is stored as the value for \p windowSize in \p node.
     *  @param node    The lookup-tree node to attach to.
     *  @param windowSize Value key identifying this block's slot within the node. */
    public native void attachToLookupNode(@ByVal LookupNodePtr node, int windowSize);

    /** \brief Detach this block from the lookup tree.
     *  \details Clears the block's value slot in its current node and resets mLookupNode /
     *  mWindowSize to their null states. The Node cascade-prune logic then removes empty
     *  ancestor nodes automatically (bottom-up, stopping at the first non-empty ancestor). */
    public native void detachFromLookupNode();

    /** \brief Initialize a dummy root block's lookup-node link.
     *  \details Stores this block as the value for \p windowSize in \p rootNode so that
     *  direct children can retrieve the root block via getPrevBlock(). Must be called once
     *  after constructing the mCachedBlocksRoot block.
     *  @param rootNode  Root node of the per-manager UnifiedBlockTree.
     *  @param windowSize Window size associated with this WindowBlockManager. */
    public native void setAsRoot(@ByVal LookupNodePtr rootNode, int windowSize);

    public native @ByVal UnderlyingType getMemoryPoolBlockIndex();

    public native @Cast("bool") boolean isPrimary();

    public native void swapMemoryPoolBlockOffset(@SharedPtr KVCacheBlock otherBlock);

    public native void incRefCount();

    public native void decRefCount();

    public native void decSchedulingRefCount();

    public native @Cast("bool") boolean hasRefs();

    public native @Cast("bool") boolean hasSchedulingRefs();

    public native void setBlockKey(@Const @ByRef Pointer blockKey, @Cast("bool") boolean isFull);

    public native @ByVal Pointer getBlockKey();

    public native @Const @ByRef VecUniqueTokens getUniqueTokens();

    /** \brief Return the parent block in the lookup tree.
     *  \details Navigates via mLookupNode->getParentNode()->getValue(mWindowSize).
     *  Returns nullptr when:
     *    - The block is not attached to the tree (mLookupNode == nullptr), or
     *    - This block IS the root (mLookupNode->getParentNode() returns nullptr).
     *  For direct children of the root, returns the root block (mCachedBlocksRoot)
     *  NOTE: return type is by value (not const&) because the result is computed on the fly. */
    public native @SharedPtr KVCacheBlock getPrevBlock();

    public native @SharedPtr KVCacheBlock getPrevBlockInSeq();

    public native void setPrevBlockInSeq(@SharedPtr KVCacheBlock prevBlock);

    public native void addNextBlock(@Const @ByRef Pointer blockKey, @SharedPtr KVCacheBlock block);

    public native void removeNextBlock(@Const @ByRef Pointer blockKey);

    /** \brief True if this block has no physical GPU memory.
     *  \details Placeholder blocks exist in the sequence's block list to preserve prefix-chain
     *  structure in the lookup tree without consuming pool memory. Used by Mamba / linear-
     *  attention layers: only snapshot-position blocks are real; intervening positions are
     *  placeholders. Placeholder blocks are excluded from the eviction pool. */
    public native @Cast("bool") boolean isPlaceholder();

    /** \brief Create a placeholder KVCacheBlock with no GPU memory.
     *  \details The placeholder holds a block ID for sequence bookkeeping but mIsPlaceholder
     *  is set so that getCacheBlockIndices returns a nil index and the eviction pool ignores it. */
    public static native @SharedPtr KVCacheBlock createPlaceholder(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId);

    public native void detachDescendantsFromLookupTree();
    public native void freeBlockAndAllDescendants();

    /** \brief Find block matching blockKey. If allowPartial is true, the returned block may match only a prefix of
     *  blockKey.
     *  @return tuple of [partialMatch, numMatched, block], partialMatch is true if not all the tokens of the block were
     *  matched. */

    /** \brief Free block from previous block if present. */
    public native void freeLeafBlock();

    public native @Cast("bool") boolean isFull();

    public native @Cast("bool") boolean isShared();

    public native @Cast("bool") boolean isLeaf();

    public native void setPriority(@Cast("tensorrt_llm::executor::RetentionPriority") int priority);

    public native @Cast("tensorrt_llm::executor::RetentionPriority") int getPriority();

    public native void setDurationMs(@Cast("std::chrono::milliseconds*") @Optional LongPointer durationMs);

    public native @Cast("std::chrono::milliseconds*") @Optional LongPointer getDurationMs();

    public native void setExpirationTime(@Optional duration expirationTime);

    public native @Optional duration getExpirationTime();

    public native void setHash(@Cast("size_t") long hash);

    // set hash automatically from block key and previous block in sequence
    public native void setHash();

    public native @Cast("size_t") long getHash();

    public native @StdVector MmKey getExtraKeys();
}
