// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::batch_manager::kv_cache_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchManagerConfig.class)
public class KVCacheManager extends BaseKVCacheManager {
    static { Loader.load(); }
    /** Default native constructor. */
    public KVCacheManager() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public KVCacheManager(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KVCacheManager(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public KVCacheManager position(long position) {
        return (KVCacheManager)super.position(position);
    }
    @Override public KVCacheManager getPointer(long i) {
        return new KVCacheManager((Pointer)this).offsetAddress(i);
    }


    public native void allocatePools(@Cast("bool") boolean useUvm/*=false*/);
    public native void allocatePools();

    public native void releasePools();

    public native void startScheduling();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getTokensPerBlock();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getMaxNumBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getUsedNumBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getNumFreeBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getNumPools();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getNumAllocTotalBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getNumAllocNewBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") @NoException(true) int getNumReusedBlocks();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") @NoException(true) int getNumMissedBlocks();

    public native @ByVal KvCacheStats getKvCacheStats();

    public native @ByVal OffsetTableDimensions getOffsetTableDimensions();

    public native @Const @ByRef BlockManager getBlockManager();

    /** \brief  Function that computes the number of KV cache blocks needed to advance a request by one or two
     *  iterations
     *  @param req The request for which we need to calculate the number of needed KV cache blocks
     *  @return  The number of blocks */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getNeededBlocksOneStep(
            @Const @ByRef LlmRequest req, @Cast("bool") boolean twoStepsLookAhead, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    /** \brief  Function that computes the number of KV cache blocks remaining to advance a request to completion (i.e.
     *  for maxNewTokens); the allocated blocks are excluded
     *  @param req The request for which we need to calculate the number of needed KV cache blocks
     *  @return  The number of blocks */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getRemainingBlocksToCompletion(
            @Const @ByRef LlmRequest req, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    /** \brief Increase size for request with requestId. Allocate new KV cache block(s) if needed. */
    public native void addToken(@ByVal RequestIdType requestId);

    /** \brief Add new request to the KV cache manager.
     *  @param inputLength Input length for which KV cache need to be allocated.
     *  @param beamWidth Beam width for which KV cache need to be allocated.
     *  @param llmRequest Optional request to use for KV cache lookup.
     *  \details If llmRequest is supplied and KV cache reuse is enabled, try to recover KV cache blocks for
     *  inputLength - 1 tokens and populate prepopulatedPromptLen. */
    public native void addSequence(@ByVal RequestIdType requestId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int beamWidth,
            @ByVal(nullValue = "tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<tensorrt_llm::batch_manager::LlmRequest>(std::nullopt)") tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<tensorrt_llm::batch_manager::LlmRequest> llmRequest);
    public native void addSequence(@ByVal RequestIdType requestId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int beamWidth);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @Optional IntPointer removeSequence(@ByVal RequestIdType requestId,
            @ByVal(nullValue = "tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<const tensorrt_llm::batch_manager::LlmRequest>(std::nullopt)") tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest, @Cast("bool") boolean pinOnRelease/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @Optional IntPointer removeSequence(@ByVal RequestIdType requestId);

    public native void schedulingRemoveSequence(@ByVal RequestIdType requestId);

    public native @ByVal ITensor getBlockPoolPointers();

    public native @ByVal ITensor getLayerToPoolMapping();

    public native @ByVal ITensor getBlockScalePoolPointers();

    public native void getBlockOffsetsOfBatch(@ByRef ITensor output, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int firstBatchSlotIdx, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int batchSize,
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int beamWidth);

    /** @return maxBlockCount of all beams */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int copyBlockOffsets(
            @ByRef ITensor output, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int outputSlotOffset, @ByVal RequestIdType requestId);

    public native @Cast("bool") boolean isEnableBlockReuse();

    public native @Cast("bool") boolean isEnablePartialReuse();

    public native @Cast("bool") boolean isEnableIndexerKCache();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getIndexerKCacheIndexHeadDim();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getIndexerKCacheQuantBlockSize();

    public native void removeToken(@ByVal RequestIdType requestId);
    public native void rewindKVCache(@ByVal RequestIdType requestId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int rewindLengths);
    public native @ByRef GenerationRequest getSequence(@ByVal RequestIdType requestId);

    public native @Cast("bool") boolean isCrossKv();

    public native CacheType getCacheType();

    /** \brief Find first new block that must be allocated for context phase and return it's concatenated token vector.
     *  \details Only full blocks are considered. */
    public native @Optional Pointer findNewContextBlock(
            @Const @ByRef VecUniqueTokens uniqueTokens, @Const @ByRef LlmRequest llmRequest);

    /** \brief Count the number of full blocks that can be reused from the KV cache for a given request. */
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int countReusableBlocks(
            @Const @ByRef VecUniqueTokens uniqueTokens, @Const @ByRef LlmRequest llmRequest, @Cast("bool") boolean onlyAllocated/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int countReusableBlocks(
            @Const @ByRef VecUniqueTokens uniqueTokens, @Const @ByRef LlmRequest llmRequest);

    /** \brief Store full context blocks contributed by llmRequest.
     *  \details These blocks become reusable from next step. */
    public native void storeContextBlocks(@Const @ByRef LlmRequest llmRequest);

    /** \brief Store newest blocks for reuse */
    public native void storeNewBlock(@Const @ByRef LlmRequest llmRequest);

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer storeBlocksForReuse(
            @ByVal RequestIdType requestId, @ByVal tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest, @Cast("bool") boolean pinBlocks/*=false*/);
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer storeBlocksForReuse(
            @ByVal RequestIdType requestId, @ByVal tensorrt_llm::batch_manager::kv_cache_manager::OptionalRef<const tensorrt_llm::batch_manager::LlmRequest> llmRequest);

    public static native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getSinkBubbleLength(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int sinkTokenLen, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int tokensPerBlock);

    
    ///
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getMaxCapacityBatchSize(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int outputLength);

    /** \brief Calculates the number of kv-cache blocks that a sequence will require.
     * 
     *  @param inputLength The number of input tokens in the sequence.
     *  @param outputLength The number of output tokens in the sequence.
     *  @param sinkTokenLength The number of sink tokens configured.
     *  @param maxAttentionWindow The attention window size allowed by the model.
     *  @param beamWidth The number of beams to consider for the request.
     *  @param tokensPerBlock The number of tokens a single kv-cache block contains.,
     *  @return SizeType32 A number of blocks. */
    public static native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int calculateMaxBlockRequirements(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int outputLength,
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int sinkTokenLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int beamWidth, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int tokensPerBlock);

    public native void pinBlocks(@ByVal RequestIdType requestId);

    public native void unpinBlocksById(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntPointer blockIds);
    public native void unpinBlocksById(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector IntBuffer blockIds);
    public native void unpinBlocksById(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @StdVector int[] blockIds);

    public native @Cast("tensorrt_llm::executor::RetentionPriority") int getPriorityByBlockId(
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType") int blockId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    
    ///
    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheBlock::IdType*") @Optional IntPointer getLastBlockId(@ByVal RequestIdType requestId);

    /** \brief Calculates the number of kv-cache blocks that a sequence will require, for a single beam.
     * 
     *  @param sequenceLength The total length of the sequence (input and output).
     *  @param sinkTokenLength The number of sink tokens configured.
     *  @param windowSize The attention window size
     *  @param tokensPerBlock The number of tokens in a single kv-cache block.
     *  @return SizeType32 A number of blocks. */
    public static native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int calculateMaxBlockRequirementsPerBeam(
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int sequenceLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int sinkTokenLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int tokensPerBlock);

    public native @StdVector std::vector<tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32> getCacheBlockIds(
            @ByVal RequestIdType requestId, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    public native @StdVector std::vector<std::vector<tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32> > getBatchCacheBlockIds(
            @StdVector RequestIdType requestIds, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    public native @ByVal ITensor getUniquePrimaryPool();
    public native @ByVal ITensor getPrimaryPool(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int layer_idx);
    public native @ByVal ITensor getIndexerKCachePool();

    public native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int getPoolLayerIdx(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int layer_idx);

    public native void syncTransferManagerWithBufferManager();

    /** \brief Perform per-iteration bookkeeping */
    public native void refreshBlocks();

    public native void flushIterationEvents();

    public native @SharedPtr KVCacheBlock findBlocksInReuseTreeByBlockKey(
            @Const @ByRef Pointer blockKey, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int windowSize);

    
    ///
    public native void resetReuseState();

    /** \brief Finds the maximum attention window that can be used on a sequence, given some kv-cache block capacity.
     * 
     *  @param inputLength The number of input tokens in the sequence.
     *  @param outputLength The number of output tokens in the sequence.
     *  @param sinkTokenLength The number of sink tokens.
     *  @param blockCapacity The number of kv-cache blocks available.
     *  @param beamWidth The number of beams to consider.
     *  @param tokensPerBlock The number of tokens per kv-cache block.
     *  @return SizeType32 A maximum attention window in number of tokens. */
    public static native @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int calculateMaxAttentionWindow(@Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int inputLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int outputLength,
            @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int sinkTokenLength, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int blockCapacity, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int beamWidth, @Cast("tensorrt_llm::batch_manager::kv_cache_manager::KVCacheManager::SizeType32") int tokensPerBlock);
}
