// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.batch_manager;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchManagerConfig.class)
public class TransformerBuffers extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TransformerBuffers(Pointer p) { super(p); }


    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor pastKeyValueLengths(); public native TransformerBuffers pastKeyValueLengths(ITensor setter); // Host tensor
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor positionIds(); public native TransformerBuffers positionIds(ITensor setter);

    // max kv cache lengths.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor maxAttentionWindows(); public native TransformerBuffers maxAttentionWindows(ITensor setter);
    // sink token lengths.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor sinkTokenLengths(); public native TransformerBuffers sinkTokenLengths(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor cacheIndirection(); public native TransformerBuffers cacheIndirection(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor kvCacheBlockOffsetsHost(); public native TransformerBuffers kvCacheBlockOffsetsHost(ITensor setter);   // [numPools, maxBatch * maxBeamWidth, 2, maxBlocksPerSeq]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor kvCacheBlockOffsetsDevice(); public native TransformerBuffers kvCacheBlockOffsetsDevice(ITensor setter); // [numPools, maxBatch * maxBeamWidth, 2, maxBlocksPerSeq]
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor contextProgressHost(); public native TransformerBuffers contextProgressHost(ITensor setter);

    // Cross attention buffers
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossKvCacheBlockPoolPointers(); public native TransformerBuffers crossKvCacheBlockPoolPointers(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossKvCacheBlockPoolMapping(); public native TransformerBuffers crossKvCacheBlockPoolMapping(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossKvCacheBlockOffsetsHost(); public native TransformerBuffers crossKvCacheBlockOffsetsHost(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossKvCacheBlockOffsetsDevice(); public native TransformerBuffers crossKvCacheBlockOffsetsDevice(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionMaskCopySrcOffsets(); public native TransformerBuffers crossAttentionMaskCopySrcOffsets(ITensor setter); // [maxNumRequest] pinned memory.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionMaskCopyDstOffsets(); public native TransformerBuffers crossAttentionMaskCopyDstOffsets(ITensor setter); // [maxNumRequest] pinned memory.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionMaskCopySizes(); public native TransformerBuffers crossAttentionMaskCopySizes(ITensor setter);      // [maxNumRequest] pinned memory.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionMaskDevice(); public native TransformerBuffers crossAttentionMaskDevice(ITensor setter);         // [maxNumTokens, maxEncoderOutputLen]
    // This is created to allow mixed memory types of crossAttentionMask (i.e. CPU and GPU).
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionMaskPinnedHost(); public native TransformerBuffers crossAttentionMaskPinnedHost(ITensor setter); // [maxNumTokens, maxEncoderOutputLen]
    // See more details in tensorrt_llm/kernels/contextFusedMultiHeadAttention/fmhaPackedMask.cu.
    // The attention packed mask for FMHA where each bit represents one mask.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionPackedMaskDevice(); public native TransformerBuffers crossAttentionPackedMaskDevice(ITensor setter); // [maxBatchSize, maxInputLengthInBatch, roundUp(maxEncoderOutputLen, 32)]
    // The number of cumulative Q sequence lengths in the mask input, which is used to get mask offsets for different
    // requests.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionCuQSeqLensDevice(); public native TransformerBuffers crossAttentionCuQSeqLensDevice(ITensor setter); // [maxBatchSize + 1]
    // The number of cumulative Q sequence lengths in the packed mask, which is used to get mask offsets for different
    // requests.
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor crossAttentionPackedMaskCuMaskRowsDevice(); public native TransformerBuffers crossAttentionPackedMaskCuMaskRowsDevice(ITensor setter); // [maxBatchSize + 1]

    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor cacheIndirBatchedCopySrcOffsets(); public native TransformerBuffers cacheIndirBatchedCopySrcOffsets(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor cacheIndirBatchedCopyDstOffsets(); public native TransformerBuffers cacheIndirBatchedCopyDstOffsets(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor cacheIndirBatchedCopySizes(); public native TransformerBuffers cacheIndirBatchedCopySizes(ITensor setter);

    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor fillValuesAlt(); public native TransformerBuffers fillValuesAlt(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor fillValuesAltDevice(); public native TransformerBuffers fillValuesAltDevice(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor seqSlotsAlt(); public native TransformerBuffers seqSlotsAlt(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor seqSlotsAltDevice(); public native TransformerBuffers seqSlotsAltDevice(ITensor setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") ITensor skipCrossAttnBlocks(); public native TransformerBuffers skipCrossAttnBlocks(ITensor setter);

    public native @SharedPtr MulticastTensor gemmAllReduceOutput(); public native TransformerBuffers gemmAllReduceOutput(MulticastTensor setter);

    public TransformerBuffers(@Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBeamWidth,
            @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32*") @StdVector IntPointer maxAttentionWindowVec, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxAttentionWindow, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int sinkTokenLen,
            @Const @ByRef TllmRuntime runtime, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig) { super((Pointer)null); allocate(maxBatchSize, maxBeamWidth, maxAttentionWindowVec, maxAttentionWindow, sinkTokenLen, runtime, modelConfig, worldConfig); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBeamWidth,
            @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32*") @StdVector IntPointer maxAttentionWindowVec, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxAttentionWindow, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int sinkTokenLen,
            @Const @ByRef TllmRuntime runtime, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig);

    public native void reshape(@Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int numSequences, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int numInputTokens);

    public native void reshapeKvTensors(@Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBeamWidth, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxBlocksPerSeq,
            CacheType kvCacheType, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int numPools, @Const @ByRef BufferManager manager);

    public native void getBuffers(@Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorMap*") @ByRef runtime::StringPtrMap<tensorrt_llm::runtime::ITensor> inputBuffers, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::TensorMap*") @ByRef runtime::StringPtrMap<tensorrt_llm::runtime::ITensor> outputBuffers, @Const @ByRef ModelConfig modelConfig);

    public native void copyPositionIds(@Const @ByRef TllmRuntime runtime, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32*") @StdVector IntPointer positionIdsHost,
            @Cast("bool") boolean isChatGlm, @Cast("const tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") @ByRef ITensor decoderPositionIds);

    public native void copyKvBlockOffsets(@SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest genRequests,
            @Const BaseKVCacheManager kvCacheManager,
            @Const BaseKVCacheManager crossKvCacheManager, @Const @ByRef BufferManager manager);

    // Copy CacheIndirection from `decoderCacheIndirectionOutput` to `this->cacheIndirection`
    public native void copyCacheIndirection(@SharedPtr LlmRequest genRequests, @Cast("const tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") @ByRef ITensor decoderCacheIndirectionOutput,
            @Cast("const tensorrt_llm::runtime::CudaStream*") @ByRef Pointer stream);

    public native void copyCrossAttentionMasks(@SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest genRequests,
            @Cast("const tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") @ByRef ITensor decoderContextLengthsDevice, @Cast("const tensorrt_llm::batch_manager::TransformerBuffers::TensorPtr*") @ByRef ITensor encoderInputLengths,
            @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxDecoderContextLength, @Cast("tensorrt_llm::batch_manager::TransformerBuffers::SizeType32") int maxEncoderInputLengthInBatch,
            @Const @ByRef TllmRuntime runtime);

    public native void copySkipCrossAttnBlocks(@Cast("const bool") boolean _skipCrossAttnBlocks, @Const @ByRef TllmRuntime runtime);
}
