// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** AdvancedIndexer exposes an interface similar to Indexer, with support for
 *  advanced indexing.
 * 
 *  In particular, AdvancedIndexer contains an Indexer instance to iterate src,
 *  dst and index tensors. AdvancedIndexer also contains various properties for
 *  advanced indexing.
 * 
 *  To construct AdvancedIndexer, one must use the tensors and index tensors
 *  preprocessed by AdvancedIndexPreprocessor. */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class AdvancedIndexer extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AdvancedIndexer(Pointer p) { super(p); }

    /** enum class Pointer */
    public static final int SET = 0, GET = 1;

    public AdvancedIndexer(@Const @ByRef Tensor src,
                        @Const @ByRef Tensor dst,
                        @StdVector Tensor index_tensors,
                        @Const @ByRef SizeVector indexed_shape,
                        @Const @ByRef SizeVector indexed_strides,
                        @Cast("Pointer") int mode) { super((Pointer)null); allocate(src, dst, index_tensors, indexed_shape, indexed_strides, mode); }
    private native void allocate(@Const @ByRef Tensor src,
                        @Const @ByRef Tensor dst,
                        @StdVector Tensor index_tensors,
                        @Const @ByRef SizeVector indexed_shape,
                        @Const @ByRef SizeVector indexed_strides,
                        @Cast("Pointer") int mode);

    public native OPEN3D_HOST_DEVICE GetInputPtr(@Cast("int64_t") long workload_idx);

    public native OPEN3D_HOST_DEVICE GetOutputPtr(@Cast("int64_t") long workload_idx);

    public native @ByVal OPEN3D_HOST_DEVICE GetIndexedOffset(@Cast("int64_t") long workload_idx);

    public native @Cast("int64_t") long NumWorkloads();
}
