// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** CUDAState is a lazy-evaluated singleton class that initializes and stores
 *  the states of CUDA devices.
 * 
 *  Currently it stores the peer-to-peer availability.
 * 
 *  In the future, it can also be used to store
 *  - Device allocators
 *  - cuBLAS and cuSPARSE handles
 *  - Scratch space sizes
 *  - ...
 * 
 *  Ref:
 *  https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCGeneral.cpp */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class CUDAState extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CUDAState(Pointer p) { super(p); }

    public static native @ByRef CUDAState GetInstance();

    
    

    /** Returns true if peer-to-peer is available from the CUDA device-ID
     *  \p src_id to \p tar_id. */
    public native @Cast("bool") boolean IsP2PEnabled(int src_id, int tar_id);

    /** Returns true if peer-to-peer is available from the CUDA device
     *  \p src to \p tar. */
    public native @Cast("bool") boolean IsP2PEnabled(@Const @ByRef Device src, @Const @ByRef Device tar);

    /** Disables P2P device transfer between all devices, in order to run
     *  non-P2P tests on a P2P-capable machine. */
    public native void ForceDisableP2PForTesting();
}
