// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class DemoFeatureMatchingPointClouds
 *  \brief Data class for {@code DemoFeatureMatchingPointClouds} contains 2
 *  point cloud fragments and their respective FPFH features and L32D features.
 *  This data is used in Open3D for point cloud feature matching demo.
 *  \copyright Creative Commons 3.0 (CC BY 3.0). */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class DemoFeatureMatchingPointClouds extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DemoFeatureMatchingPointClouds(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public DemoFeatureMatchingPointClouds(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public DemoFeatureMatchingPointClouds position(long position) {
        return (DemoFeatureMatchingPointClouds)super.position(position);
    }
    @Override public DemoFeatureMatchingPointClouds getPointer(long i) {
        return new DemoFeatureMatchingPointClouds((Pointer)this).offsetAddress(i);
    }

    public DemoFeatureMatchingPointClouds(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public DemoFeatureMatchingPointClouds() { super((Pointer)null); allocate(); }
    private native void allocate();
    public DemoFeatureMatchingPointClouds(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Returns list of paths to point clouds, of size 2. */
    public native @StdString @StdVector BytePointer GetPointCloudPaths();
    /** \brief Returns list of paths to saved FPFH features binary for point
     *  clouds, respectively, of size 2. */
    public native @StdString @StdVector BytePointer GetFPFHFeaturePaths();
    /** \brief Returns list of paths to saved L32D features binary for point
     *  clouds, respectively, of size 2. */
    public native @StdString @StdVector BytePointer GetL32DFeaturePaths();
}
