// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/**
 * \brief Exports a PyObject* Tensor/NDArray to a DLManagedTensorVersioned.
 *
 * This function does not perform any stream synchronization. The consumer
 * should query DLPackCurrentWorkStream to get the current work stream and
 * launch kernels on it.
 *
 * This function is exposed by the framework through the DLPackExchangeAPI.
 *
 * @param py_object The Python object to convert. Must have the same type
 *        as the one the {@code DLPackExchangeAPI} was discovered from.
 * @return The owning DLManagedTensorVersioned* or NULL on failure with a
 *         Python exception set. If the data cannot be described using DLPack
 *         this should be a BufferError if possible.
 * \note - As a C function, must not thrown C++ exceptions.
 *
 * @see DLPackExchangeAPI, DLPackCurrentWorkStream
 */
@Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class DLPackManagedTensorFromPyObjectNoSync extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    DLPackManagedTensorFromPyObjectNoSync(Pointer p) { super(p); }
    protected DLPackManagedTensorFromPyObjectNoSync() { allocate(); }
    private native void allocate();
    public native int call(
        Pointer py_object,
        @Cast("DLManagedTensorVersioned**") PointerPointer out
);
}
