// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class Dtype extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Dtype(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Dtype(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public Dtype position(long position) {
        return (Dtype)super.position(position);
    }
    @Override public Dtype getPointer(long i) {
        return new Dtype((Pointer)this).offsetAddress(i);
    }

    @MemberGetter public static native @Const @ByRef Dtype Undefined();
    @MemberGetter public static native @Const @ByRef Dtype Float32();
    @MemberGetter public static native @Const @ByRef Dtype Float64();
    @MemberGetter public static native @Const @ByRef Dtype Int8();
    @MemberGetter public static native @Const @ByRef Dtype Int16();
    @MemberGetter public static native @Const @ByRef Dtype Int32();
    @MemberGetter public static native @Const @ByRef Dtype Int64();
    @MemberGetter public static native @Const @ByRef Dtype UInt8();
    @MemberGetter public static native @Const @ByRef Dtype UInt16();
    @MemberGetter public static native @Const @ByRef Dtype UInt32();
    @MemberGetter public static native @Const @ByRef Dtype UInt64();
    @MemberGetter public static native @Const @ByRef Dtype Bool();
    /** enum class Pointer */
    public static final int
        Undefined = 0,
        Bool = 1,  // Needed to distinguish bool from uint8_t.
        Int = 2,
        UInt = 3,
        Float = 4,
        Object = 5;

    public Dtype() { super((Pointer)null); allocate(); }
    private native void allocate();

    public Dtype(@Cast("Pointer") int dtype_code,
                       @Cast("int64_t") long byte_size,
                       @StdString BytePointer name) { super((Pointer)null); allocate(dtype_code, byte_size, name); }
    private native void allocate(@Cast("Pointer") int dtype_code,
                       @Cast("int64_t") long byte_size,
                       @StdString BytePointer name);
    public Dtype(@Cast("Pointer") int dtype_code,
                       @Cast("int64_t") long byte_size,
                       @StdString String name) { super((Pointer)null); allocate(dtype_code, byte_size, name); }
    private native void allocate(@Cast("Pointer") int dtype_code,
                       @Cast("int64_t") long byte_size,
                       @StdString String name);

    /** Convert from C++ types to Dtype. Known types are explicitly specialized,
     *  e.g. FromType<float>(). Unsupported type results in an exception. */

    public native @Cast("int64_t") long ByteSize();

    public native @Cast("Pointer") int GetDtypeCode();

    public native @Cast("bool") boolean IsObject();

    public native @StdString BytePointer ToString();

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef Dtype other);

    public native @Cast("bool") @Name("operator !=") boolean notEquals(@Const @ByRef Dtype other);
}
