// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class LivingRoomPointClouds
 *  \brief Dataset class for {@code LivingRoomPointClouds} contains 57 point
 *  clouds of binary PLY format.
 *  \copyright Creative Commons 3.0 (CC BY 3.0). */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class LivingRoomPointClouds extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LivingRoomPointClouds(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public LivingRoomPointClouds(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public LivingRoomPointClouds position(long position) {
        return (LivingRoomPointClouds)super.position(position);
    }
    @Override public LivingRoomPointClouds getPointer(long i) {
        return new LivingRoomPointClouds((Pointer)this).offsetAddress(i);
    }

    public LivingRoomPointClouds(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public LivingRoomPointClouds() { super((Pointer)null); allocate(); }
    private native void allocate();
    public LivingRoomPointClouds(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Returns list of paths to ply point-cloud fragments of size 57. */
    public native @StdString @StdVector BytePointer GetPaths();
    /** \brief Path to the ply point-cloud fragment at index (from 0 to
     *  56). Use {@code GetPaths(0)}, {@code GetPaths(1)} ... {@code GetPaths(56)} to access the
     *  paths. */
    public native @StdString BytePointer GetPaths(long index);
}
