// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** Singleton SYCL context manager. It maintains:
 *  - A default queue for each SYCL device */
@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class SYCLContext extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SYCLContext(Pointer p) { super(p); }

    
    

    /** Get singleton instance. */
    public static native @ByRef SYCLContext GetInstance();

    /** Returns true if there is at least one SYCL devices. */
    public native @Cast("bool") boolean IsAvailable();

    /** Returns true if the specified SYCL device is available. */
    public native @Cast("bool") boolean IsDeviceAvailable(@Const @ByRef Device device);

    /** Returns a list of all available SYCL devices. */
    public native @StdVector Device GetAvailableSYCLDevices();

    /** Get the default SYCL queue given an Open3D device. */
    public native @ByVal queue GetDefaultQueue(@Const @ByRef Device device);

    /** Get SYCL device properties given an Open3D device. */
    public native @ByVal SYCLDevice GetDeviceProperties(@Const @ByRef Device device);
}
