// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class TerrazzoTexture
 *  \brief Data class for {@code TerrazzoTexture} contains albedo, normal and
 *  roughness texture files for terrazzo based material. */
@Namespace("Pointer") @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class TerrazzoTexture extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TerrazzoTexture(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public TerrazzoTexture(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public TerrazzoTexture position(long position) {
        return (TerrazzoTexture)super.position(position);
    }
    @Override public TerrazzoTexture getPointer(long i) {
        return new TerrazzoTexture((Pointer)this).offsetAddress(i);
    }

    public TerrazzoTexture(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public TerrazzoTexture() { super((Pointer)null); allocate(); }
    private native void allocate();
    public TerrazzoTexture(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);
    /** \brief Returns the path to albedo color texture image. */
    public native @StdString BytePointer GetAlbedoTexturePath();
    /** \brief Returns the path to normal texture image. */
    public native @StdString BytePointer GetNormalTexturePath();
    /** \brief Returns the path to roughness texture image. */
    public native @StdString BytePointer GetRoughnessTexturePath();
    /** \brief Returns the map of filename to path. Refer documentation page for
     *  available options. */
}
