// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Additional output that should be gathered.
 *  \details By default gather output of shape [beamWidth, x] from each generation phase.
 *           If gatherContext is true, also gather output of shape [promptLen, x] from context phase. */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class AdditionalModelOutput extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AdditionalModelOutput(Pointer p) { super(p); }

    public AdditionalModelOutput(@ByVal @Cast("std::string*") BytePointer name, @Cast("bool") boolean gatherContext/*=false*/) { super((Pointer)null); allocate(name, gatherContext); }
    private native void allocate(@ByVal @Cast("std::string*") BytePointer name, @Cast("bool") boolean gatherContext/*=false*/);
    public AdditionalModelOutput(@ByVal @Cast("std::string*") BytePointer name) { super((Pointer)null); allocate(name); }
    private native void allocate(@ByVal @Cast("std::string*") BytePointer name);

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef AdditionalModelOutput other);

    public native @ByRef @Cast("std::string*") BytePointer name(); public native AdditionalModelOutput name(BytePointer setter);
    public native @Cast("bool") boolean gatherContext(); public native AdditionalModelOutput gatherContext(boolean setter);
}
