// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief A helper class for managing memory on host and device. */
@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class BufferManager extends Pointer {
    static { Loader.load(); }

    
    //!

    /** \brief Construct a BufferManager.
     * 
     *  @param cudaStream [in] The cuda stream to use for all operations on GPU (allocation, de-allocation, copying,
     *  etc.). */
    public BufferManager(@Cast("tensorrt_llm::runtime::BufferManager::CudaStreamPtr") Pointer stream, @Cast("bool") boolean trimPool/*=false*/) { super((Pointer)null); allocate(stream, trimPool); }
    private native void allocate(@Cast("tensorrt_llm::runtime::BufferManager::CudaStreamPtr") Pointer stream, @Cast("bool") boolean trimPool/*=false*/);
    public BufferManager(@Cast("tensorrt_llm::runtime::BufferManager::CudaStreamPtr") Pointer stream) { super((Pointer)null); allocate(stream); }
    private native void allocate(@Cast("tensorrt_llm::runtime::BufferManager::CudaStreamPtr") Pointer stream);

    /** \brief Destructor. */

    /** \brief Allocates an {@code IBuffer} of the given size on the GPU, using cudaMallocAsync. */
    public native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer gpu(@Cast("std::size_t") long size);

    /** \brief Allocates an {@code ITensor} of the given dimensions on the GPU, using cudaMallocAsync. */

    /** \brief Allocates an {@code IBuffer} of the given size on the GPU, using cudaMalloc. */
    public static native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer gpuSync(@Cast("std::size_t") long size);

    /** \brief Allocates an {@code ITensor} of the given dimensions on the GPU, using cudaMalloc. */

    /** \brief Allocates an {@code IBuffer} of the given size on the CPU. */
    public static native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer cpu(@Cast("std::size_t") long size);

    /** \brief Allocates an {@code ITensor} of the given dimensions on the CPU. */

    /** \brief Allocates a pinned {@code IBuffer} of the given size on the CPU. */
    public static native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer pinned(@Cast("std::size_t") long size);

    /** \brief Allocates a pinned {@code ITensor} of the given dimensions on the CPU. */

    /** \brief Allocates a pinned {@code IBuffer} of the given size on the CPU in the default memory pool. */
    public static native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer pinnedPool(@Cast("std::size_t") long size);

    /** \brief Allocates a pinned {@code ITensor} of the given dimensions on the CPU in the default memory pool. */

    /** \brief Allocates an {@code IBuffer} of the given size in UVM. */
    public static native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer managed(@Cast("std::size_t") long size);

    /** \brief Allocates an {@code ITensor} of the given dimensions in UVM. */

    /** \brief Allocates an {@code ITensor} of the given dimensions for NVLS */

    /** \brief Allocates an {@code IBuffer} of the given size and memory type. */
    public native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") @Name("allocate") IBuffer _allocate(
            @Cast("tensorrt_llm::runtime::MemoryType") int memoryType, @Cast("std::size_t") long size);

    /** \brief Allocates an {@code ITensor} of the given dimensions and memory type. */

    /** \brief Create an empty {@code IBuffer} of the given memory type. It may be resized later. */
    public native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") IBuffer emptyBuffer(@Cast("tensorrt_llm::runtime::MemoryType") int memoryType);

    /** \brief Create an empty {@code ITensor} of the given memory type. It may be reshaped later. */
    public native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::ITensorPtr*") ITensor emptyTensor(@Cast("tensorrt_llm::runtime::MemoryType") int memoryType);

    /** \brief Set the contents of the given {@code buffer} to value. */
    public void setMem(IBuffer buffer, int value) { _setMem(buffer.asIBuffer(), value); }
    private native @Name("setMem") void _setMem(@ByRef IBuffer buffer, int value);

    /** \brief Set the contents of the given {@code buffer} to zero. */
    public void setZero(IBuffer buffer) { _setZero(buffer.asIBuffer()); }
    private native @Name("setZero") void _setZero(@ByRef IBuffer buffer);

    /** \brief Copy {@code src} to {@code dst}. */
    public void copy(Pointer src, IBuffer dst, int srcType) { _copy(src, dst.asIBuffer(), srcType); }
    private native @Name("copy") void _copy(@Const Pointer src, @ByRef IBuffer dst, @Cast("tensorrt_llm::runtime::MemoryType") int srcType);

    /** \brief Copy {@code src} to {@code dst}. */
    public void copy(IBuffer src, Pointer dst, int dstType) { _copy(src.asIBuffer(), dst, dstType); }
    private native @Name("copy") void _copy(@Const @ByRef IBuffer src, Pointer dst, @Cast("tensorrt_llm::runtime::MemoryType") int dstType);

    /** \brief Copy {@code src} to {@code dst}. */
    public void copy(Pointer src, IBuffer dst) { _copy(src, dst.asIBuffer()); }
    private native @Name("copy") void _copy(@Const Pointer src, @ByRef IBuffer dst);

    /** \brief Copy {@code src} to {@code dst}. */
    public void copy(IBuffer src, Pointer dst) { _copy(src.asIBuffer(), dst); }
    private native @Name("copy") void _copy(@Const @ByRef IBuffer src, Pointer dst);

    /** \brief Copy {@code src} to {@code dst}. */
    public void copy(IBuffer src, IBuffer dst) { _copy(src.asIBuffer(), dst.asIBuffer()); }
    private native @Name("copy") void _copy(@Const @ByRef IBuffer src, @ByRef IBuffer dst);

    /** \brief Copy {@code src} into a new {@code IBuffer} with a potentially different memory type. */
    public IBuffer copyFrom(IBuffer src, int memoryType) { return _copyFrom(src.asIBuffer(), memoryType); }
    private native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::IBufferPtr*") @Name("copyFrom") IBuffer _copyFrom(@Const @ByRef IBuffer src, @Cast("tensorrt_llm::runtime::MemoryType") int memoryType);

    /** \brief Copy {@code src} into a new {@code ITensor} with a potentially different memory type. */
    public native @ByVal @Cast("tensorrt_llm::runtime::BufferManager::ITensorPtr*") ITensor copyFrom(@Const @ByRef ITensor src, @Cast("tensorrt_llm::runtime::MemoryType") int memoryType);

    /** \brief Copy {@code src} into a new {@code IBuffer} with a potentially different memory type. */

    /** \brief Copy {@code src} into a new {@code ITensor} with a potentially different memory type. */

    /** \brief Copy {@code src} into a new {@code ITensor} with a potentially different memory type. */

    /** \brief Get the underlying cuda stream. */
    public native @Cast("const tensorrt_llm::runtime::CudaStream*") @ByRef Pointer getStream();

    /** \brief The current size of the memory reserved by the memory pool. */
    public native @Cast("std::size_t") long memoryPoolReserved();

    /** \brief The current size of the memory used by the memory pool. */
    public native @Cast("std::size_t") long memoryPoolUsed();

    /** \brief The current size of the memory free in the memory pool. */
    public native @Cast("std::size_t") long memoryPoolFree();

    /** \brief Try to trim the memory reserved by the pool to {@code size} bytes. This synchronizes implicitly with the
     *  stream. */
    public native void memoryPoolTrimTo(@Cast("std::size_t") long size);
}
