// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Configuration class for the KV cache */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class KvCacheConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KvCacheConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public KvCacheConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public KvCacheConfig position(long position) {
        return (KvCacheConfig)super.position(position);
    }
    @Override public KvCacheConfig getPointer(long i) {
        return new KvCacheConfig((Pointer)this).offsetAddress(i);
    }


    public KvCacheConfig() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Cast("bool") boolean getEnableBlockReuse();
    public native @Cast("bool") boolean getEnablePartialReuse();
    public native @Cast("bool") boolean getCopyOnPartialReuse();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getMaxTokens();
    public native @StdVector @Optional IntPointer getMaxAttentionWindowVec();
    public native @Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer getSinkTokenLength();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getFreeGpuMemoryFraction();
    public native @Cast("tensorrt_llm::executor::FloatType*") @Optional FloatPointer getCrossKvCacheFraction();
    public native @Cast("size_t*") @Optional LongPointer getHostCacheSize();
    public native @Cast("bool") boolean getOnboardBlocks();
    public native @Cast("tensorrt_llm::executor::RetentionPriority*") @Optional IntPointer getSecondaryOffloadMinPriority();
    public native @Cast("size_t") long getEventBufferMaxSize();
    public native @Cast("bool") boolean getUseUvm();
    public native @Cast("tensorrt_llm::executor::SizeType32") int getAttentionDpEventsGatherPeriodMs();
    public native @Cast("uint64_t") long getMaxGpuTotalBytes();

    public native void setEnableBlockReuse(@Cast("bool") boolean enableBlockReuse);
    public native void setEnablePartialReuse(@Cast("bool") boolean enablePartialReuse);
    public native void setCopyOnPartialReuse(@Cast("bool") boolean copyOnPartialReuse);
    public native void setMaxTokens(@Cast("tensorrt_llm::executor::SizeType32*") @Optional IntPointer maxTokens);
    public native void setMaxAttentionWindowVec(@StdVector @ByVal IntPointer maxAttentionWindowVec);
    public native void setSinkTokenLength(@Cast("tensorrt_llm::executor::SizeType32") int sinkTokenLength);
    public native void setFreeGpuMemoryFraction(@Cast("tensorrt_llm::executor::FloatType") float freeGpuMemoryFraction);
    public native void setCrossKvCacheFraction(@Cast("tensorrt_llm::executor::FloatType") float crossKvCacheFraction);
    public native void setHostCacheSize(@Cast("size_t") long hostCacheSize);
    public native void setOnboardBlocks(@Cast("bool") boolean onboardBlocks);
    public native void setSecondaryOffloadMinPriority(@Cast("tensorrt_llm::executor::RetentionPriority*") @Optional IntPointer secondaryOffloadMinPriority);
    public native void setEventBufferMaxSize(@Cast("size_t") long eventBufferMaxSize);
    public native void setUseUvm(@Cast("bool") boolean useUvm);
    public native void setAttentionDpEventsGatherPeriodMs(@Cast("tensorrt_llm::executor::SizeType32") int attentionDpEventsGatherPeriodMs);
    public native void setMaxGpuTotalBytes(@Cast("uint64_t") long maxGpuTotalBytes);
}
