// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Configuration for Look-Ahead speculative decoding.
 *  Allows to include window size, ngram size and verification set size */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class LookaheadDecodingConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LookaheadDecodingConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public LookaheadDecodingConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public LookaheadDecodingConfig position(long position) {
        return (LookaheadDecodingConfig)super.position(position);
    }
    @Override public LookaheadDecodingConfig getPointer(long i) {
        return new LookaheadDecodingConfig((Pointer)this).offsetAddress(i);
    }

    public LookaheadDecodingConfig(@ByVal SizeType32 windowSize, @ByVal SizeType32 ngramSize, @ByVal SizeType32 verificationSetSize) { super((Pointer)null); allocate(windowSize, ngramSize, verificationSetSize); }
    private native void allocate(@ByVal SizeType32 windowSize, @ByVal SizeType32 ngramSize, @ByVal SizeType32 verificationSetSize);

    public LookaheadDecodingConfig() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Cast("bool") @Name("operator ==") boolean equals(@Const @ByRef LookaheadDecodingConfig other);
    public native @ByVal std::tuple<const tensorrt_llm::executor::SizeType32,const tensorrt_llm::executor::SizeType32,const tensorrt_llm::executor::SizeType32> get();
    public native @ByVal SizeType32 getWindowSize();
    public native @ByVal SizeType32 getNgramSize();
    public native @ByVal SizeType32 getVerificationSetSize();

    /** \brief return <maxDecodingTokens, maxPathLen, maxDraftTokens, maxDraftPathLen> */
    public native @ByVal std::tuple<tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32> calculateSpeculativeResource();
    public static native @ByVal std::tuple<tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32,tensorrt_llm::executor::SizeType32> calculateSpeculativeResourceTuple(
            @ByVal SizeType32 windowSize, @ByVal SizeType32 ngramSize, @ByVal SizeType32 verificationSetSize);

    /** \brief return true when {@code this} can be executed on resources defined by {@code that} */
    public native @Cast("bool") boolean isLE(@Const @ByRef LookaheadDecodingConfig that);

    /** \brief return true when the parameter combination is valid. */
    public static native @Cast("bool") @NoException(true) boolean isLegal(@ByVal SizeType32 windowSize, @ByVal SizeType32 ngramSize, @ByVal SizeType32 verificationSetSize);

    @MemberGetter public static native @Const @ByRef SizeType32 kDefaultLookaheadDecodingWindow();
    @MemberGetter public static native @Const @ByRef SizeType32 kDefaultLookaheadDecodingNgram();
    @MemberGetter public static native @Const @ByRef SizeType32 kDefaultLookaheadDecodingVerificationSet();
}
