// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief Multimodal input data class */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class MultimodalInput extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MultimodalInput(Pointer p) { super(p); }

    public MultimodalInput(@StdVector std::vector<tensorrt_llm::executor::SizeType32> multimodalHashes,
            @StdVector SizeType32 multimodalPositions, @StdVector SizeType32 multimodalLengths,
            @Optional std::vector<std::optional<std::string> > multimodalUuids/*=std::nullopt*/) { super((Pointer)null); allocate(multimodalHashes, multimodalPositions, multimodalLengths, multimodalUuids); }
    private native void allocate(@StdVector std::vector<tensorrt_llm::executor::SizeType32> multimodalHashes,
            @StdVector SizeType32 multimodalPositions, @StdVector SizeType32 multimodalLengths,
            @Optional std::vector<std::optional<std::string> > multimodalUuids/*=std::nullopt*/);
    public MultimodalInput(@StdVector std::vector<tensorrt_llm::executor::SizeType32> multimodalHashes,
            @StdVector SizeType32 multimodalPositions, @StdVector SizeType32 multimodalLengths) { super((Pointer)null); allocate(multimodalHashes, multimodalPositions, multimodalLengths); }
    private native void allocate(@StdVector std::vector<tensorrt_llm::executor::SizeType32> multimodalHashes,
            @StdVector SizeType32 multimodalPositions, @StdVector SizeType32 multimodalLengths);

    public native @StdVector std::vector<tensorrt_llm::executor::SizeType32> getMultimodalHashes();
    public native @StdVector SizeType32 getMultimodalPositions();
    public native @StdVector SizeType32 getMultimodalLengths();
    public native @Optional std::vector<std::optional<std::string> > getMultimodalUuids();
}
