// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;


/** \brief A class that holds information about the request */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class Request extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Request(Pointer p) { super(p); }

    @MemberGetter public static native @Const @ByRef PriorityType kDefaultPriority();

    /** \brief The Request constructor
     <p>
     *  @param inputTokenIds The input token ids
     *  @param maxTokens  The maximum number of tokens to generate
     *  @param streaming Indicates if the responses should be streamed or not. Default is false.
     *  @param samplingConfig The sampling configuration
     *  @param outputConfig The output configuration
     *  @param endId The end token id
     *  @param padId The pad token id
     *  @param positionIds The input position ids
     *  @param badWords A list of bad words tokens. Each "word" can be composed of multiple tokens
     *  @param stopWords A list of stop words tokens. Each "word" can be composed of multiple tokens
     *  @param embeddingBias The embedding bias tensor. Expected shape is [vocab_size]
     *  @param externalDraftTokensConfig The speculative decoding with external draft tokens configuration
     *  @param pTuningConfig The prompt tuning configuration
     *  @param multimodalInput The multimodal input {multimodalHashes, multimodalPositions, multimodalLengths}
     *  @param multimodalEmbedding The multimodal embedding tensor. Expected shape is [num_multimodal_tokens,
     *  hidden_dim]
     *  @param mRopeConfig The mrope configuration
     *  @param loraConfig The LoRA configuration
     *  @param lookaheadConfig The lookahead speculative decoding configuration
     *  @param kvCacheRetentionConfig The configuration used for KV cache block eviction.
     *  @param logitsPostProcessorName The logits postprocessor name. Must correspond to one of the logits postprocessor
     *  name provided to the ExecutorConfig.
     *  @param logitsPostProcessor The logits postprocessor dynamically specified per request; only supported with
     *  replicate=false or no tensor parallelism.
     *  @param encoderInputTokenIds The encoder input token ids for encoder-decoder models, or encoder-only models
     *  @param clientId
     *  @param returnAllGeneratedTokens Indicates whether to return the full beams or just the newly generated tokens
     *  after every streaming step.
     *  @param priority Sets the execution priority of this request.
     *  @param type Indicate the request type for disaggregated serving mode.
     *  @param contextPhaseParams Generated token ID  from context only executor.
     *  @param encoderInputFeatures Encoder input features for multimodal models.
     *  @param encoderOutputLength Encoder output length if encoder input and output have different lengths (due to
     *  convolution down-sampling, etc.)
     *  @param crossAttentionMask Cross attention mask.
     *  @param numReturnSequences The number of returning sequences.
     *  @param eagleConfig The EAGLE speculative decoding configuration
     *  @param skipCrossAttnBlocks Skip the cross attention transformer blocks or not.
     *  @param guidedDecodingParams The guided decoding parameters.
     *  @param languageAdapterUid Task Uid for language adapter.
     *  @param allottedTimeMs The allotted time in milliseconds after which the request is cancelled with a timedOut
     *  finish reason. The request may exceed this time slightly, but at most by 1 forward pass (in pipeline parallelism
     *  that may involve multiple micro-batches). A request can be timed-out before ever being scheduled.
     *  @param cacheSaltID Salt ID for KV cache blocks to limit the kv cache reuse to the requests with the same string.
     *  @param disaggRequestId Disaggregated request ID. */
    public Request(@ByVal VecTokens inputTokenIds, @ByVal SizeType32 maxTokens, @Cast("bool") boolean streaming/*=false*/,
            @Const @ByRef(nullValue = "tensorrt_llm::executor::SamplingConfig()") SamplingConfig samplingConfig, @Const @ByRef(nullValue = "tensorrt_llm::executor::OutputConfig()") OutputConfig outputConfig,
            @Optional SizeType32 endId/*=std::nullopt*/, @Optional SizeType32 padId/*=std::nullopt*/,
            @Optional std::vector<tensorrt_llm::executor::SizeType32> positionIds/*=std::nullopt*/,
            @Optional std::list<VecTokens> badWords/*=std::nullopt*/,
            @Optional std::list<VecTokens> stopWords/*=std::nullopt*/,
            @Optional Tensor embeddingBias/*=std::nullopt*/,
            @Optional ExternalDraftTokensConfig externalDraftTokensConfig/*=std::nullopt*/,
            @Optional PromptTuningConfig pTuningConfig/*=std::nullopt*/,
            @Optional MultimodalInput multimodalInput/*=std::nullopt*/,
            @Optional Tensor multimodalEmbedding/*=std::nullopt*/, @Optional MropeConfig mRopeConfig/*=std::nullopt*/,
            @Optional LoraConfig loraConfig/*=std::nullopt*/,
            @Optional LookaheadDecodingConfig lookaheadConfig/*=std::nullopt*/,
            @Optional KvCacheRetentionConfig kvCacheRetentionConfig/*=std::nullopt*/,
            @Cast("std::string*") @Optional BytePointer logitsPostProcessorName/*=std::nullopt*/,
            @Optional LogitsPostProcessor logitsPostProcessor/*=std::nullopt*/,
            @Optional VecTokens encoderInputTokenIds/*=std::nullopt*/, @Optional IdType clientId/*=std::nullopt*/,
            @Cast("bool") boolean returnAllGeneratedTokens/*=false*/, @ByVal(nullValue = "PriorityType(tensorrt_llm::executor::Request::kDefaultPriority)") PriorityType priority,
            @ByVal(nullValue = "RequestType::REQUEST_TYPE_CONTEXT_AND_GENERATION") RequestType type,
            @Optional ContextPhaseParams contextPhaseParams/*=std::nullopt*/,
            @Optional Tensor encoderInputFeatures/*=std::nullopt*/,
            @Optional SizeType32 encoderOutputLength/*=std::nullopt*/,
            @Optional Tensor crossAttentionMask/*=std::nullopt*/, @ByVal(nullValue = "tensorrt_llm::executor::SizeType32(1)") SizeType32 numReturnSequences,
            @Optional EagleConfig eagleConfig/*=std::nullopt*/, @Optional Tensor skipCrossAttnBlocks/*=std::nullopt*/,
            @Optional GuidedDecodingParams guidedDecodingParams/*=std::nullopt*/,
            @Optional SizeType32 languageAdapterUid/*=std::nullopt*/,
            @Optional MillisecondsType allottedTimeMs/*=std::nullopt*/,
            @Optional CacheSaltIDType cacheSaltID/*=std::nullopt*/,
            @Optional IdType disaggRequestId/*=std::nullopt*/) { super((Pointer)null); allocate(inputTokenIds, maxTokens, streaming, samplingConfig, outputConfig, endId, padId, positionIds, badWords, stopWords, embeddingBias, externalDraftTokensConfig, pTuningConfig, multimodalInput, multimodalEmbedding, mRopeConfig, loraConfig, lookaheadConfig, kvCacheRetentionConfig, logitsPostProcessorName, logitsPostProcessor, encoderInputTokenIds, clientId, returnAllGeneratedTokens, priority, type, contextPhaseParams, encoderInputFeatures, encoderOutputLength, crossAttentionMask, numReturnSequences, eagleConfig, skipCrossAttnBlocks, guidedDecodingParams, languageAdapterUid, allottedTimeMs, cacheSaltID, disaggRequestId); }
    private native void allocate(@ByVal VecTokens inputTokenIds, @ByVal SizeType32 maxTokens, @Cast("bool") boolean streaming/*=false*/,
            @Const @ByRef(nullValue = "tensorrt_llm::executor::SamplingConfig()") SamplingConfig samplingConfig, @Const @ByRef(nullValue = "tensorrt_llm::executor::OutputConfig()") OutputConfig outputConfig,
            @Optional SizeType32 endId/*=std::nullopt*/, @Optional SizeType32 padId/*=std::nullopt*/,
            @Optional std::vector<tensorrt_llm::executor::SizeType32> positionIds/*=std::nullopt*/,
            @Optional std::list<VecTokens> badWords/*=std::nullopt*/,
            @Optional std::list<VecTokens> stopWords/*=std::nullopt*/,
            @Optional Tensor embeddingBias/*=std::nullopt*/,
            @Optional ExternalDraftTokensConfig externalDraftTokensConfig/*=std::nullopt*/,
            @Optional PromptTuningConfig pTuningConfig/*=std::nullopt*/,
            @Optional MultimodalInput multimodalInput/*=std::nullopt*/,
            @Optional Tensor multimodalEmbedding/*=std::nullopt*/, @Optional MropeConfig mRopeConfig/*=std::nullopt*/,
            @Optional LoraConfig loraConfig/*=std::nullopt*/,
            @Optional LookaheadDecodingConfig lookaheadConfig/*=std::nullopt*/,
            @Optional KvCacheRetentionConfig kvCacheRetentionConfig/*=std::nullopt*/,
            @Cast("std::string*") @Optional BytePointer logitsPostProcessorName/*=std::nullopt*/,
            @Optional LogitsPostProcessor logitsPostProcessor/*=std::nullopt*/,
            @Optional VecTokens encoderInputTokenIds/*=std::nullopt*/, @Optional IdType clientId/*=std::nullopt*/,
            @Cast("bool") boolean returnAllGeneratedTokens/*=false*/, @ByVal(nullValue = "PriorityType(tensorrt_llm::executor::Request::kDefaultPriority)") PriorityType priority,
            @ByVal(nullValue = "RequestType::REQUEST_TYPE_CONTEXT_AND_GENERATION") RequestType type,
            @Optional ContextPhaseParams contextPhaseParams/*=std::nullopt*/,
            @Optional Tensor encoderInputFeatures/*=std::nullopt*/,
            @Optional SizeType32 encoderOutputLength/*=std::nullopt*/,
            @Optional Tensor crossAttentionMask/*=std::nullopt*/, @ByVal(nullValue = "tensorrt_llm::executor::SizeType32(1)") SizeType32 numReturnSequences,
            @Optional EagleConfig eagleConfig/*=std::nullopt*/, @Optional Tensor skipCrossAttnBlocks/*=std::nullopt*/,
            @Optional GuidedDecodingParams guidedDecodingParams/*=std::nullopt*/,
            @Optional SizeType32 languageAdapterUid/*=std::nullopt*/,
            @Optional MillisecondsType allottedTimeMs/*=std::nullopt*/,
            @Optional CacheSaltIDType cacheSaltID/*=std::nullopt*/,
            @Optional IdType disaggRequestId/*=std::nullopt*/);
    public Request(@ByVal VecTokens inputTokenIds, @ByVal SizeType32 maxTokens) { super((Pointer)null); allocate(inputTokenIds, maxTokens); }
    private native void allocate(@ByVal VecTokens inputTokenIds, @ByVal SizeType32 maxTokens);

    /** \brief This logits postprocessor name will dispatch to the batched logits postprocessor */
    @MemberGetter public static native @Const @ByRef auto kBatchedPostProcessorName();
    /** \brief Dynamic logits postprocessor name will be "dynamic" + requestId */
    @MemberGetter public static native @Const @ByRef auto kDynamicPostProcessorNamePrefix();

    public Request(@Const @ByRef Request other) { super((Pointer)null); allocate(other); }
    private native void allocate(@Const @ByRef Request other);
    public native @ByRef @Name("operator =") Request put(@Const @ByRef Request other);

    public native @ByVal VecTokens getInputTokenIds();
    public native @ByVal SizeType32 getMaxTokens();
    public native @Cast("bool") boolean getStreaming();
    public native @ByVal SamplingConfig getSamplingConfig();
    public native @ByVal OutputConfig getOutputConfig();
    public native @Optional SizeType32 getEndId();
    public native @Optional SizeType32 getPadId();
    public native @Optional std::vector<tensorrt_llm::executor::SizeType32> getPositionIds();
    public native @Optional std::list<VecTokens> getBadWords();
    public native @Optional std::list<VecTokens> getStopWords();
    public native @Optional Tensor getEmbeddingBias();
    public native @Optional ExternalDraftTokensConfig getExternalDraftTokensConfig();
    public native @Optional PromptTuningConfig getPromptTuningConfig();
    public native @Optional MultimodalInput getMultimodalInput();
    public native @Optional Tensor getMultimodalEmbedding();
    public native @Optional MropeConfig getMropeConfig();
    public native @Optional LoraConfig getLoraConfig();
    public native @Optional LookaheadDecodingConfig getLookaheadConfig();
    public native @Optional KvCacheRetentionConfig getKvCacheRetentionConfig();
    public native @Cast("std::string*") @Optional BytePointer getLogitsPostProcessorName();
    public native @Optional LogitsPostProcessor getLogitsPostProcessor();
    public native @Optional VecTokens getEncoderInputTokenIds();
    public native @Optional IdType getClientId();
    public native @ByVal PriorityType getPriority();
    public native @Cast("bool") boolean getReturnAllGeneratedTokens();
    public native @Optional ContextPhaseParams getContextPhaseParams();
    public native @Optional Tensor getEncoderInputFeatures();
    public native @Optional SizeType32 getEncoderOutputLength();
    public native @Optional Tensor getCrossAttentionMask();
    public native @ByVal RequestType getRequestType();
    public native @Optional EagleConfig getEagleConfig();
    public native @Optional Tensor getSkipCrossAttnBlocks();
    public native @Optional GuidedDecodingParams getGuidedDecodingParams();
    public native @Optional SizeType32 getLanguageAdapterUid();
    public native @Optional MillisecondsType getAllottedTimeMs();
    public native @Optional CacheSaltIDType getCacheSaltID();
    public native @Optional std::vector<std::string> getAdditionalOutputNames();
    public native @Optional IdType getDisaggRequestId();

    public native void setStreaming(@Cast("bool") boolean streaming);
    public native void setSamplingConfig(@Const @ByRef SamplingConfig config);
    public native void setOutputConfig(@Const @ByRef OutputConfig outputConfig);
    public native void setEndId(@ByVal SizeType32 endId);
    public native void setPadId(@ByVal SizeType32 padId);
    public native void setPositionIds(@StdVector SizeType32 positionIds);
    public native void setBadWords(@Const @ByRef std::list<VecTokens> badWords);
    public native void setStopWords(@Const @ByRef std::list<VecTokens> stopWords);
    public native void setEmbeddingBias(@Const @ByRef Tensor embeddingBias);
    public native void setExternalDraftTokensConfig(@Const @ByRef ExternalDraftTokensConfig externalDraftTokensConfig);
    public native void setPromptTuningConfig(@Const @ByRef PromptTuningConfig pTuningConfig);
    public native void setMultimodalEmbedding(@Const @ByRef Tensor multimodalEmbedding);
    public native void setMultimodalInput(@Const @ByRef MultimodalInput multimodalInput);
    public native void setMropeConfig(@Const @ByRef MropeConfig mRopeConfig);
    public native void setLoraConfig(@Const @ByRef LoraConfig loraConfig);
    public native void setLookaheadConfig(@Const @ByRef LookaheadDecodingConfig lookaheadConfig);
    public native void setKvCacheRetentionConfig(@Const @ByRef KvCacheRetentionConfig kvCacheRetentionConfig);
    public native void setLogitsPostProcessorName(@Cast("const std::string*") @ByRef BytePointer logitsPostProcessorName);
    public native void setLogitsPostProcessor(@Optional LogitsPostProcessor logitsPostProcessor);
    public native void setEncoderInputTokenIds(@Const @ByRef VecTokens encoderInputTokenIds);
    public native void setClientId(@ByVal IdType clientId);
    public native void setPriority(@ByVal PriorityType priority);
    public native void setReturnAllGeneratedTokens(@Cast("bool") boolean returnAllGeneratedTokens);
    public native void setRequestType(@Const @ByRef RequestType requestType);
    public native void setContextPhaseParams(@ByVal ContextPhaseParams contextPhaseParams);
    public native void setEncoderInputFeatures(@ByVal Tensor encoderInputFeatures);
    public native void setEncoderOutputLength(@ByVal SizeType32 encoderOutputLength);
    public native void setCrossAttentionMask(@ByVal Tensor crossAttentionMask);
    public native void setEagleConfig(@Optional EagleConfig eagleConfig);
    public native void setSkipCrossAttnBlocks(@ByVal Tensor skipCrossAttnBlocks);
    public native void setGuidedDecodingParams(@Const @ByRef GuidedDecodingParams guidedDecodingParams);
    public native void setLanguageAdapterUid(@ByVal SizeType32 languageAdapterUid);
    public native void setAllottedTimeMs(@ByVal MillisecondsType allottedTimeMs);
    public native void setCacheSaltID(@ByVal CacheSaltIDType cacheSaltID);
    public native void setDisaggRequestId(@ByVal IdType disaggRequestId);
}
