// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.tensorrt_llm.global.TRTLLM.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.TRTLLMFullConfig.class)
public class WorldConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public WorldConfig(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public WorldConfig(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public WorldConfig position(long position) {
        return (WorldConfig)super.position(position);
    }
    @Override public WorldConfig getPointer(long i) {
        return new WorldConfig((Pointer)this).offsetAddress(i);
    }

// #if ENABLE_MULTI_DEVICE
    @MemberGetter public static native @Const @ByRef SizeType32 kDefaultGpusPerNode();
// #else
// #endif

    public WorldConfig(@ByVal(nullValue = "SizeType32(1)") SizeType32 tensorParallelism, @ByVal(nullValue = "SizeType32(1)") SizeType32 pipelineParallelism,
            @ByVal(nullValue = "SizeType32(1)") SizeType32 contextParallelism, @ByVal(nullValue = "SizeType32(0)") SizeType32 rank, @ByVal(nullValue = "SizeType32(tensorrt_llm::runtime::WorldConfig::kDefaultGpusPerNode)") SizeType32 gpusPerNode,
            @Optional std::vector<SizeType32> deviceIds/*=std::nullopt*/, @Cast("bool") boolean enableAttentionDP/*=false*/) { super((Pointer)null); allocate(tensorParallelism, pipelineParallelism, contextParallelism, rank, gpusPerNode, deviceIds, enableAttentionDP); }
    private native void allocate(@ByVal(nullValue = "SizeType32(1)") SizeType32 tensorParallelism, @ByVal(nullValue = "SizeType32(1)") SizeType32 pipelineParallelism,
            @ByVal(nullValue = "SizeType32(1)") SizeType32 contextParallelism, @ByVal(nullValue = "SizeType32(0)") SizeType32 rank, @ByVal(nullValue = "SizeType32(tensorrt_llm::runtime::WorldConfig::kDefaultGpusPerNode)") SizeType32 gpusPerNode,
            @Optional std::vector<SizeType32> deviceIds/*=std::nullopt*/, @Cast("bool") boolean enableAttentionDP/*=false*/);
    public WorldConfig() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Const @ByVal @NoException(true) SizeType32 getSize();

    public native @Const @ByVal @NoException(true) SizeType32 getTensorParallelism();

    public native @Cast("const bool") @NoException(true) boolean isTensorParallel();

    public native @Const @ByVal @NoException(true) SizeType32 getPipelineParallelism();

    public native @Cast("const bool") @NoException(true) boolean isPipelineParallel();

    public native @Const @ByVal @NoException(true) SizeType32 getContextParallelism();

    public native @Cast("const bool") @NoException(true) boolean isContextParallel();

    public native @Const @ByVal @NoException(true) SizeType32 getRank();

    public native @Const @ByVal @NoException(true) SizeType32 getGpusPerNode();

    public native @ByVal @NoException(true) SizeType32 getGpusPerGroup();

    public native @ByVal @NoException(true) SizeType32 getDevice();

    public native @ByVal @NoException(true) SizeType32 getDeviceOf(@ByVal SizeType32 rank);

    public native @Const @ByVal @NoException(true) SizeType32 getPipelineParallelRank();

    public native @Const @ByVal @NoException(true) SizeType32 getTensorParallelRank();

    public native @Const @ByVal @NoException(true) SizeType32 getContextParallelRank();

    public native @Const @ByVal @NoException(true) SizeType32 getLocalRank();

    public native @Const @ByVal @NoException(true) SizeType32 getNodeRank();

    public native @Const @ByVal @NoException(true) SizeType32 getNodeRankOf(@ByVal SizeType32 rank);

    public native @Cast("const bool") @NoException(true) boolean isFirstPipelineParallelRank();

    /** \brief Is my rank the last rank in its pipeline? */
    public native @Cast("const bool") @NoException(true) boolean isLastPipelineParallelRank();

    public native @Cast("const bool") @NoException(true) boolean isFirstTensorParallelRank();

    public native @Cast("const bool") @NoException(true) boolean isFirstContextParallelRank();

    public native @Const @ByVal @NoException(true) SizeType32 getLastRank();

    public native @Cast("const bool") @NoException(true) boolean enableAttentionDP();

    public native @StdVector SizeType32 getPipelineParallelGroup();
    public native @StdVector SizeType32 getTensorParallelGroup();
    public native @StdVector SizeType32 getContextParallelGroup();

    public static native @ByVal WorldConfig mpi(@ByVal(nullValue = "SizeType32(tensorrt_llm::runtime::WorldConfig::kDefaultGpusPerNode)") SizeType32 gpusPerNode,
            @Optional SizeType32 tensorParallelism/*=std::nullopt*/,
            @Optional SizeType32 pipelineParallelism/*=std::nullopt*/,
            @Optional SizeType32 contextParallelism/*=std::nullopt*/,
            @Optional std::vector<SizeType32> deviceIds/*=std::nullopt*/, @Cast("bool") boolean enableAttentionDP/*=false*/);
    public static native @ByVal WorldConfig mpi();

    public native @Cast("bool") boolean validMpiConfig();
}
