// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.pipelines;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DPipelines.*;


/** \class L2Loss
 * 
 *  Classical loss function used for outlier rejection.
 * 
 *  The loss p(r) for a given residual 'r' is computed as follow:
 *     p(r) = r^2 / 2 */
@Namespace("open3d::pipelines::registration") @Properties(inherit = org.bytedeco.open3d.presets.Open3DPipelinesConfig.class)
public class L2Loss extends RobustKernel {
    static { Loader.load(); }
    /** Default native constructor. */
    public L2Loss() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public L2Loss(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public L2Loss(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public L2Loss position(long position) {
        return (L2Loss)super.position(position);
    }
    @Override public L2Loss getPointer(long i) {
        return new L2Loss((Pointer)this).offsetAddress(i);
    }

    /** The weight w(r) for a given residual 'r' is computed as follow:
     *    w(r) = 1.0, for all r
     * 
     *  @param residual [ignored] */
    public native double Weight(double residual);
}
