// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;


@Namespace("tensorrt_llm::plugins") @NoOffset @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class CudaStreamPluginCreator extends BaseCreator {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CudaStreamPluginCreator(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CudaStreamPluginCreator(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public CudaStreamPluginCreator position(long position) {
        return (CudaStreamPluginCreator)super.position(position);
    }
    @Override public CudaStreamPluginCreator getPointer(long i) {
        return new CudaStreamPluginCreator((Pointer)this).offsetAddress(i);
    }

    public CudaStreamPluginCreator() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @NoException(true) @Cast("const char*") BytePointer getPluginName();

    public native @NoException(true) @Cast("const char*") BytePointer getPluginVersion();

    public native @Const @NoException(true) PluginFieldCollection getFieldNames();

    public native @NoException(true) IPluginV2 createPlugin(@Cast("const char*") BytePointer name, @Const PluginFieldCollection fc);
    public native @NoException(true) IPluginV2 createPlugin(String name, @Const PluginFieldCollection fc);

    public native @NoException(true) IPluginV2 deserializePlugin(
            @Cast("const char*") BytePointer name, @Const Pointer serialData, long serialLength);
    public native @NoException(true) IPluginV2 deserializePlugin(
            String name, @Const Pointer serialData, long serialLength);
}
