// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;


@Namespace("tensorrt_llm::plugins") @NoOffset @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class GemmDims extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GemmDims(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GemmDims(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public GemmDims position(long position) {
        return (GemmDims)super.position(position);
    }
    @Override public GemmDims getPointer(long i) {
        return new GemmDims((Pointer)this).offsetAddress(i);
    }


    public native @ByRef DimType64 minM(); public native GemmDims minM(DimType64 setter);
    public native @ByRef DimType64 maxM(); public native GemmDims maxM(DimType64 setter);
    public native @ByRef DimType64 n(); public native GemmDims n(DimType64 setter);
    public native @ByRef DimType64 k(); public native GemmDims k(DimType64 setter);

    public GemmDims() { super((Pointer)null); allocate(); }
    private native void allocate();

    public GemmDims(@ByVal DimType64 minM_, @ByVal DimType64 maxM_, @ByVal DimType64 n_, @ByVal DimType64 k_) { super((Pointer)null); allocate(minM_, maxM_, n_, k_); }
    private native void allocate(@ByVal DimType64 minM_, @ByVal DimType64 maxM_, @ByVal DimType64 n_, @ByVal DimType64 k_);

    public native boolean isInitialized();
}
