// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;
          // typedef _k4a_device_t* k4a_device_t;
@Opaque @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class _k4a_transformation_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public _k4a_transformation_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public _k4a_transformation_t(Pointer p) { super(p); }
}
