// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** \class CauchyLoss
 * 
 *  CauchyLoss loss function used for outlier rejection.
 * 
 *  The loss p(r) for a given residual 'r' is computed as follow:
 *    p(r) = (k^2 / 2) * log(1 + (r / k)^2), for all r */
@Namespace("open3d::pipelines::registration") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class CauchyLoss extends RobustKernel {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CauchyLoss(Pointer p) { super(p); }

    /** \brief Parametrized Constructor.
     * 
     *  @param k Is the scaling parameter of the loss function. */
    
    ///
    public CauchyLoss(double k) { super((Pointer)null); allocate(k); }
    private native void allocate(double k);

    /** The weight w(r) for a given residual 'r' is computed as follow:
     *    w(r) = 1 / (1 + (r / k)^2)
     *  Where k Is the scaling parameter of the loss function.
     * 
     *  @param residual Residual value obtained during the optimization step. */
    public native double Weight(double residual);
    /** Scaling parameter. */
    public native double k_(); public native CauchyLoss k_(double setter);
}
