// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** Receiver implementation which always returns a successful status.
 *  This class is meant for testing puproses. */
@Namespace("open3d::io::rpc") @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class DummyReceiver extends ZMQReceiver {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DummyReceiver(Pointer p) { super(p); }

    public DummyReceiver(@StdString BytePointer _address, int timeout) { super((Pointer)null); allocate(_address, timeout); }
    private native void allocate(@StdString BytePointer _address, int timeout);
    public DummyReceiver(@StdString String _address, int timeout) { super((Pointer)null); allocate(_address, timeout); }
    private native void allocate(@StdString String _address, int timeout);
}
