// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


@Namespace("open3d::utility") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class FPSTimer extends Timer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FPSTimer(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public FPSTimer(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public FPSTimer position(long position) {
        return (FPSTimer)super.position(position);
    }
    @Override public FPSTimer getPointer(long i) {
        return new FPSTimer((Pointer)this).offsetAddress(i);
    }

    public FPSTimer(@StdString BytePointer fps_timer_info/*=""*/,
                 int expectation/*=-1*/,
                 double time_to_print/*=3000.0*/,
                 int events_to_print/*=100*/) { super((Pointer)null); allocate(fps_timer_info, expectation, time_to_print, events_to_print); }
    private native void allocate(@StdString BytePointer fps_timer_info/*=""*/,
                 int expectation/*=-1*/,
                 double time_to_print/*=3000.0*/,
                 int events_to_print/*=100*/);
    public FPSTimer() { super((Pointer)null); allocate(); }
    private native void allocate();
    public FPSTimer(@StdString String fps_timer_info/*=""*/,
                 int expectation/*=-1*/,
                 double time_to_print/*=3000.0*/,
                 int events_to_print/*=100*/) { super((Pointer)null); allocate(fps_timer_info, expectation, time_to_print, events_to_print); }
    private native void allocate(@StdString String fps_timer_info/*=""*/,
                 int expectation/*=-1*/,
                 double time_to_print/*=3000.0*/,
                 int events_to_print/*=100*/);

    /** Function to signal an event
     *  It automatically prints FPS information when duration is more than
     *  time_to_print_, or event has been signaled events_to_print_ times. */
    public native void Signal();
}
