// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** \class Geometry
 * 
 *  \brief The base geometry class. */
@Namespace("open3d::geometry") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class Geometry extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Geometry(Pointer p) { super(p); }

    /** \enum GeometryType
     * 
     *  \brief Specifies possible geometry types. */
    /** enum class open3d::geometry::Geometry::GeometryType */
    public static final int
        /** Unspecified geometry type. */
        Unspecified = 0,
        /** PointCloud */
        PointCloud = 1,
        /** VoxelGrid */
        VoxelGrid = 2,
        /** Octree */
        Octree = 3,
        /** LineSet */
        LineSet = 4,
        /** MeshBase */
        MeshBase = 5,
        /** TriangleMesh */
        TriangleMesh = 6,
        /** HalfEdgeTriangleMesh */
        HalfEdgeTriangleMesh = 7,
        /** Image */
        Image = 8,
        /** RGBDImage */
        RGBDImage = 9,
        /** TetraMesh */
        TetraMesh = 10,
        /** OrientedBoundingBox */
        OrientedBoundingBox = 11,
        /** AxisAlignedBoundingBox */
        AxisAlignedBoundingBox = 12;
    /** Clear all elements in the geometry. */
    public native @ByRef Geometry Clear();
    /** Returns {@code true} iff the geometry is empty. */
    public native @Cast("bool") boolean IsEmpty();
    /** Returns one of registered geometry types. */
    public native @Cast("open3d::geometry::Geometry::GeometryType") int GetGeometryType();
    /** Returns whether the geometry is 2D or 3D. */
    public native int Dimension();

    public native @StdString BytePointer GetName();
    public native void SetName(@StdString BytePointer name);
    public native void SetName(@StdString String name);
}
