// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** \class KDTreeSearchParam
 * 
 *  \brief Base class for KDTree search parameters. */
@Namespace("open3d::geometry") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class KDTreeSearchParam extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KDTreeSearchParam(Pointer p) { super(p); }

    /** \enum SearchType
     * 
     *  \brief Specifies the search type for the search. */
    /** enum class open3d::geometry::KDTreeSearchParam::SearchType */
    public static final int
        Knn = 0,
        Radius = 1,
        Hybrid = 2;
    /** Get the search type (KNN, Radius, Hybrid) for the search parameter. */
    public native @Cast("open3d::geometry::KDTreeSearchParam::SearchType") int GetSearchType();
}
