// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


@Namespace("open3d::io") @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class RGBDSensor extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RGBDSensor(Pointer p) { super(p); }

    public native @Cast("bool") boolean Connect(long sensor_index);

    /** Capture one frame, return an RGBDImage.
     *  If \p enable_align_depth_to_color is true, the depth image will be
     *  warped to align with the color image; otherwise the raw depth image
     *  output will be saved. Setting \p enable_align_depth_to_color to
     *  false is useful when capturing at high resolution with high frame rates. */
    public native @SharedPtr RGBDImage CaptureFrame(
                @Cast("bool") boolean enable_align_depth_to_color);
}
