// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** \class Segment3D
 * 
 *  \brief A segment is a semantic interpretation of Eigen::ParametrizedLine
 *  which has an origin and an endpoint and exists finitely between them.
 * 
 *  \details One of the main motivations behind this class, and the Line3D
 *  taxonomy in general, is the ambiguity of the Eigen documentation with
 *  regards to the ParametrizedLine's direction. The documentation warns that
 *  the direction vector is expected to be normalized and makes no guarantees
 *  about behavior when this expectation is not met.  However, ParametrizedLine
 *  does behave correctly when the direction vector is scaled. This class
 *  exists as a seam to ensure the correct behavior can be produced regardless
 *  of what happens in the underlying Eigen implementation without changing
 *  the api surface for client code. */
@Namespace("open3d::geometry") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class Segment3D extends Line3D {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Segment3D(Pointer p) { super(p); }

    /** \brief Creates a Segment3D through two points.  The origin will take the
     *  value of p0, and the endpoint be p1. The direction will be a normalized
     *  vector from p0 to p1. */
    public static native @ByVal Segment3D Through(@Const @ByRef Vector3d p0,
                                 @Const @ByRef Vector3d p1);

    /** \brief Default constructor for Segment3D takes the start and end points
     *  of the segment \p start_point \p end_point */
    public Segment3D(@Const @ByRef Vector3d start_point,
                  @Const @ByRef Vector3d end_point) { super((Pointer)null); allocate(start_point, end_point); }
    private native void allocate(@Const @ByRef Vector3d start_point,
                  @Const @ByRef Vector3d end_point);

    /** \brief Takes a std::pair of points, the first to be used as the start
     *  point/origin and the second to be the end point */
    public Segment3D(@Const @ByRef std::pair<Eigen::Vector3d,Eigen::Vector3d> pair) { super((Pointer)null); allocate(pair); }
    private native void allocate(@Const @ByRef std::pair<Eigen::Vector3d,Eigen::Vector3d> pair);

    /** \brief Get the scalar length of the segment as the distance between the
     *  start point (origin) and the end point. */
    public native double Length();

    /** \brief Calculates the midpoint of the segment */
    public native @ByVal Vector3d MidPoint();

    /** \brief Get the end point of the segment */
    public native @Const @ByRef Vector3d EndPoint();

    /** \brief Transform the segment by the given matrix */
    public native void Transform(
                @Const @ByRef Eigen::Transform<double,3,Eigen::Affine> t);

    /** \brief Get an axis-aligned bounding box representing the enclosed volume
     *  of the line segment. */
    public native @ByVal AxisAlignedBoundingBox GetBoundingBox();

    /** \brief Calculates the intersection parameter between the line and a
     *  plane taking into account segment semantics. Returns an empty result if
     *  there is no intersection. On a Segment3D this means that intersections
     *  behind the origin and beyond the endpoint are invalid. */
    
    ///
    ///
    ///
    public native @Optional DoublePointer IntersectionParameter(
                @Const @ByRef Eigen::Hyperplane<double,3> plane);

    /** \brief Returns the lower intersection parameter for a segment with an
     *  axis aligned bounding box or empty if no intersection. Uses the slab
     *  method, see warning below.
     * 
     *  \details Calculates the lower intersection parameter of a parameterized
     *  segment with an axis aligned bounding box. The intersection point can be
     *  recovered with .Line().pointAt(...). If the segment does not
     *  intersect the box the optional return value will be empty. No
     *  intersection behind the segment origin will be counted, and if the
     *  segment originates from within the bounding box the parameter value will
     *  be 0. No intersection beyond the endpoint of the segment will be
     *  considered either.
     * 
     *  This implementation is based off of Tavian Barnes' optimized branchless
     *  slab method. https://tavianator.com/2011/segment_box.html. It runs in
     *  roughly 5% of the time as the the naive exact method, but can degenerate
     *  in specific conditions where a segment lies exactly in one of the AABB's
     *  planes.
     * 
     *  \warning A segment that lies exactly in one of the AABB's planes within
     *  the double floating point precision will not intersect correctly by this
     *  method */
    
    ///
    ///
    public native @Optional DoublePointer SlabAABB(
                @Const @ByRef AxisAlignedBoundingBox box);

    /** \brief Returns the lower intersection parameter for a segment with an
     *  axis aligned bounding box or empty if no intersection. This method is
     *  about 20x slower than the slab method, see details to know when to use.
     * 
     *  \details Calculates the lower intersection parameter of a parameterized
     *  segment with an axis aligned bounding box. The intersection point can be
     *  recovered with .Line().pointAt(...). If the segment does not
     *  intersect the box the return value will be empty.
     * 
     *  This implementation is a naive exact method that considers intersections
     *  with all six bounding box planes. It is not optimized for speed and
     *  should only be used when a problem is conditioned such that the slab
     *  method is unacceptable. Use this when a segment is likely to lie exactly
     *  in one of the AABB planes and false negatives are unacceptable.
     *  Typically this will only happen when segments are axis-aligned and both
     *  segments and bounding volumes are regularly spaced, and every
     *  intersection is important.  In such cases if performance is important, a
     *  simple custom implementation based on the problem directionality will
     *  likely outperform even the slab method. */
    public native @Optional DoublePointer ExactAABB(
                @Const @ByRef AxisAlignedBoundingBox box);

    /** \brief Clamps/bounds a parameter value to the closest valid place where
     *  the entity exists.  On a Line3D, the value will be unchanged, on a Ray3D
     *  a negative value will be made 0, and on a Segment3D a negative value
     *  will be made 0 and a positive value greater than Length() will take
     *  the value of Length() */
    public native double ClampParameter(double parameter);

    /** \brief Verifies that a given parameter value is valid for the semantics
     *  of the line object. For lines, any parameter is valid, for rays any
     *  positive parameter is valid, and for segments any parameter between 0
     *  and the segment length is valid. */
    public native @Cast("bool") boolean IsParameterValid(double parameter);
}
