// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** struct for defining a "set_active_camera" message, which sets the active
 *  camera as the object with the specified path in the scene tree. */
@Namespace("open3d::io::rpc::messages") @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class SetActiveCamera extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SetActiveCamera() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SetActiveCamera(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SetActiveCamera(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SetActiveCamera position(long position) {
        return (SetActiveCamera)super.position(position);
    }
    @Override public SetActiveCamera getPointer(long i) {
        return new SetActiveCamera((Pointer)this).offsetAddress(i);
    }

    public static native @StdString BytePointer MsgId();
    public native @StdString BytePointer path(); public native SetActiveCamera path(BytePointer setter);
}
