// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3D.*;


/** struct for defining a "set_time" message, which sets the current time
 *  to the specified value. */
@Namespace("open3d::io::rpc::messages") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DConfig.class)
public class SetTime extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SetTime(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SetTime(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public SetTime position(long position) {
        return (SetTime)super.position(position);
    }
    @Override public SetTime getPointer(long i) {
        return new SetTime((Pointer)this).offsetAddress(i);
    }

    public static native @StdString BytePointer MsgId();
    public SetTime() { super((Pointer)null); allocate(); }
    private native void allocate();
    public native int time(); public native SetTime time(int setter);
}
