// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class ArmadilloMesh
 *  \brief Data class for {@code ArmadilloMesh} contains the {@code ArmadilloMesh.ply} from
 *  the {@code Stanford 3D Scanning Repository}. */
@Namespace("open3d::data") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class ArmadilloMesh extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ArmadilloMesh(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ArmadilloMesh(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public ArmadilloMesh position(long position) {
        return (ArmadilloMesh)super.position(position);
    }
    @Override public ArmadilloMesh getPointer(long i) {
        return new ArmadilloMesh((Pointer)this).offsetAddress(i);
    }

    public ArmadilloMesh(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public ArmadilloMesh() { super((Pointer)null); allocate(); }
    private native void allocate();
    public ArmadilloMesh(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Path to the {@code ArmadilloMesh.ply} file. */
    public native @StdString BytePointer GetPath();
}
