// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class PLYPointCloud
 *  \brief Data class for {@code PLYPointCloud} contains the {@code fragment.ply}
 *  point cloud mesh from the {@code Redwood Living Room} dataset. */
@Namespace("open3d::data") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class PLYPointCloud extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public PLYPointCloud(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public PLYPointCloud(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public PLYPointCloud position(long position) {
        return (PLYPointCloud)super.position(position);
    }
    @Override public PLYPointCloud getPointer(long i) {
        return new PLYPointCloud((Pointer)this).offsetAddress(i);
    }

    public PLYPointCloud(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public PLYPointCloud() { super((Pointer)null); allocate(); }
    private native void allocate();
    public PLYPointCloud(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Path to the PLY format point cloud. */
    public native @StdString BytePointer GetPath();
}
