// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class SampleFountainRGBDImages
 *  \brief Data class for {@code SampleFountainRGBDImages} contains a sample set
 *  of 33 color and depth images from the {@code Fountain RGBD dataset}. */
@Namespace("open3d::data") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class SampleFountainRGBDImages extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SampleFountainRGBDImages(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SampleFountainRGBDImages(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public SampleFountainRGBDImages position(long position) {
        return (SampleFountainRGBDImages)super.position(position);
    }
    @Override public SampleFountainRGBDImages getPointer(long i) {
        return new SampleFountainRGBDImages((Pointer)this).offsetAddress(i);
    }

    public SampleFountainRGBDImages(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public SampleFountainRGBDImages() { super((Pointer)null); allocate(); }
    private native void allocate();
    public SampleFountainRGBDImages(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Returns List of paths to color image samples of size 33. */
    public native @StdString @StdVector BytePointer GetColorPaths();
    /** \brief Returns List of paths to depth image samples of size 33. */
    public native @StdString @StdVector BytePointer GetDepthPaths();
    /** \brief Path to camera poses at key frames log file {@code key.log}. */
    public native @StdString BytePointer GetKeyframePosesLogPath();
    /** \brief Path to mesh reconstruction. */
    public native @StdString BytePointer GetReconstructionPath();
}
