// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \brief SYCL device properties. */
@Namespace("open3d::core::sy") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class SYCLDevice extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SYCLDevice(Pointer p) { super(p); }

    public SYCLDevice(@Const @ByRef device sycl_device) { super((Pointer)null); allocate(sycl_device); }
    private native void allocate(@Const @ByRef device sycl_device);
    /** Fiendlly / descriptive name of the device. */
    public native @StdString BytePointer name(); public native SYCLDevice name(BytePointer setter);
    /** cpu, gpu, host, acc, custom, unknown. */
    public native @StdString BytePointer device_type(); public native SYCLDevice device_type(BytePointer setter);
    /** SYCL device. */
    public native @ByRef device device(); public native SYCLDevice device(device setter);
    /** Default queue for this device. */
    public native @ByRef queue queue(); public native SYCLDevice queue(queue setter);
    /** Preferred work group size */
    public native long max_work_group_size(); public native SYCLDevice max_work_group_size(long setter);
    /** Double precision support, else need to emulate. */
    public native @Cast("bool") boolean fp64(); public native SYCLDevice fp64(boolean setter);
    /** USM device allocations required for
     *  Open3D. */
    public native @Cast("bool") boolean usm_device_allocations(); public native SYCLDevice usm_device_allocations(boolean setter);
}
