// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.geometry;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DGeometry.*;


@Namespace("open3d::geometry") @Properties(inherit = org.bytedeco.open3d.presets.Open3DGeometryConfig.class)
public class Qhull extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public Qhull() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Qhull(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Qhull(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public Qhull position(long position) {
        return (Qhull)super.position(position);
    }
    @Override public Qhull getPointer(long i) {
        return new Qhull((Pointer)this).offsetAddress(i);
    }

    /** Computes the convex hull
     *  @param points Input points.
     *  @param joggle_inputs If true allows the algorithm to add random noise
     *         to the points to work around degenerate inputs. This adds the
     *         'QJ' option to the qhull command.
     *  @return The triangle mesh of the convex hull and the list of point
     *           indices that are part of the convex hull. */
    public static native @ByVal std::tuple<std::shared_ptr<open3d::geometry::TriangleMesh>,std::vector<size_t> > ComputeConvexHull(@StdVector Vector3d points,
                          @Cast("bool") boolean joggle_inputs/*=false*/);
    public static native @ByVal std::tuple<std::shared_ptr<open3d::geometry::TriangleMesh>,std::vector<size_t> > ComputeConvexHull(@StdVector Vector3d points);

    public static native @ByVal std::tuple<std::shared_ptr<open3d::geometry::TetraMesh>,std::vector<size_t> > ComputeDelaunayTetrahedralization(
                @StdVector Vector3d points);
}
