// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;



import tensorrt_llm.common.QuantMode;
import tensorrt_llm.global.Plugins;
import tensorrt_llm.presets.PluginsConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;


@Namespace("tensorrt_llm::plugins") @NoOffset @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class Fp8RowwiseGemmPluginProfiler extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public Fp8RowwiseGemmPluginProfiler() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Fp8RowwiseGemmPluginProfiler(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Fp8RowwiseGemmPluginProfiler(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public Fp8RowwiseGemmPluginProfiler position(long position) {
        return (Fp8RowwiseGemmPluginProfiler)super.position(position);
    }
    @Override public Fp8RowwiseGemmPluginProfiler getPointer(long i) {
        return new Fp8RowwiseGemmPluginProfiler((Pointer)this).offsetAddress(i);
    }


    public native void setQuantMode(@Const @ByRef QuantMode quantMode);

    public native int getMaxProfileM();
}
