// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;


import tensorrt_llm.global.Plugins;
import tensorrt_llm.presets.PluginsConfig;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;

// #endif
@Namespace("tensorrt_llm::plugins") @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class GemmAllReducePluginProfiler extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public GemmAllReducePluginProfiler() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GemmAllReducePluginProfiler(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GemmAllReducePluginProfiler(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public GemmAllReducePluginProfiler position(long position) {
        return (GemmAllReducePluginProfiler)super.position(position);
    }
    @Override public GemmAllReducePluginProfiler getPointer(long i) {
        return new GemmAllReducePluginProfiler((Pointer)this).offsetAddress(i);
    }

    public native void serializeToOwnFile(@ByVal GemmIdCore gemmId);

    public native void deserializeFromOwnFile(@ByVal GemmIdCore gemmId, @ByVal GemmDims problemShape);

    public native boolean useProfiler();
}
