// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;


@Namespace("tensorrt_llm::plugins") @NoOffset @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class GemmIdCublas extends GemmIdCore {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GemmIdCublas(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GemmIdCublas(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public GemmIdCublas position(long position) {
        return (GemmIdCublas)super.position(position);
    }
    @Override public GemmIdCublas getPointer(long i) {
        return new GemmIdCublas((Pointer)this).offsetAddress(i);
    }

    public native boolean transA(); public native GemmIdCublas transA(boolean setter);
    public native boolean transB(); public native GemmIdCublas transB(boolean setter);
    public native int outputDtype(); public native GemmIdCublas outputDtype(int setter);

    public GemmIdCublas(int n_, int k_, int dtype_, boolean transA_, boolean transB_,
            int output_dtype_) { super((Pointer)null); allocate(n_, k_, dtype_, transA_, transB_, output_dtype_); }
    private native void allocate(int n_, int k_, int dtype_, boolean transA_, boolean transB_,
            int output_dtype_);

    public GemmIdCublas() { super((Pointer)null); allocate(); }
    private native void allocate();

    public native @Name("operator ==") boolean equals(@Const @ByRef GemmIdCublas id);

    
}
