// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.plugins;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Plugins.*;

@Namespace("nvinfer1::v_1_0") @Opaque @Properties(inherit = tensorrt_llm.presets.PluginsConfig.class)
public class IPluginCreator extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public IPluginCreator() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public IPluginCreator(Pointer p) { super(p); }
}
