// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class DecoderInputBuffers extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DecoderInputBuffers(Pointer p) { super(p); }


    public DecoderInputBuffers(
            @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxDecoderSteps, @Const @ByRef BufferManager manager) { super((Pointer)null); allocate(maxBatchSize, maxDecoderSteps, manager); }
    private native void allocate(
            @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxBatchSize, @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxDecoderSteps, @Const @ByRef BufferManager manager);

    public native void setupMedusaLogits(@Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxNumSequences, @Const @ByRef Pointer modelConfig);

    /** Buffers for decoder setup
     <p>
     *  Input IDs of new requests, [maxBatchSize] */
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") SharedPtr inputsIds(); public native DecoderInputBuffers inputsIds(SharedPtr setter);
    /** Batch slots for setup step, [maxBatchSize] */
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") SharedPtr setupBatchSlots(); public native DecoderInputBuffers setupBatchSlots(SharedPtr setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") SharedPtr setupBatchSlotsDevice(); public native DecoderInputBuffers setupBatchSlotsDevice(SharedPtr setter);
    /** Helper buffer for copying sequence lengths, [maxBatchSize] */
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") SharedPtr fillValues(); public native DecoderInputBuffers fillValues(SharedPtr setter);
    public native @ByRef @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") SharedPtr fillValuesDevice(); public native DecoderInputBuffers fillValuesDevice(SharedPtr setter);

    /** Buffers for decoder forward
     <p>
     *  Requests for considered in decoder forward */
    public native @SharedPtr LlmRequest decoderRequests(); public native DecoderInputBuffers decoderRequests(LlmRequest setter);

    /** Logits of decoder requests */
    public native @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") @StdVector SharedPtr decoderLogits(); public native DecoderInputBuffers decoderLogits(SharedPtr setter);

    /** Maximum number of decoding steps of decoder requests.
     *  This is only more than 1 for external draft tokens speculative decoding. */
    public native @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::SizeType32") int maxDecoderSteps(); public native DecoderInputBuffers maxDecoderSteps(int setter);

    /** Batch slots for all decoder steps, [maxDecoderSteps][maxBatchSize] */
    public native @Cast("tensorrt_llm::batch_manager::DecoderInputBuffers::TensorPtr*") @StdVector SharedPtr forwardBatchSlots(); public native DecoderInputBuffers forwardBatchSlots(SharedPtr setter);

    /** Logits for requests in forwardBatchSlots (in the same order).
     *  [maxDecoderSteps][batchSize][1, beamWidth, vocabSizePadded], on gpu */
    

    /** Logits for speculative decoding (Medusa).
     *  The vector is sparse, only slots in forwardBatchSlots are used.
     *  [maxBatchSize][maxAcceptedDraftTokensPerStep][maxDraftTokens + 1, vocabSizePadded] */
    public native @StdVector std::vector<runtime::ITensor::SharedPtr> predictedDraftLogits(); public native DecoderInputBuffers predictedDraftLogits(std::vector<runtime::ITensor::SharedPtr> setter);
}
