// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


/** \brief Schedule up to maxNumRequests requests */
@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class MaxRequestsScheduler extends BaseCapacityScheduler {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MaxRequestsScheduler(Pointer p) { super(p); }

    public MaxRequestsScheduler(int maxNumRequests,
            @Cast("tensorrt_llm::batch_manager::LlmRequestState") int noScheduleUntilState/*=tensorrt_llm::batch_manager::LlmRequestState::kCONTEXT_INIT*/,
            @Cast("tensorrt_llm::batch_manager::LlmRequestState") int noScheduleAfterState/*=tensorrt_llm::batch_manager::LlmRequestState::kGENERATION_COMPLETE*/) { super((Pointer)null); allocate(maxNumRequests, noScheduleUntilState, noScheduleAfterState); }
    private native void allocate(int maxNumRequests,
            @Cast("tensorrt_llm::batch_manager::LlmRequestState") int noScheduleUntilState/*=tensorrt_llm::batch_manager::LlmRequestState::kCONTEXT_INIT*/,
            @Cast("tensorrt_llm::batch_manager::LlmRequestState") int noScheduleAfterState/*=tensorrt_llm::batch_manager::LlmRequestState::kGENERATION_COMPLETE*/);
    public MaxRequestsScheduler(int maxNumRequests) { super((Pointer)null); allocate(maxNumRequests); }
    private native void allocate(int maxNumRequests);

    /** \brief Takes as input a sorted list of requests and outputs a sorted lists of requests
     *         to update for this current iteration, and a map of requests to pause */
}
