// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.utility;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DUtility.*;


/** RAII Wrapper for C FILE*
 *  Throws exceptions in situations where the caller is not usually going to
 *  have proper handling code:
 *  - using an unopened CFile
 *  - errors and ferror from underlying calls (fclose, ftell, fseek, fread,
 *    fwrite, fgetpos, fsetpos)
 *  - reading a line that is too long, caller is unlikely to have proper code to
 *    handle a partial next line
 *  If you would like to handle any of these issues by not having your code
 *  throw, use try/catch (const Pointer &e) { ... } */
@Namespace("Pointer") @Properties(inherit = org.bytedeco.open3d.presets.Open3DUtilityConfig.class)
public class CFile extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CFile() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CFile(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CFile(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CFile position(long position) {
        return (CFile)super.position(position);
    }
    @Override public CFile getPointer(long i) {
        return new CFile((Pointer)this).offsetAddress(i);
    }

    /** The destructor closes the file automatically. */

    /** Open a file. */
    public native @Cast("bool") boolean Open(@StdString BytePointer filename, @StdString BytePointer mode);
    public native @Cast("bool") boolean Open(@StdString String filename, @StdString String mode);

    /** Returns the last encountered error for this file. */
    public native @StdString BytePointer GetError();

    /** Close the file. */
    public native void Close();

    /** Returns current position in the file (ftell). */
    public native @Cast("int64_t") long CurPos();

    /** Returns the file size in bytes. */
    public native @Cast("int64_t") long GetFileSize();

    /** Returns the number of lines in the file. */
    public native @Cast("int64_t") long GetNumLines();

    /** Throws if we hit buffer maximum. In most cases, calling code is only
     *  capable of processing a complete line, if it receives a partial line it
     *  will probably fail and it is very likely to fail/corrupt on the next
     *  call that receives the remainder of the line. */
    public native @Cast("const char*") BytePointer ReadLine();

    /** Read data to a buffer.
     *  @param data The data buffer to be written into.
     *  @param num_elems Number of elements to be read. The byte size of the
     *  element is determined by the size of buffer type. */

    /** Read data to a buffer.
     *  @param data The data buffer to be written into.
     *  @param elem_size Element size in bytes.
     *  @param num_elems Number of elements to read. */
    public native long ReadData(Pointer data, long elem_size, long num_elems);

    /** Returns the underlying C FILE pointer. */
    public native @Cast("FILE*") Pointer GetFILE();
}
