// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.utility;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.open3d.Vector3d;
import org.bytedeco.open3d.Vector3i;
import org.bytedeco.open3d.Vector2d;
import org.bytedeco.open3d.Vector2i;
import org.bytedeco.open3d.Vector4i;
import org.bytedeco.open3d.Matrix3d;
import org.bytedeco.open3d.Matrix4d;
import org.bytedeco.open3d.SizeVector;

import static org.bytedeco.open3d.global.Open3DUtility.*;


@Namespace("Pointer") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DUtilityConfig.class)
public class ProgressBar extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ProgressBar(Pointer p) { super(p); }

    public ProgressBar(long expected_count,
                    @StdString BytePointer progress_info,
                    @Cast("bool") boolean active/*=false*/) { super((Pointer)null); allocate(expected_count, progress_info, active); }
    private native void allocate(long expected_count,
                    @StdString BytePointer progress_info,
                    @Cast("bool") boolean active/*=false*/);
    public ProgressBar(long expected_count,
                    @StdString BytePointer progress_info) { super((Pointer)null); allocate(expected_count, progress_info); }
    private native void allocate(long expected_count,
                    @StdString BytePointer progress_info);
    public ProgressBar(long expected_count,
                    @StdString String progress_info,
                    @Cast("bool") boolean active/*=false*/) { super((Pointer)null); allocate(expected_count, progress_info, active); }
    private native void allocate(long expected_count,
                    @StdString String progress_info,
                    @Cast("bool") boolean active/*=false*/);
    public ProgressBar(long expected_count,
                    @StdString String progress_info) { super((Pointer)null); allocate(expected_count, progress_info); }
    private native void allocate(long expected_count,
                    @StdString String progress_info);
    public native void Reset(long expected_count,
                   @StdString BytePointer progress_info,
                   @Cast("bool") boolean active);
    public native void Reset(long expected_count,
                   @StdString String progress_info,
                   @Cast("bool") boolean active);
    public native @ByRef @Name("operator ++") ProgressBar increment();
    public native void SetCurrentCount(long n);
    public native long GetCurrentCount();
}
