// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class PeftCacheManager extends BasePeftCacheManager {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public PeftCacheManager(Pointer p) { super(p); }


    public PeftCacheManager(@Const @ByRef PeftCacheManagerConfig config, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig, @Const @ByRef BufferManager bufferManager) { super((Pointer)null); allocate(config, modelConfig, worldConfig, bufferManager); }
    private native void allocate(@Const @ByRef PeftCacheManagerConfig config, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig, @Const @ByRef BufferManager bufferManager);

    public native void addRequestPeft(@SharedPtr LlmRequest llmRequest, boolean tryGpuCache/*=true*/);
    public native void addRequestPeft(@SharedPtr LlmRequest llmRequest);

    public native @ByVal PeftTable ensureBatch(@SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest generationRequests,
            boolean resetGpuCache/*=false*/);
    public native @ByVal PeftTable ensureBatch(@SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest generationRequests);

    public native @ByVal EnsureBatchTaskResult ensureBatchMapTaskId(
            @SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest generationRequests, boolean resetGpuCache/*=false*/);
    public native @ByVal EnsureBatchTaskResult ensureBatchMapTaskId(
            @SharedPtr LlmRequest contextRequests, @SharedPtr LlmRequest generationRequests);

    public native boolean isTaskCached(long taskId);

    public native boolean isTaskDone(long taskId);

    public native boolean isTaskDoneDevice(long taskId);

    public native boolean isTaskCachedDevice(long taskId);

    public native void resetDeviceCache();

    public native void markRequestDone(@Const @ByRef LlmRequest llmReq, boolean pause/*=false*/);
    public native void markRequestDone(@Const @ByRef LlmRequest llmReq);

    public native @Cast("tensorrt_llm::batch_manager::SizeType32") int getMaxDevicePages();

    public native @Cast("tensorrt_llm::batch_manager::SizeType32") int getMaxHostPages();

    public native @Cast("tensorrt_llm::batch_manager::SizeType32") int determineNumPages(@SharedPtr LlmRequest llmRequest);

    public native boolean enabled();

    public native void updateTaskState(long taskId, long reqId, boolean terminate/*=false*/, boolean pause/*=false*/);
    public native void updateTaskState(long taskId, long reqId);

    public native void prefetchLoraWeights(@StdString BytePointer modelDir, @Const @ByRef BufferManager bufferManager);
    public native void prefetchLoraWeights(@StdString String modelDir, @Const @ByRef BufferManager bufferManager);
}
