// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.batch_manager;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.executor.CacheState;

import static tensorrt_llm.global.Batchmanager.*;


@Namespace("tensorrt_llm::batch_manager::rnn_state_manager") @NoOffset @Properties(inherit = tensorrt_llm.presets.BatchmanagerConfig.class)
public class RnnStateManager extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RnnStateManager(Pointer p) { super(p); }


    public RnnStateManager(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int maxNumSequences, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig, @Const @ByRef BufferManager bufferManager) { super((Pointer)null); allocate(maxNumSequences, modelConfig, worldConfig, bufferManager); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int maxNumSequences, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig, @Const @ByRef BufferManager bufferManager);

    public RnnStateManager(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int dState, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int dConv, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int numHeads, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int nGroups, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int headDim,
            @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int maxBatchSize, @Const @ByRef WorldConfig worldConfig, long stream, int dtype,
            int ssmCacheDtype, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32*") @StdVector IntPointer ppLayers, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int numLayers) { super((Pointer)null); allocate(dState, dConv, numHeads, nGroups, headDim, maxBatchSize, worldConfig, stream, dtype, ssmCacheDtype, ppLayers, numLayers); }
    private native void allocate(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int dState, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int dConv, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int numHeads, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int nGroups, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int headDim,
            @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int maxBatchSize, @Const @ByRef WorldConfig worldConfig, long stream, int dtype,
            int ssmCacheDtype, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32*") @StdVector IntPointer ppLayers, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int numLayers);

    // SKIPPED: public native void getPtrBuffers(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::TensorMap*") @ByRef runtime::StringPtrMap<runtime::ITensor> inputBuffers, @Const @ByRef ModelConfig modelConfig,
    // @Const @ByRef WorldConfig worldConfig);

    public native void fillSlotMapping(
            @ByRef ITensor dstPointers, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int dstSlotOffset, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int seqSlotIdx, @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int beamWidth);

    public native void allocateCacheBlocks(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::RequestIdType*") @StdVector LongPointer requestIds);

    public native void freeCacheBlock(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::RequestIdType") long requestId);

    public native @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int getCacheIndex(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::RequestIdType") long requestId);

    public native @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32*") @StdVector IntPointer getStateIndices(
            @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::RequestIdType*") @StdVector LongPointer requestIds, @StdVector BoolPointer isPadding);

    public native @ByVal @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::TensorPtr*") SharedPtr getConvStates(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int layerIdx);

    public native @ByVal @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::TensorPtr*") SharedPtr getSsmStates(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int layerIdx);

    public native @ByVal @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::TensorPtr*") SharedPtr getConvStates();

    public native @ByVal @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::TensorPtr*") SharedPtr getSsmStates();

    public native @NoException(true) int getConvStateDataType();

    public native @NoException(true) int getSsmStateDataType();

    public native @ByVal @NoException(true) CacheState.RnnModelConfig getRnnCacheStateModelConfig();

    public native @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") @NoException(true) int getMaxBatchSize();

    /** Returns the number of local RNN layers on this PP rank */
    public native @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") @NoException(true) int getNumLocalLayers();

    /** Returns the buffer manager */
    public native @Const @ByRef @NoException(true) BufferManager getBufferManager();

    public native @Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int getGlobalLayerNum(@Cast("tensorrt_llm::batch_manager::rnn_state_manager::RnnStateManager::SizeType32") int localOffset);
}
