// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


@Namespace("open3d::core") @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class CuBLASContext extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CuBLASContext(Pointer p) { super(p); }

    public static native @ByRef CuBLASContext GetInstance();

    
    

    public native @ByRef cublasHandle_t GetHandle(@Const @ByRef Device device);
}
