// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class FlightHelmetModel
 *  \brief Data class for {@code FlightHelmetModel} contains a flight helmet model
 *  file, along with material and various other texture files. The model file
 *  can be accessed using {@code GetPath()}, however in order to access the paths to
 *  the texture files one may use {@code GetPath(filename)} method or get the
 *  unordered map of filename to path using {@code GetPathMap()}. */
@Namespace("open3d::data") @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class FlightHelmetModel extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FlightHelmetModel(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public FlightHelmetModel(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public FlightHelmetModel position(long position) {
        return (FlightHelmetModel)super.position(position);
    }
    @Override public FlightHelmetModel getPointer(long i) {
        return new FlightHelmetModel((Pointer)this).offsetAddress(i);
    }

    public FlightHelmetModel(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public FlightHelmetModel() { super((Pointer)null); allocate(); }
    private native void allocate();
    public FlightHelmetModel(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Path to the {@code filename}. By default it returns the path to
     *  {@code FlightHelmet.gltf} file. Refer documentation page for available
     *  options. */
    public native @StdString BytePointer GetPath(@StdString BytePointer filename/*="flight_helmet"*/);
    public native @StdString BytePointer GetPath();
    public native @StdString String GetPath(@StdString String filename/*="flight_helmet"*/);

    /** \brief Returns the map of filename to path. Refer documentation page for
     *  available options. */
}
