// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class PTSPointCloud
 *  \brief Data class for {@code PTSPointCloud} contains a sample point-cloud of PTS
 *  format. */
@Namespace("open3d::data") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class PTSPointCloud extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public PTSPointCloud(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public PTSPointCloud(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public PTSPointCloud position(long position) {
        return (PTSPointCloud)super.position(position);
    }
    @Override public PTSPointCloud getPointer(long i) {
        return new PTSPointCloud((Pointer)this).offsetAddress(i);
    }

    public PTSPointCloud(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public PTSPointCloud() { super((Pointer)null); allocate(); }
    private native void allocate();
    public PTSPointCloud(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Path to the PTS format point cloud. */
    public native @StdString BytePointer GetPath();
}
