// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.core;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DCore.*;


/** \class RedwoodIndoorLivingRoom2
 *  \brief Data class for {@code RedwoodIndoorLivingRoom2} (Augmented ICL-NUIM
 *  Dataset), containing dense point cloud, rgb sequence, clean depth sequence,
 *  noisy depth sequence, oni sequence, and ground-truth camera trajectory.
 * 
 *      RedwoodIndoorLivingRoom2
 *      ├── colors
 *      │   ├── 00000.jpg
 *      │   ├── 00001.jpg
 *      │   ├── ...
 *      │   └── 02349.jpg
 *      ├── depth
 *      │   ├── 00000.png
 *      │   ├── 00001.png
 *      │   ├── ...
 *      │   └── 02349.png
 *      ├── depth_noisy
 *      │   ├── 00000.png
 *      │   ├── 00001.png
 *      │   ├── ...
 *      │   └── 02349.png
 *      ├── dist-model.txt
 *      ├── livingroom2.oni
 *      ├── livingroom2-traj.txt
 *      └── livingroom.ply */
@Namespace("open3d::data") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DCoreConfig.class)
public class RedwoodIndoorLivingRoom2 extends DownloadDataset {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RedwoodIndoorLivingRoom2(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public RedwoodIndoorLivingRoom2(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public RedwoodIndoorLivingRoom2 position(long position) {
        return (RedwoodIndoorLivingRoom2)super.position(position);
    }
    @Override public RedwoodIndoorLivingRoom2 getPointer(long i) {
        return new RedwoodIndoorLivingRoom2((Pointer)this).offsetAddress(i);
    }

    public RedwoodIndoorLivingRoom2(@StdString BytePointer data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString BytePointer data_root/*=""*/);
    public RedwoodIndoorLivingRoom2() { super((Pointer)null); allocate(); }
    private native void allocate();
    public RedwoodIndoorLivingRoom2(@StdString String data_root/*=""*/) { super((Pointer)null); allocate(data_root); }
    private native void allocate(@StdString String data_root/*=""*/);

    /** \brief Path to the point cloud. */
    public native @StdString BytePointer GetPointCloudPath();
    /** \brief Paths to the color images. */
    public native @StdString @StdVector BytePointer GetColorPaths();
    /** \brief Paths to the clean depth images. */
    public native @StdString @StdVector BytePointer GetDepthPaths();
    /** \brief Paths to the noisy depth images. */
    public native @StdString @StdVector BytePointer GetNoisyDepthPaths();
    /** \brief Paths to the ONI sequence. */
    public native @StdString BytePointer GetONIPath();
    /** \brief Path to the ground-truth camera trajectory. */
    public native @StdString BytePointer GetTrajectoryPath();
    /** \brief Path to the noise model. */
    public native @StdString BytePointer GetNoiseModelPath();
}
