// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief Exposes a limited set of KV cache manager functionalities */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class KVCacheEventManager extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KVCacheEventManager(Pointer p) { super(p); }

    public KVCacheEventManager(
            @SharedPtr BaseKVCacheManager kvCacheManager) { super((Pointer)null); allocate(kvCacheManager); }
    private native void allocate(
            @SharedPtr BaseKVCacheManager kvCacheManager);

    /** \brief Get the latest KV Cache events.
     *  @param timeout The maximum time to wait for new events. If nullopt, will only return when new events are
     *  available, or when the executor instance has shutdown. */
    // [CPP-FIX] public native @ByVal std::deque<tensorrt_llm::executor::KVCacheEvent> getLatestEvents(@Optional milliseconds timeout/*=std::nullopt*/);
    // [CPP-FIX] public native @ByVal std::deque<tensorrt_llm::executor::KVCacheEvent> getLatestEvents();
}
