// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class MooncakeTransferStatus extends TransferStatus {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MooncakeTransferStatus(Pointer p) { super(p); }

    public MooncakeTransferStatus(@ByVal transfer_engine_t engine, long batchId, long requestCount) { super((Pointer)null); allocate(engine, batchId, requestCount); }
    private native void allocate(@ByVal transfer_engine_t engine, long batchId, long requestCount);

    public native boolean isCompleted();

    public native @ByVal @Name("wait") TransferState _wait(long timeout_ms/*=-1*/);
    public native @ByVal @Name("wait") TransferState _wait();
}
