// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class MpiState extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MpiState() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MpiState(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MpiState(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MpiState position(long position) {
        return (MpiState)super.position(position);
    }
    @Override public MpiState getPointer(long i) {
        return new MpiState((Pointer)this).offsetAddress(i);
    }

    public native @Name("operator ==") @NoException(true) boolean equals(@Const @ByRef MpiState other);

    public native @StdString BytePointer toString();

    public native @StdVector IntPointer mRanks(); public native MpiState mRanks(IntPointer setter);
}
