// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import tensorrt_llm.batch_manager.RequestInfo;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class RequestAndBufferInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public RequestAndBufferInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public RequestAndBufferInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public RequestAndBufferInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public RequestAndBufferInfo position(long position) {
        return (RequestAndBufferInfo)super.position(position);
    }
    @Override public RequestAndBufferInfo getPointer(long i) {
        return new RequestAndBufferInfo((Pointer)this).offsetAddress(i);
    }

    public native @StdString BytePointer mAgentName(); public native RequestAndBufferInfo mAgentName(BytePointer setter);
    public native @StdString BytePointer mAddress(); public native RequestAndBufferInfo mAddress(BytePointer setter);
    public native @ByRef RequestInfo mRequestInfo(); public native RequestAndBufferInfo mRequestInfo(RequestInfo setter);
    public native @StdVector MemoryDesc mBufferDescs(); public native RequestAndBufferInfo mBufferDescs(MemoryDesc setter);
    public native @StdString @Optional BytePointer mMetadata(); public native RequestAndBufferInfo mMetadata(BytePointer setter);
    public native int mValidConnectionIdx(); public native RequestAndBufferInfo mValidConnectionIdx(int setter);
    public native @Cast("uint8_t*") @StdVector BytePointer mBufferKinds(); public native RequestAndBufferInfo mBufferKinds(BytePointer setter);

    public static native void serialize(@Const @ByRef RequestAndBufferInfo requestAndBufferInfo, @Cast("std::ostream*") @ByRef Pointer os);

    public static native @ByVal RequestAndBufferInfo deserialize(@Cast("std::istream*") @ByRef Pointer is);

    public static native long serializedSize(@Const @ByRef RequestAndBufferInfo requestAndBufferInfo);
}
