// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class SocketState extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SocketState() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SocketState(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SocketState(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SocketState position(long position) {
        return (SocketState)super.position(position);
    }
    @Override public SocketState getPointer(long i) {
        return new SocketState((Pointer)this).offsetAddress(i);
    }

    public native @Name("operator ==") @NoException(true) boolean equals(@Const @ByRef SocketState other);

    public native @StdString BytePointer toString();

    public native @Cast("std::uint16_t") short mPort(); public native SocketState mPort(short setter);
    public native @StdString BytePointer mIp(); public native SocketState mIp(BytePointer setter);
}
