// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


/** \brief Struct that holds the logits information when using direct transfer */
@Namespace("tensorrt_llm::executor") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class SpeculativeDecodingFastLogitsInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SpeculativeDecodingFastLogitsInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SpeculativeDecodingFastLogitsInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SpeculativeDecodingFastLogitsInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SpeculativeDecodingFastLogitsInfo position(long position) {
        return (SpeculativeDecodingFastLogitsInfo)super.position(position);
    }
    @Override public SpeculativeDecodingFastLogitsInfo getPointer(long i) {
        return new SpeculativeDecodingFastLogitsInfo((Pointer)this).offsetAddress(i);
    }

    /** \brief Draft request id */
    public native long draftRequestId(); public native SpeculativeDecodingFastLogitsInfo draftRequestId(long setter);

    /** \brief MPI world rank of the draft model leader */
    public native int draftParticipantId(); public native SpeculativeDecodingFastLogitsInfo draftParticipantId(int setter);

    /** \brief Returns the struct serialized into a tensor that can be used as generation logits input */
    public native @ByVal Tensor toTensor();
}
