// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.pipelines;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DPipelines.*;


/** \class GlobalOptimizationGaussNewton
 * 
 *  \brief Global optimization with Gauss-Newton algorithm. */
@Namespace("open3d::pipelines::registration") @Properties(inherit = org.bytedeco.open3d.presets.Open3DPipelinesConfig.class)
public class GlobalOptimizationGaussNewton extends GlobalOptimizationMethod {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GlobalOptimizationGaussNewton(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GlobalOptimizationGaussNewton(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public GlobalOptimizationGaussNewton position(long position) {
        return (GlobalOptimizationGaussNewton)super.position(position);
    }
    @Override public GlobalOptimizationGaussNewton getPointer(long i) {
        return new GlobalOptimizationGaussNewton((Pointer)this).offsetAddress(i);
    }

    /** \brief Default Constructor. */
    public GlobalOptimizationGaussNewton() { super((Pointer)null); allocate(); }
    private native void allocate();
    public native void OptimizePoseGraph(
                @ByRef PoseGraph pose_graph,
                @Const @ByRef GlobalOptimizationConvergenceCriteria criteria,
                @Const @ByRef GlobalOptimizationOption option);
}
