// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.pipelines;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DPipelines.*;


/** \class GlobalOptimizationMethod
 * 
 *  \brief Base class for global optimization method. */
@Namespace("open3d::pipelines::registration") @Properties(inherit = org.bytedeco.open3d.presets.Open3DPipelinesConfig.class)
public class GlobalOptimizationMethod extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GlobalOptimizationMethod(Pointer p) { super(p); }

    /** \brief Default Constructor. */
    /** \brief Run pose graph optimization method.
     * 
     *  @param pose_graph The pose graph to be optimized (in-place).
     *  @param criteria Convergence criteria.
     *  @param option Global optimization options. */
    public native void OptimizePoseGraph(
                @ByRef PoseGraph pose_graph,
                @Const @ByRef GlobalOptimizationConvergenceCriteria criteria,
                @Const @ByRef GlobalOptimizationOption option);
}
