// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.open3d.utility;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.open3d.global.Open3DUtility.*;


@Namespace("open3d::utility") @NoOffset @Properties(inherit = org.bytedeco.open3d.presets.Open3DUtilityConfig.class)
public class ScopeTimer extends Timer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ScopeTimer(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public ScopeTimer(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public ScopeTimer position(long position) {
        return (ScopeTimer)super.position(position);
    }
    @Override public ScopeTimer getPointer(long i) {
        return new ScopeTimer((Pointer)this).offsetAddress(i);
    }

    public ScopeTimer(@StdString BytePointer scope_timer_info/*=""*/) { super((Pointer)null); allocate(scope_timer_info); }
    private native void allocate(@StdString BytePointer scope_timer_info/*=""*/);
    public ScopeTimer() { super((Pointer)null); allocate(); }
    private native void allocate();
    public ScopeTimer(@StdString String scope_timer_info/*=""*/) { super((Pointer)null); allocate(scope_timer_info); }
    private native void allocate(@StdString String scope_timer_info/*=""*/);
}
