// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.thop;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Thop.*;


@Namespace("tensorrt_llm::torch_ext") @Properties(inherit = tensorrt_llm.presets.ThopConfig.class)
public class KvCachePoolPointers extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public KvCachePoolPointers() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public KvCachePoolPointers(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public KvCachePoolPointers(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public KvCachePoolPointers position(long position) {
        return (KvCachePoolPointers)super.position(position);
    }
    @Override public KvCachePoolPointers getPointer(long i) {
        return new KvCachePoolPointers((Pointer)this).offsetAddress(i);
    }

    public native Pointer primaryPoolPtr(); public native KvCachePoolPointers primaryPoolPtr(Pointer setter);
    public native Pointer secondaryPoolPtr(); public native KvCachePoolPointers secondaryPoolPtr(Pointer setter);
    public native Pointer primaryBlockScalePoolPtr(); public native KvCachePoolPointers primaryBlockScalePoolPtr(Pointer setter);
    public native Pointer secondaryBlockScalePoolPtr(); public native KvCachePoolPointers secondaryBlockScalePoolPtr(Pointer setter);
}
