// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class BufferView extends IBuffer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BufferView(Pointer p) { super(p); }
    /** Downcast constructor. */
    public BufferView(IBuffer pointer) { super((Pointer)null); allocate(pointer); }
    @Namespace private native @Name("dynamic_cast<tensorrt_llm::runtime::BufferView*>") void allocate(IBuffer pointer);
    @Override public IBuffer asIBuffer() { return asIBuffer(this); }
    @Namespace public static native @Name("static_cast<tensorrt_llm::runtime::IBuffer*>") IBuffer asIBuffer(BufferView pointer);

    public BufferView(@ByVal IBuffer buffer, @Cast("std::size_t") long offset, @Cast("std::size_t") long size) { super((Pointer)null); allocate(buffer.asIBuffer(), offset, size); }
    private native void allocate(@ByVal IBuffer buffer, @Cast("std::size_t") long offset, @Cast("std::size_t") long size);

    public native Pointer data();

    public native @Cast("size_t") long getSize();

    public native @Cast("size_t") long getCapacity();

    public native @Cast("tensorrt_llm::runtime::MemoryType") int getMemoryType();

    public native void resize(@Cast("std::size_t") long newSize);

    public native void release();
}
