// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Opaque @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class gdr_info_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public gdr_info_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public gdr_info_t(Pointer p) { super(p); }
}
