// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::runtime::lora") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class LoraModuleConfig extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LoraModuleConfig(Pointer p) { super(p); }

    public LoraModuleConfig(@ByVal @Cast("tensorrt_llm::runtime::lora::LoraModuleConfig::TensorPtr*") ITensor loraConfigTensor) { super((Pointer)null); allocate(loraConfigTensor); }
    private native void allocate(@ByVal @Cast("tensorrt_llm::runtime::lora::LoraModuleConfig::TensorPtr*") ITensor loraConfigTensor);

    public native int moduleId(); public native LoraModuleConfig moduleId(int setter);
    public native int layerId(); public native LoraModuleConfig layerId(int setter);
    public native int adapterSize(); public native LoraModuleConfig adapterSize(int setter);
    public native @Cast("bool") boolean isDora(); public native LoraModuleConfig isDora(boolean setter);
}
