// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


/**
 * \brief Manages LoRA tensors.
 * \details Handles formatting input tensors and populating trt engine params related to LoRA.
 */
@Namespace("tensorrt_llm::runtime") @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class LoraManager extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public LoraManager(Pointer p) { super(p); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public LoraManager(long size) { super((Pointer)null); allocateArray(size); }
    private native void allocateArray(long size);
    @Override public LoraManager position(long position) {
        return (LoraManager)super.position(position);
    }
    @Override public LoraManager getPointer(long i) {
        return new LoraManager((Pointer)this).offsetAddress(i);
    }


    public LoraManager() { super((Pointer)null); allocate(); }
    private native void allocate();

    /**
     * \brief Sets up and configures LoraManager. Allocates and needed device / host memory
     * @param modelConfig [in] : a ModelConfig.
     * @param worldConfig [in] : a WorldConfig
     * @param manager [in] : and BufferManager used to allocate memory
     */
    public native void create(@Const @ByRef ModelConfig modelConfig);

    /**
     * \brief same as fillInputTensors but for an entire batch
     */
    public native void fillInputTensors(@ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor weightsPtrs, @ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor adapterSizes, @Const @ByRef PeftTable peftTable,
            @Cast("const tensorrt_llm::runtime::LoraManager::ReqIdsVec") long reqIds, @Const @StdVector @ByRef IntPointer reqBeamWidth, @Const @ByRef ModelConfig modelConfig,
            @Const @ByRef WorldConfig worldConfig);

    /**
     * \brief fill batch input tensors for LoRA.  This method fills on batch slot.
     * @param weightsPtrs [out] : the tensor of pointers to lora weights to fill.
     *                          (ie for {@code *_lora_weights_pointers_*} fields)
     * @param adapterSizes [out] : the adapter sizes tensor to fill
     *                           (ie for {@code *lora_low_rank_*} fields)
     * @param peftTable [in] : reqId to LoraCache::Values
     * @param batchIdx [in] : the request batch index
     * @param beamWidth [in] : the request beam width
     * @param modelConfig [in] : a ModelConfig
     * @param worldConfig [in] : a WorldConfig
     */
    public native void fillInputTensors(@ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor weightsPtrs, @ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor adapterSizes, @StdVector runtime::LoraCache::TaskLayerModuleConfig peftValues,
            @Cast("tensorrt_llm::runtime::SizeType32") int batchIdx, @Cast("tensorrt_llm::runtime::SizeType32") int beamWidth, @Const @ByRef ModelConfig modelConfig, @Const @ByRef WorldConfig worldConfig);

    /**
     * \brief fill tensor map for trt engine context
     * @param inputTensors [out] : the tensor map to fill
     * @param weightsPtrs [in] : tensor of weights pointers as filled in fillInputTensors
     * @param adapterSizes [in] : tensor of adapter sizes as filled in fillInputTensors
     * @param modelConfig [in] : a ModelConfig
     * @param worldConfig [in] : a WorldConfig
     */
    public native void insertInputTensors(@Cast("tensorrt_llm::runtime::LoraManager::TensorMap*") @ByRef runtime::StringPtrMap<tensorrt_llm::runtime::ITensor> inputTensors, @ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor weightsPtrs, @ByVal @Cast("tensorrt_llm::runtime::LoraManager::TensorPtr*") ITensor adapterSizes,
            @Const @ByRef ModelConfig modelConfig, @Const @ByRef WorldConfig worldConfig);
}
