// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class TllmRuntime extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TllmRuntime(Pointer p) { super(p); }


    public TllmRuntime(@Const @ByRef RawEngine rawEngine, ILogger logger, @Cast("bool") boolean useGpuDirectStorage/*=false*/,
            float gpuWeightsPercent/*=1.0f*/, @Cast("bool") boolean useShapeInference/*=true*/) { super((Pointer)null); allocate(rawEngine, logger, useGpuDirectStorage, gpuWeightsPercent, useShapeInference); }
    private native void allocate(@Const @ByRef RawEngine rawEngine, ILogger logger, @Cast("bool") boolean useGpuDirectStorage/*=false*/,
            float gpuWeightsPercent/*=1.0f*/, @Cast("bool") boolean useShapeInference/*=true*/);
    public TllmRuntime(@Const @ByRef RawEngine rawEngine, ILogger logger) { super((Pointer)null); allocate(rawEngine, logger); }
    private native void allocate(@Const @ByRef RawEngine rawEngine, ILogger logger);

    public native @Cast("tensorrt_llm::runtime::SizeType32") int getNbContexts();

    public native @ByRef IExecutionContext getContext(@Cast("tensorrt_llm::runtime::SizeType32") int contextIndex);

    public native @Cast("tensorrt_llm::runtime::SizeType32") int getNbProfiles();

    /** \brief If multiple TensorRT optimization profiles are built in the engine, this function selects the
     *  corresponding profile that is going to be used based on the runtime shape, for now, TensorRT LLM only split
     *  multiple profiles on the num_tokens dimension, hence the profile index is selected based on which profile
     *  handles the actual num_tokens
     *  @return The index of the selected TensorRT optimization profile */
    public native @Cast("tensorrt_llm::runtime::SizeType32") int getOptProfileId(int numTokens, @Const @StdVector @ByRef IntPointer splitPoints);

    public native @ByRef IExecutionContext addContext(int profileIndex);

    public native void clearContexts();

    /** \brief Set input tensors from tensorMap for all contexts.
     *  \details The function can be used to set static input tensors for all iterations. If a tensor was set this way,
     *  it doesn't need to included in calls to setInputTensors anymore. */
    public native void setStaticInputTensors(@Cast("const tensorrt_llm::runtime::TllmRuntime::TensorMap*") @ByRef StringPtrMap<tensorrt_llm::runtime::ITensor> tensorMap);

    /** \brief Set input tensors from tensorMap for context at contextIndex.
     *  \details The function expects that all input tensors (excluding the ones set by setStaticInputTensors) are
     *  contained in the tensorMap. If a tensor is missing, has a bad shape or type, it will throw. */
    public native void setInputTensors(@Cast("tensorrt_llm::runtime::SizeType32") int contextIndex, @Cast("const tensorrt_llm::runtime::TllmRuntime::TensorMap*") @ByRef StringPtrMap<tensorrt_llm::runtime::ITensor> tensorMap);

    /** \brief Set output tensors from tensorMap for context at contextIndex.
     *  \details The function expects that all output tensors are contained in the tensorMap. If a tensor is missing and
     *  shape inference is enabled, it will allocate the tensor on GPU and insert it into the tensorMap. Otherwise it
     *  will throw. */
    public native void setOutputTensors(@Cast("tensorrt_llm::runtime::SizeType32") int contextIndex, @Cast("tensorrt_llm::runtime::TllmRuntime::TensorMap*") @ByRef StringPtrMap<tensorrt_llm::runtime::ITensor> tensorMap);

    public native @Cast("bool") boolean executeContext(@Cast("tensorrt_llm::runtime::SizeType32") int contextIndex);

    public native @Cast("const tensorrt_llm::runtime::CudaStream*") @ByRef Pointer getStream();

    public native @Cast("tensorrt_llm::runtime::BufferManager::CudaStreamPtr") Pointer getStreamPtr();

    public native @ByRef ICudaEngine getEngine();

    public native @ByRef IEngineInspector getEngineInspector();

    public native @ByRef BufferManager getBufferManager();

    public native void setLayerProfiler();
    public native @Cast("bool") boolean hasLayerProfiler(@Cast("tensorrt_llm::runtime::SizeType32") int contextId);
    public native @StdString BytePointer getLayerProfileInfo();
    public native void reportToProfiler(@Cast("tensorrt_llm::runtime::SizeType32") int contextId);
    public native void loadManagedWeights(@Const @ByRef RawEngine rawEngine, int localRank);
    public native void initializeUserBuffer(@Const @ByRef WorldConfig world_config, @Cast("tensorrt_llm::runtime::SizeType32") int maxBatchSize,
            @Cast("tensorrt_llm::runtime::SizeType32") int maxBeamWidth, @Cast("tensorrt_llm::runtime::SizeType32") int maxSequenceLength, @Cast("tensorrt_llm::runtime::SizeType32") int hiddenSize,
            @Cast("tensorrt_llm::runtime::SizeType32*") @Optional IntPointer maxNumTokens);

    public native @Cast("bool") boolean isUserBufferEnabled();

    public native @NoException(true) void setCurrentBeamWidths(@Const @StdVector @ByRef IntPointer beamWidth);

    public native @Cast("const tensorrt_llm::runtime::SizeType32") @NoException(true) int getCurrentBeamWidth();
}
