// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.runtime;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;

@Namespace("tensorrt_llm::runtime") @NoOffset @Properties(inherit = tensorrt_llm.presets.RuntimeConfig.class)
public class TorchView extends ITensor {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TorchView(Pointer p) { super(p); }
    /** Downcast constructor. */
    public TorchView(ITensor pointer) { super((Pointer)null); allocate(pointer); }
    @Namespace private native @Name("dynamic_cast<tensorrt_llm::runtime::TorchView*>") void allocate(ITensor pointer);
    public ITensor asITensor() { return asITensor(this); }
    @Namespace public static native @Name("static_cast<tensorrt_llm::runtime::ITensor*>") ITensor asITensor(TorchView pointer);

    public static native @ByVal ITensor of(@ByRef(true) Tensor tensor);

    public native Pointer data();

    public native @Cast("size_t") long getSize();

    public native @Cast("std::size_t") long getCapacity();

    public native @ByVal DataType getDataType();

    public native @Cast("tensorrt_llm::runtime::MemoryType") int getMemoryType();

    public native void release();

    public native @Const @ByRef Shape getShape();

    public native void reshape(@Const @ByRef Shape dims);
}
