// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class MooncakeBase64Helper extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public MooncakeBase64Helper() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public MooncakeBase64Helper(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MooncakeBase64Helper(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public MooncakeBase64Helper position(long position) {
        return (MooncakeBase64Helper)super.position(position);
    }
    @Override public MooncakeBase64Helper getPointer(long i) {
        return new MooncakeBase64Helper((Pointer)this).offsetAddress(i);
    }

    public static native @StdString BytePointer encode(@Const @StdVector @ByRef BytePointer data);

    public static native @StdVector @ByVal BytePointer decode(@StdString BytePointer encoded);
    public static native @StdString BytePointer decodeToString(@StdString BytePointer encoded);
}
