// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import org.bytedeco.tensorrt_llm.*;


@Namespace("tensorrt_llm::executor::kv_cache") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class MpiConnection extends Connection {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public MpiConnection(Pointer p) { super(p); }

    public MpiConnection(@Const MpiComm comm, int rank) { super((Pointer)null); allocate(comm, rank); }
    private native void allocate(@Const MpiComm comm, int rank);
    public native void send(@Const @ByRef DataContext ctx, @Const Pointer data, @Cast("size_t") long size);
    public native void recv(@Const @ByRef DataContext ctx, Pointer data, @Cast("size_t") long size);
}
