// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class NixlHelper extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public NixlHelper() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public NixlHelper(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public NixlHelper(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public NixlHelper position(long position) {
        return (NixlHelper)super.position(position);
    }
    @Override public NixlHelper getPointer(long i) {
        return new NixlHelper((Pointer)this).offsetAddress(i);
    }

    public static native @ByVal nixl_mem_t convert(MemoryType type);
    public static native @ByVal nixlBasicDesc convert(@Const @ByRef MemoryDesc desc);
    public static native @ByVal nixl_reg_dlist_t convertRegDlist(@Const @ByRef RegisterDescs descs);
    public static native @ByVal nixl_reg_dlist_t convertRegDlist(@Const @ByRef FileDescs descs);
    public static native @ByVal nixl_xfer_op_t convert(@Const @ByRef TransferOp op);
    public static native @ByVal nixl_xfer_dlist_t convertXferDist(@Const @ByRef TransferDescs descs);
    public static native @ByVal nixl_xfer_dlist_t convertXferDist(@Const @ByRef FileDescs descs);
    public static native void posixGpuToFileFallback(@Const @ByRef MemoryDescs memoryDesc, @Const @ByRef FileDescs fileDescs);
    public static native void posixFileToGpuFallback(@Const @ByRef MemoryDescs memoryDesc, @Const @ByRef FileDescs fileDescs);

    /** \brief Coalesce contiguous memory regions to reduce memory registration overhead.
     *  Adjacent memory regions with the same deviceId will be merged into a single region.
     *  @param descs Memory descriptors to coalesce
     *  @return Coalesced MemoryDescs */
    public static native @ByVal MemoryDescs coalesceMemoryDescs(@Const @ByRef MemoryDescs descs);

    /** \brief Coalesce contiguous memory regions in src and dst to reduce transfer count.
     *  If src[i] and src[i+1] are contiguous, and dst[i] and dst[i+1] are also contiguous
     *  (with same deviceId), they will be merged into a single transfer.
     *  @param srcDescs Source memory descriptors
     *  @param dstDescs Destination memory descriptors
     *  @return Pair of coalesced (src, dst) MemoryDescs */

    /** \brief Split VRAM descs at VMM chunk boundaries detected via cuMemGetAddressRange.
     *  For cudaMalloc memory (single allocation), descs pass through unchanged.
     *  @param detectedChunkSize [out] Set to the VMM chunk size if detected, 0 otherwise. */
    public static native @ByVal MemoryDescs splitVmmDescs(@Const @ByRef MemoryDescs descs, @Cast("size_t*") @ByRef LongPointer detectedChunkSize);
}
