// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.bytedeco.tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class NotificationInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public NotificationInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public NotificationInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public NotificationInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public NotificationInfo position(long position) {
        return (NotificationInfo)super.position(position);
    }
    @Override public NotificationInfo getPointer(long i) {
        return new NotificationInfo((Pointer)this).offsetAddress(i);
    }


    public static native @Cast("size_t") long serializedSize(@Const @ByRef NotificationInfo notificationInfo);
}
