// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class AgentConnection extends Connection {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AgentConnection(Pointer p) { super(p); }

    public AgentConnection(
            @StdString BytePointer mAgentName, @StdString BytePointer mRemoteAgentName, AgentConnectionManager mAgentConnectionManager) { super((Pointer)null); allocate(mAgentName, mRemoteAgentName, mAgentConnectionManager); }
    private native void allocate(
            @StdString BytePointer mAgentName, @StdString BytePointer mRemoteAgentName, AgentConnectionManager mAgentConnectionManager);
    public AgentConnection(
            @StdString String mAgentName, @StdString String mRemoteAgentName, AgentConnectionManager mAgentConnectionManager) { super((Pointer)null); allocate(mAgentName, mRemoteAgentName, mAgentConnectionManager); }
    private native void allocate(
            @StdString String mAgentName, @StdString String mRemoteAgentName, AgentConnectionManager mAgentConnectionManager);
    public native void send(@Const @ByRef Pointer ctx, @Const Pointer data, long size);
    public native void recv(@Const @ByRef Pointer ctx, Pointer data, long size);
    // [CPP-FIX] public native void sendRequestAndBufferInfo(@ByRef RequestInfo requestInfo,
    // FIXED: @StdVector std::optional<size_t> cacheBufferIds, int validConnectionIdx);
    public native void setHasLoadRemoteAgent(boolean hasLoadRemoteAgent);
    public native boolean hasLoadRemoteAgent();
    public native void sendReadySignal(@Const @ByRef Pointer ctx, boolean isReady);
    public native boolean recvReadySignal(@Const @ByRef Pointer ctx);

    public native void activateBuffer(@Cast("uint8_t") byte kind);
    public native @Optional LongPointer getPreAssignedBufferId(@Cast("uint8_t") byte kind);
}
