// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class ConnectionManager extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public ConnectionManager(Pointer p) { super(p); }


    public native @Const Pointer recvConnect(@Const @ByRef Pointer ctx, Pointer data, long size);

    public native @Cast("const Pointer**") @StdVector PointerPointer getConnections(@Const @ByRef Pointer state);

    public native @Const @ByRef Pointer getCommState();
    public native boolean isRunning();
}
