// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Namespace("tensorrt_llm::executor::kv_cache") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class DataContext extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DataContext(Pointer p) { super(p); }

    public DataContext(int tag) { super((Pointer)null); allocate(tag); }
    private native void allocate(int tag);

    public native @NoException(true) int getTag();
}
