// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;


import tensorrt_llm.batch_manager.IdType;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;


@Name("tensorrt_llm::executor::Response::Impl") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class Impl extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Impl(Pointer p) { super(p); }

    public Impl(@ByVal long requestId, @StdString BytePointer errorMsg, @Optional long clientId) { super((Pointer)null); allocate(requestId, errorMsg, clientId); }
    private native void allocate(@ByVal long requestId, @StdString BytePointer errorMsg, @Optional long clientId);
    public Impl(@ByVal long requestId, @StdString String errorMsg, @Optional long clientId) { super((Pointer)null); allocate(requestId, errorMsg, clientId); }
    private native void allocate(@ByVal long requestId, @StdString String errorMsg, @Optional long clientId);

    public Impl(@ByVal long requestId, @ByVal Result Result, @Optional long clientId) { super((Pointer)null); allocate(requestId, Result, clientId); }
    private native void allocate(@ByVal long requestId, @ByVal Result Result, @Optional long clientId);

    public native boolean hasError();

    public native boolean hasResult();

    public native @ByVal long getRequestId();

    public native @Optional long getClientId();

    /** Could throw exception if no result is available */
    public native @Const @ByRef Result getResult();

    public native @StdString BytePointer getErrorMsg();
}
