// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package tensorrt_llm.executor;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static tensorrt_llm.global.Executor.*;


/** \brief Configuration for prompt tuning */
@Namespace("tensorrt_llm::executor") @NoOffset @Properties(inherit = tensorrt_llm.presets.ExecutorConfig.class)
public class PromptTuningConfig extends Pointer {
    // [CPP-FIX] broken decl removed:
    // static { Loader.load(); }
    // /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    // public PromptTuningConfig(Pointer p) { super(p); }
    // 
    // public PromptTuningConfig(
    // // [CPP-FIX] @ByVal Tensor embeddingTable, @Optional Pointer inputTokenExtraIds/*=std::nullopt*/) { super((Pointer)null); allocate(embeddingTable, inputTokenExtraIds); }
    // // [CPP-FIX] broken signature removed:
    // // private native void allocate(
    // // // [CPP-FIX] @ByVal Tensor embeddingTable, @Optional Pointer inputTokenExtraIds/*=std::nullopt*/);
    public PromptTuningConfig(
            @ByVal Tensor embeddingTable) { super((Pointer)null); allocate(embeddingTable); }
    private native void allocate(
            @ByVal Tensor embeddingTable);

    public native @ByVal Tensor getEmbeddingTable();

    public native @Optional Pointer getInputTokenExtraIds();
}
